### ISSUE TITLE
[REQUEST] Document the Python validator feature set

### ISSUE THREAD

**Issue by fabrice-v** [MobilityData/gtfs-validator#101]
**Additional context**
This issue consist in figuring out the feature set of the Google provided python GTFS validator
code: https://github.com/google/transitfeed/tree/master/transitfeed
"documentation": https://github.com/google/transitfeed/wiki/FeedValidator

 and report them in our own rules spreadsheet : https://docs.google.com/spreadsheets/d/1Qu9hoZWVPcsMf0ZwtmG6upcgjY97Sj5BXljnUrH9UlU/edit#gid=0

we need this to be able to prioritize our own implementation effort towards reaching feature parity before adding extra checks.

**Comment by maximearmstrong** [comment]
**Architecture overview:**

Here are the different components of the Google transit feed validator, with a short description of their role within the validator.

- version.py : software version

- compat.py : Python2 and Python3 compatibility

- error.py : error types

- gtfsfactory.py : a factory for the default GTFS objects

- gtfsfactoryuser.py : specific gtfsfactory
	- shape.py : geographic representation of a specific gtfsfactory

- gtfsobjectbase.py : abstract gtfs object.
	- agency.py : agency object and its validation methods
	- fareattribute.py : fare attribute object and its validation methods
	- farerule.py : fare rule object and its validation methods
	- feedinfo.py : feed info object and its validation methods
	- frequency.py : frequency object and its validation methods
	- route.py : route object and its validation methods
	- shapepoint.py : shape point object
	- stop.py : stop object and its validation methods
	- transfer.py : transfer object and its validation methods
	- trip.py : trip object and its validation methods

- loader.py : loads the feed files, calls problems.py
	- shapeloader.py : loads only the feed shapes files

- problems.py : the possible problems that can occur during validation

- schedule.py : a schedule object, composed of stops(StopTImes in db), routes, trips and an agency

- serviceperiod : service (dates) for when a trips operate

- shapelib.py : lib for shape.py 

- stoptime.py : a single stop, an instance of Stop. Every stop time is added to StopTimes table in db. Validation performances are bad using the gtfsfactory, so Stop class is used instead.

- util.py : utils for the validation

**Comment by maximearmstrong** [comment]
The document [Members] Error support prioritization is fully updated with Google Python Validator rules https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0
