### ISSUE TITLE
is the StopTimeWithDepartureBeforeArrivalTimeNotice still in use?

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1048]
It's only present in RULES.md [here](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#stoptimewithdeparturebeforearrivaltimenotice) and nowhere else in the documentation. 

If it's an old rule that got depreciated, it should be removed from the documentation.
If it's still in use, it should appear in the RULES.md table and in NOTICES.md

**Comment by lionel-nj** [comment]
Good catch! This notice has been removed. Documentation has been updated [here](https://github.com/MobilityData/gtfs-validator/pull/1069).
