### ISSUE TITLE
Downgrade InvalidPhoneNumberNotice

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#1060]
## **Feature request**

This notice (currently an `ERROR`) causes false positive. The first step for `v3.0.0` release is to downgrade this notice (to avoid breaking changes) and then improve the validator so that it does not generate false positives.

**Additional context**
#1058

**Comment by barbeau** [comment]
@lionel-nj I think https://github.com/MobilityData/gtfs-validator/issues/1058 should be the issue linked above in "Additonal context"?

**Comment by isabelle-dr** [comment]
Closing, resolved in #1062
