### ISSUE TITLE
USAGE.md Export notice schema

### ISSUE THREAD

**Issue by dancesWithCycles** [MobilityData/gtfs-validator#1065]
Hi folks,
thank you so much for providing and maintaining this repository. I am studying it with high interest in calendar related business rules.

## **Bug report** 

**Describe the bug**

I was running the following instruction using the latest snapshot from today Nov 16th 2021.

```
java -jar gtfs-validator-master-sha-649c1643-SNAPSHOT/gtfs-validator-v-master-sha-649c1643-SNAPSHOT_cli.jar --export_notice_schema
```

**How we reproduce the bug**
1. Download snapshot from Nov 16th 2021
2. Call gtfs-validator this way ```java -jar gtfs-validator-master-sha-649c1643-SNAPSHOT/gtfs-validator-v-master-sha-649c1643-SNAPSHOT_cli.jar --export_notice_schema```

**Expected behavior**
I expected the tool to generate and export all validation notices as a json file as described on the USAGE.md page.

**Observed behaviour**
I received the following exception.

```
java -jar gtfs-validator-master-sha-649c1643-SNAPSHOT/gtfs-validator-v-master-sha-649c1643-SNAPSHOT_cli.jar --export_notice_schema
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: --export_notice_schema
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at org.mobilitydata.gtfsvalidator.cli.Main.parseArguments(Main.java:193)
	at org.mobilitydata.gtfsvalidator.cli.Main.main(Main.java:55)
```

**Environment versions**
- validator version: snapshot from Nov 16th. 2021
- Java version:  ```openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)```
- OS versions: ```Linux tpx200 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux```

I appreciate any hint that steers me in the right direction.

Cheers!

**Comment by lionel-nj** [comment]
Hi @dancesWithCycles thanks for opening this issue. 

Here is the syntax you should use : 

```java -jar gtfs-validator-master-sha-649c1643-SNAPSHOT/gtfs-validator-v-master-sha-649c1643-SNAPSHOT_cli.jar --export_notices_schema --output <output>```

where `<output>` should be replaced by the path to the directory where you would like the json file to be exported.

There is a typo in the documentation, we will fix it. 

Feel free to close this if this answers your question.

Lionel.

**Comment by dancesWithCycles** [comment]
Hi @lionel-nj ,
Thank you so much for the rapid and helpful response. Using the missing ```s``` and ```--output_base``` instead of ```--output``` works perfectly fine. Here is my working instruction call.

```
java -jar gtfs-validator-master-sha-649c1643-SNAPSHOT/gtfs-validator-v-master-sha-649c1643-SNAPSHOT_cli.jar --export_notices_schema --output_base output
```

Cheers!
