### ISSUE TITLE
Add a rule for missing stop name 

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1078]
**What problem in GTFS datasets does this new rule address? Please describe.**
The GTFS specification [mentions in `stops.stop_name`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt):

> Conditionally Required:
> - Required for locations which are stops (location_type=0), stations (location_type=1) or entrances/exits (location_type=2).
> - Optional for locations which are generic nodes (location_type=3) or boarding areas (location_type=4).

**Describe the new validation rule**
We should add a rule that would trigger a `MissingStopNameNotice` if:
- (`location_type` has values 0, 1 or 2) AND (`stop_name` is missing) for a line in `stops.txt`

**Error vs warning**
ERROR

**Comment by isabelle-dr** [comment]
@asvechnikov2 do you have this rule implemented at Google?

**Comment by asvechnikov2** [comment]
Hi @isabelle-dr

Yes, we require for stations and stops to have stop_name. A thing to note that we don't require this for entrances, do you think entrances must have a name?

**Comment by KClough** [comment]
> Hello @asvechnikov2,
> 
> Yes, the name is also required for entrances & exits. Would you like to Pull Request the rule you have on this repo, and then we make a second PR with the additional code and use the acceptance test architecture to get the stats? We would know if there are datasets that are passing your rule and that wouldn't pass the new rule. I would be surprised if there are any since it's pretty clear in the specification.

@asvechnikov2 @bdferris-v2 

Wanted to bump up this question. I'm able to assist with this issue as needed.

**Comment by isabelle-dr** [comment]
Hello @KClough, 
I think we can move forward with this rule. 😊
Are you still planning to write it?

**Comment by KClough** [comment]
@isabelle-dr yes.
