### ISSUE TITLE
open an issue automatically when a PR is merged on google/transit

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1080]
In order to keep the validator up to date with the changes, we need to review PR's merged on the official specification to see if we need to modify a rule in the Canonical GTFS Schedule Validator. 
Having an automatic issue would help to make sure we don't miss anything.

Additional context in:
- https://github.com/MobilityData/gtfs-validator/issues/311

**Comment by davidgamez** [comment]
There is an interesting thread here: https://github.com/orgs/community/discussions/26323
One of the replies mentioned a GitHub app that we might be able to use, https://github.com/marketplace/webhook-actions

**Comment by isabelle-dr** [comment]
The logic would be: if REFERENCE.md is modified, we open an issue.
https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md

**Comment by emmambd** [comment]
Implemented! Waiting for next merge on reference.md to google/transit to test. It's on me to check this and mark this "done". Will likely take a few months for the next spec vote. cc @jcpitre @fredericsimard

**Comment by isabelle-dr** [comment]
Guessing it didn't work?

**Comment by fredericsimard** [comment]
> Guessing it didn't work?

@isabelle-dr No, it did. Here's an example: https://github.com/MobilityData/gtfs-validator/issues/1601

**Comment by emmambd** [comment]
@fredericsimard @isabelle-dr Finally confirmed success from #1601, so closing now.

**Comment by emmambd** [comment]
@fredericsimard Reopening for one more request with this: can we automatically add the "needs triage" label to any issue that comes from this workflow?
