### ISSUE TITLE
[REQUEST] Handling conditionally required fields

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#109]
**Is your feature request related to a problem? Please describe.**
Some fields such as routes.agency_id are conditionally required. Whether these fields should be present or not depend on other file's content. 
Here, routes.agency_id depends on the number of agencies present in agency.txt file.

**Describe the solution you'd like**
In the calling code agencies should therefore be added to a GtfsDataRepository before adding route entities.

1. In a first place we should determine all the fields that need pre-processing

**Describe alternatives you've considered**

**Additional context**
https://github.com/MobilityData/gtfs-validator/pull/57#discussion_r404210651

**Comment by barbeau** [comment]
Closing as outdated with annotation-based architecture
