### ISSUE TITLE
Improve user facing messages: list of invoked validators 

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#1097]
## **Feature request** 
This description was edited by @isabelle-dr on 2022-05-05

**Is your feature request related to a problem? Please describe.**
The user facing messages that print in the terminal during validation are currently confusing because they often imply that something might have gone wrong when it's not the case.
If any of the existing validator (in the sense of a [validator.java](https://github.com/MobilityData/gtfs-validator/blob/master/main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopZoneIdValidator.java) file) didn't run, the user gets the following message:
<img width="339" alt="Screen Shot 2022-04-19 at 2 57 53 PM" src="https://user-images.githubusercontent.com/63653518/167010318-6836da80-4d8a-4904-8e23-ae4d731f991a.png">

There are two problems:
1. the `MISSING_FILE` statement should only appear for required files. Right now it implies that the user need to add all these files but they are optional. 
2. the `!!! PARSING FAILED !!!` statement should not appear when everything runs properly. If an optional file/field isn't present in the dataset, the validator that is based on it doesn't run (which is normal), so we should't give such warning to the user.

What is important to flag is if something happened that would compromise the validator integrity (_I can't trust this report_). That would happen when a validator should have run but didn't (this seems to have happened in [issue 1089](https://github.com/MobilityData/gtfs-validator/issues/1089#issue-1116860117), and we opened issue #1096 to troubleshoot why. This could be because it wasn't invoked at all, or that it didn't run because it encountered an issue (e. g. a validator that is dependant on the time fields being properly formatted, or a validator that couldn't find the field name it was looking for)

**Proposed solution**
This would need further thinking and discussion but the solution could look like:
1. Remove the `MISSING_FILE` statement for optional files
2. Create a list of validators that should be invoked based on the dataset files & fields, and log a list of validators that have run. 
If there is a discrepancy between the two lists, print a message that mentions that the validation report may be compromised, and print the name of the validators that should have run. 

We might need to implement https://github.com/MobilityData/gtfs-validator/issues/1098 before we can do this.

**Additional context**
https://github.com/MobilityData/gtfs-validator/issues/1098

**Comment by isabelle-dr** [comment]
Related to #1097 and #1096
