### ISSUE TITLE
Issue triage is failing

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-validator#1106]
**Describe the bug**
The repo is currently set up to automatically generate comments for new issues:
https://github.com/MobilityData/gtfs-validator/blob/master/.github/workflows/triage.yml

However, when I opened https://github.com/MobilityData/gtfs-validator/issues/1105 this apparently failed - see:
https://github.com/MobilityData/gtfs-validator/runs/5185798257?check_suite_focus=true

...with:

```
Run alex-page/github-project-automation-plus@v0.8.1
Error: lionel-nj does not have the correct permissions to execute `AddProjectCard`
```

So it looks like the action is trying to use @lionel-nj's account but it no longer has proper permissions. We should switch to using a different account.

**How we reproduce the bug**
Steps to reproduce the behaviour:
1. Create an issue

**Expected behaviour**
Triage workflow should run without error and generate a new comment on the issue

**Observed behaviour**
Triage workflow fails and no comment is generated

**Comment by isabelle-dr** [comment]
I updated the token with a token configured under my account, this fixes the issue (see [here](https://github.com/MobilityData/gtfs-validator/issues/1174))
