### ISSUE TITLE
Update mobilitydata.org to old.mobilitydata.org for the acceptance tests

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#1107]
## **Feature request**
Update mobilitydata.org to old.mobilitydata.org for the acceptance tests

**Is your feature request related to a problem? Please describe.**
The Mobility Database have been redirected to old.mobilitydatabase.org. The acceptance tests are still using the database, so the url should be updated.

**Proposed solution**
Update the constants string in the scripts.

**Comment by isabelle-dr** [comment]
Closing, solved in #1108
