### ISSUE TITLE
Update validator after the addition of primary and foreign keys in the specification

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1113]
> UPDATE: This issue has been updated after [PR # 326](https://github.com/google/transit/pull/326) has been merged in the spec in June 2022.

In Q4 2021, the definition of primary and foreign keys was added to GTFS in [PR #278](https://github.com/google/transit/pull/278).
This validator already defines primary and foreign keys, and this informs the following notices:
- [ForeignKeyViolationNotice](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#ForeignKeyViolationNotice)
- [DuplicateKeyNotice](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#DuplicateKeyNotice)
- [TranslationFOreignKeyViolationNotice](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#TranslationForeignKeyViolationNotice)

A comparison[ has been made](https://github.com/MobilityData/gtfs-validator/issues/1079#issuecomment-1068180857) between the existing primary & foreign key implementations in the specification and the validator. From this comparison, we should update the validator with:
1. in `calendar_dates.txt`, add `service_id` and `date` as the primary key
2. in `frequencies.txt`, add `trip_id` and `start_time` as the primary key
3. in `transfers.txt`, add `from_stop_id`, `to_stop_id`, `from_trip_id`, `to_trip_id`, `from_route_id`, `to_route_id`as the primary key
4. in `translations.txt`, ~~add that all records are a primary key, or add an additional rule similar to [DuplicateFareRuleZoneIdFieldsNotice](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#duplicatefarerulezoneidfieldsnotice) to flag a duplicate row.~~ add `table_name`, `field_name`, `language`, `record_id`, `record_sub_id`, `field_value` as the primary key.

### Definition of done
- The DuplicateKeyNotice is triggered for:
  - two rows in `calendar_dates.txt` that have the same values for `service_id` and `date`
  - two rows in `frequencies.txt` that have the same values for `trip_id` and `start_time`
  - two rows in `transfers.txt` that have the same values for `from_stop_id`, `to_stop_id`, `from_trip_id`, `to_trip_id`, `from_route_id`, `to_route_id`
  - ~~two duplicate rows in `translations.txt`~~ two rows in `translations.txt` that have the same values for: `table_name`, `field_name`, `language`, `record_id`, `record_sub_id`, `field_value`.

**Comment by f8full** [comment]
This is not a good first issue because no sample dataset is provided. There is no way to easily test the validator modifications.

**Comment by isabelle-dr** [comment]
@f8full Fair point. 
Additionally, if 3 and 4 need a new rule this is definitely not a good first issue. Thanks!

**Comment by isabelle-dr** [comment]
Do you think it would be useful to create a sample dataset with all the issues provided in the **Definition of done**?

**Comment by f8full** [comment]
I do.

**Comment by isabelle-dr** [comment]
This issue is dependent on the change planned by @bdferris in https://github.com/MobilityData/gtfs-validator/issues/1187. 
I would recommend doing #1187 first, then solving this issue.

**Comment by KClough** [comment]
@isabelle-dr I went ahead and created my own sample data set to test this. Is it helpful if I attach the sample data to the issue or PR?

**Comment by isabelle-dr** [comment]
@KClough thanks :) 
Yes, it would be helpful to have the sample data attached to this issue! Thanks for creating it.

**Comment by KClough** [comment]
@isabelle-dr Here are the two datasets I used.

**Note**, I've only tested this feature on transfers.

[vinetransit-ca-us-bad-multi-pk.zip](https://github.com/MobilityData/gtfs-validator/files/9234886/vinetransit-ca-us-bad-multi-pk.zip)
[vinetransit-ca-us-good-multi-pk.zip](https://github.com/MobilityData/gtfs-validator/files/9234887/vinetransit-ca-us-good-multi-pk.zip)
