### ISSUE TITLE
Update Validator after addition of trip-to-trip and route-to-route transfers

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1114]
In Q4 2021, trip-to-trip and route-to-route transfers were added to the specification ([PR#278](https://github.com/google/transit/pull/278)). 

The validator needs to be updated with 4 additional optional fields in transfers.txt:
- `from_trip_id` - Foreign key referencing `trips.trip_id`
- `to_trip_id` -  Foreign key referencing `trips.trip_id`
- `from_route_id` -  Foreign key referencing `routes.route_id`
- `to_route_id` - Foreign key referencing `routes.route_id`

No additional rules need to be added.

### Definition of done:
- the [ForeignKeyViolationNotice](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#ForeignKeyViolationNotice) is triggered if these fields are referencing a value that doesn't exist.
- the [UnknownColumnNotice](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#UnknownColumnNotice) is not triggered by these four fields.

**Comment by KClough** [comment]
@isabelle-dr please let me know if I should be updating the status of things on this board. I didn't see a way for me to set that status from `Current Sprint` to `Under Review`.

**Comment by maximearmstrong** [comment]
> @isabelle-dr please let me know if I should be updating the status of things on this board. I didn't see a way for me to set that status from `Current Sprint` to `Under Review`.

I just updated it :) Thank you @KClough !
