### ISSUE TITLE
Update the "Help" menu with current command line parameters

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1116]
**Describe the bug**
Provide a clear and concise description of what the bug is. 

**How we reproduce the bug**
Steps to reproduce the behaviour:
1. Download the lastest jar file
2. Open the terminal
3. Type java -jar gtfs-validator-v-trillium_cli.jar --help

**Expected behaviour**
See a list of parameters that match the list described in [USAGE.md](https://github.com/MobilityData/gtfs-validator/blob/master/docs/USAGE.md).
The current list of parameters is:
- -i or --input
- -c or --country_code
- -h or --help
- -o or --output
- -s or --storage_directory
- -t or --threads
- -u or --url
- -v or --validation_report_name
- -e or --system_errors_report_name
- -n or --export_notices_schema

**Observed behaviour**
The list of parameters is outdated

**Screenshots:** 
![Screen Shot 2022-03-16 at 1 58 37 PM](https://user-images.githubusercontent.com/63653518/158656518-d2f0cb73-f6e0-4dee-9690-6b6610a9c69b.png)

**Comment by ed-g** [comment]
I just realized something. If you're downloading the jar file https://github.com/Trillium-Solutions/gtfs-validator/releases/tag/v3.0.1-alpha, that's quite a bit behind the version of the code in github and there are a number of bugs. I had created it to experiment with github releases. I can upload a new version which has all the features and bug fixes if that makes your life easier. Or it can be compiled with gradle from the `html_output` branch, whichever you prefer.

**Comment by isabelle-dr** [comment]
@ed-g I used a JAR from [our GH action Test Package Document](https://github.com/MobilityData/gtfs-validator/actions/workflows/test_pack_doc.yml), and I renamed it Trillium because the latest came from your contribution :). 
I tried it with another one ([this one](https://github.com/MobilityData/gtfs-validator/actions/runs/1860897014)) and I have the same result. We just forgot to update the help menu when changing the command line parameters. 🙈
