### ISSUE TITLE
[BUG] Output fails when output file is open

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-validator#112]
**Describe the bug**
If after running the validator you open the output `results.json` file and then run validator again, the output fails with an error message:

>[ERROR] 2020-04-15 17:06:38.743 [main] Main - An exception occurred: C:\git-projects\gtfs-validator\application\cli-app\build\libs\output\results.json

**To Reproduce**
Run from command-line or IntelliJ

1. Run the validator (`java -jar gtfs-validator-v1.1.0-SNAPSHOT.jar -u https://github.com/CUTR-at-USF/bullrunner-gtfs-realtime-generator/raw/master/bullrunner-gtfs.zip -z input.zip -i input -o output`)
1. Open the `output/results.json` file in an editor like Notepad++
1. Run the validator again (`java -jar gtfs-validator-v1.1.0-SNAPSHOT.jar -u https://github.com/CUTR-at-USF/bullrunner-gtfs-realtime-generator/raw/master/bullrunner-gtfs.zip -z input.zip -i input -o output`)

**Expected behavior**
Validation should succeed and overwrite the output file, or the original output file should not be overwritten

**Witnessed behavior**

The validator deletes the old output file and directory, but fails to output a new output file.

Here's the console output:

>Notice{filename='calendar_dates.txt', noticeId='E015', title='Missing required value', description='Missing value for field:service_id marked as required in entity with id:null'},
Notice{filename='calendar_dates.txt', noticeId='E015', title='Missing required value', description='Missing value for field:date marked as required in entity with id:null'},
Notice{filename='calendar_dates.txt', noticeId='E015', title='Missing required value', description='Missing value for field:exception_type marked as required in entity with id:null'}]
[ERROR] 2020-04-15 17:06:38.743 [main] Main - An exception occurred: C:\git-projects\gtfs-validator\application\cli-app\build\libs\output\results.json
[INFO ] 2020-04-15 17:06:38.750 [main] Main - Took 2038ms
PS C:\git-projects\gtfs-validator\application\cli-app\build\libs>

**Environment used**
- OS: Windows 10
- Java version: JDK 14

**Comment by barbeau** [comment]
Looking at `CleanOrCreatePath.execute()`, I don't think that exceptions related to not being able to delete files or create a directory should be stored in the validation results repo - they should be output to the logger/command-line.

**Comment by barbeau** [comment]
It looks like the error message is only being partially output too here - I just opened https://github.com/MobilityData/gtfs-validator/pull/113 to fix this.

**Comment by irees** [comment]
Is this a Windows issue? IIRC Windows does not allow open files to be deleted without a specific open flag.

**Comment by barbeau** [comment]
@irees Maybe - when testing a fix I ran across these:
* https://bugs.openjdk.java.net/browse/JDK-8029608
* https://bugs.openjdk.java.net/browse/JDK-8024496

...which indicate that immediately after delete sometimes Windows may block `Files.createDirectory()` with a `java.nio.file.AccessDeniedException`

But I'm not sure why this is only happening when I have the file open in an editor and why it doesn't always happen, especially because the file gets deleted anyway even if it's open in editor.

I'm curious if someone can reproduce this on Linux or Mac.

You don't need a release build for this - you can test running from IntelliJ.

**Comment by fabrice-v** [comment]
On my mac machine I tested this situation by having the file opened in IntelliJ, the content is updated without any issue. with TextEdit the file had to be reopened. In both cases the validator executed without error.

**Comment by barbeau** [comment]
@fabrice-v You might want to try an external editor - having IntelliJ running the application and having the file open may be a special case.

**Comment by fabrice-v** [comment]
Yep, as mentionned I also tried with TextEdit and even though the file content didn't update, the validator execution went normaly.
