### ISSUE TITLE
Implement HTML output for validation report (MVP)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#1126]
## **Feature request**
Currently, the validation report is only available as a JSON file. Adding an HTML output would improve the user experience.

**Is your feature request related to a problem? Please describe.**
Browsing through the JSON validation report can be complicated and tedious, especially for user with low to mid technical knowledge. This is an obstacle to the use of the product.

**Proposed solution**
Inspired by Trillium work in PR #1119, we suggest implement a lean HTML + CSS + JavaScript output. The file will be self-contained so it can live on its own. We suggest using jQuery instead of a front-end framework like React or Snabbdom as we are no longer going for a local/hosted web UI app.

Steps:
- [X] Output prototype
- [X] Add the jQuery dependency
- [X] Add the components to generate the HTML output
- [X] Modify the validator main to add the generation of the HTML output during the export of the validation report.
- [X] Add tests.

**Describe alternatives you've considered**
We considered using React or Snabbdom at first. The initial idea was to create a local web UI, then to host it. This is not a feature we are considering doing anymore.

**Additional context**
Trillium did great work in PR #1119 to implement a front-end framework and a UI.
Issue #1112 explains the previous feature we were considering, the local web UI.
Epic #1124 explains the current feature we are considering, a packaged executable and an HTML output.

**Comment by bdferris-v2** [comment]
Maxime, I appreciate the work you've done here, but I wanted to make a counter proposal.  I know the team shied away from some of the technical complexity of from the original Trillium PR, with good reason, but I fear this PR has gone too far in the other direction.

Namely, I think you could leverage a basic templating engine here without too much more complexity that would come with a lot of benefits.  There are a number of Java templating engines out there, but I'd suggest https://www.thymeleaf.org/ as a good candidate.  It comes with a number of nice benefits:

*   Allows you to write templates that are valid HTML, which makes it a lot easier to understand, develop, and maintain the reports.
*   Provides a clear technical path for features like i18n/l10n ([reference](https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#using-thtext-and-externalizing-text))
*   Can generate static HTML without needing a server environment.

I put together a quick commit that demonstrates a flavor of what this would look like for report generation:
https://github.com/bdferris-v2/gtfs-validator/commit/f64b213c310950d70ed86f12f2e2798ff13e4cc1

Again, apologies for stepping in with an alternate proposal after you've already got an end-to-end solution working here.  If there was some earlier technical discussion I missed where you all laid out your options here, I will try to figure out how to be more proactively involved going forward.

**Comment by maximearmstrong** [comment]
@bdferris-v2 No worries at all! I was looking for a HTML library before implementing the code, but all I found was HTML parsers such as [jsoup](https://jsoup.org/), which was not exactly what I was looking for. I agree that Thymeleaf looks like a way better solution. I will implement it, thank you :)
