### ISSUE TITLE
End to End workflow failure of PR

### ISSUE THREAD

**Issue by bdferris-v2** [MobilityData/gtfs-validator#1129]
## **Bug report** 

On PR #1125, I had a couple of acceptance tests fail.  While some of those might be due to issue #1094, I think there might be other bugs as well.  For example, consider the "End to end" test:

https://github.com/MobilityData/gtfs-validator/actions/runs/2234494855

I see the following error in the `run-on-data` step:

```
Run java -jar main/build/libs/*.jar --url https://openmobilitydata.org/p/transport-for-nsw/237/latest/download --output_base output --country_code au --storage_directory gs.zip
Error: Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter 'main/build/libs/main-v-pr-1125-sha-0b91b063-SNAPSHOT_cli.jar' but no main parameter was defined
```

I think this is an issue with the following line in [end_to_end.yml](https://github.com/MobilityData/gtfs-validator/blob/master/.github/workflows/end_to_end.yml#L74):

```
java -jar application/cli-app/build/libs/*.jar
```

I think the issue is that the :main sub-project can actually generate two jars.  One regular jar (`main-$version.jar`) and one shadowJar (`gtfs-validator-$version_cli.jar`) containing all the dependencies for the CLI.  The shadow jar is what you want here and is indeed what's built by the workflow, but I'm wondering if something is causing the build to be left in a weird state (possibly due to a previous workflow failure?) where the other jar is still around, such that the `*.jar` wild-card in the command actually expands to two jars, causing the command to fail?  That's my interpretation of the error message, at least.

Could probably be fixed by adding a `gtfs-validator-` prefix to the `*.jar` wildcard.  Or, alternatively, doing a full clean before running the workflow step?

I'll admit I'm not familiar enough with the workflow setup to know the right course of action here.

**Comment by barbeau** [comment]
>Could probably be fixed by adding a gtfs-validator- prefix to the *.jar wildcard.

As discussed in today's meeting I think this would be a good first fix and we can see what happens from here. 👍

**Comment by bdferris-v2** [comment]
My end-to-end tests are now successfully running for PR #1125 with the new workflow changes.  While there may be other issues affecting workflows and acceptance test, I believe this specific instance appears to be fixed.
