### ISSUE TITLE
Refactor handling of project version numbers and tags

### ISSUE THREAD

**Issue by bdferris-v2** [MobilityData/gtfs-validator#1139]
Per discussion in https://github.com/MobilityData/gtfs-validator/pull/1125#discussion_r869435195, we'd like to consider a few potential changes to how `gtfs-validator` handles version numbers.  Two potential issues:

*  The use of a leading `v` in the version tag (ala v3.1.0) causes problems for some tooling (Java Modules, Mac OS app packaging) that expects numeric major.minor.patch version numbers.
* Our use of a `versionTag` environment variable for passing in version information is maybe not idiomatic Gradle?  My limited research has suggested that overriding `project.version` via a command-line flag ala `-Pversion=1.2.3` is a more consistent way of setting the project version for the entire build.

**Comment by maximearmstrong** [comment]
As discussed [here](https://github.com/MobilityData/gtfs-validator/pull/1127#issuecomment-1125486282) in #1127, the work done for this issue may affect the version of the validator we display in the HTML output.

**Comment by isabelle-dr** [comment]
> The use of a leading v in the version tag

Do we want to do this one right now? (i. e. rename previous versions & only use major.minor.patch from now on)

**Comment by bdferris-v2** [comment]
@isabelle-dr the axion-release plugin in PR #1147 seems to be able to handle the leading 'v' on the version tag, so I don't think any changes are needed there.
