### ISSUE TITLE
Include basic feed information in validation report 

### ISSUE THREAD

**Issue by FreddieMarkgraf** [MobilityData/gtfs-validator#1159]
## **Feature request**
It would be helpful if validator results included general feed information such as agency name, number of routes and trips, and service dates. When dealing with multiple files it can be helpful to have a way to identify the feed being validated in the validator results. Having the service dates visible is especially helpful when comparing validation results of older files against new ones. 

**Is your feature request related to a problem? Please describe.**
I was unable to see feed identifying information in the validator results.

**Proposed solution**
I would like to have general feed information available in the validator results, such as agency name, service date range, and number of routes/trips.

**Comment by davidgamez** [comment]
The feed information was added as part of #1363
