### ISSUE TITLE
remove InMemoryGtfsSpecRepository guava dependency

### ISSUE THREAD

**Issue by ghost** [MobilityData/gtfs-validator#116]
**Describe the solution you'd like**
Presently, InMemoryGtfsSpecRepository takes a resource name as a construction parameter and uses guava to access resources. The goal of this issue would be to mimic what has been done in InMemoryExecParamRepository where it is the CONTENT of the resource file that is passed as a String to the constructor. This will allow to remove the dependency on guava as well as avoid testing some part of Guava when testing InMemoryGtfsSpecRepository.

**Comment by barbeau** [comment]
Closing, addressed by v2 architecture
