### ISSUE TITLE
Add an icon for the GUI application

### ISSUE THREAD

**Issue by bdferris-v2** [MobilityData/gtfs-validator#1162]
The new packaged app could benefit from an official application icon.  By default, it gets a generic Java icon when packaged, which is less than ideal.

**Comment by bdferris-v2** [comment]
Per discussion on #tech-contributors, I attempted to integrate the new icon (I worked with `Validator_Icon_Reversed.svg`).  I think there are some issues with image transparency that we might need to address.  Namely, fill for both the checkmark and the stroke of the grid in the background are both transparent. This looks fine when the app icon is on a white background:

<img width="327" alt="Screen Shot 2022-06-02 at 9 50 35 PM" src="https://user-images.githubusercontent.com/26211219/171793573-e1852f2a-04eb-4372-a16d-dfa773c64a3f.png">
<img width="344" alt="Screen Shot 2022-06-02 at 10 31 05 PM" src="https://user-images.githubusercontent.com/26211219/171793630-7b8c7884-c754-4a15-958c-0ac222c4da91.png">

But does not look great when the app is on a non-white background (e.g. desktop shortcut).

<img width="121" alt="Screen Shot 2022-06-02 at 9 52 24 PM" src="https://user-images.githubusercontent.com/26211219/171793811-7d35d1ab-46a3-4b6f-a55e-a7cbc5194eb3.png">
<img width="69" alt="Screen Shot 2022-06-02 at 10 33 56 PM" src="https://user-images.githubusercontent.com/26211219/171793852-684a8ab3-b94f-4727-a6b9-cdcf781194ca.png">

(My Windows background is particularly dark).

While we could use the icon as-is, it's not the best experience with some backgrounds.

@isabelle-dr thoughts?  Anything you can help with?

**Comment by isabelle-dr** [comment]
@bdferris-v2 agreed, the background should be white. 
I'm sending you the update via e-mail

**Comment by isabelle-dr** [comment]
Here is the version with a white background to function on all different backgrounds. 
![Screen Shot 2022-06-03 at 10 35 40 AM](https://user-images.githubusercontent.com/63653518/171875929-91c52fd2-c7da-4865-b179-82549b31aa73.png)
