### ISSUE TITLE
Add the GUI app package to the test_pack_doc.yml workflow

### ISSUE THREAD

**Issue by bdferris-v2** [MobilityData/gtfs-validator#1163]
So that the GUI application package can be automatically built as part of the release process (along with other CI runs), we'd like to add a phase to the existing `test_pack_doc.yml` workflow to package the application.  Ideally, we'd run it on Windows and Mac OS (and maybe Linux?), though I don't know if GitHub supports all those flavors.

**Comment by barbeau** [comment]
Windows may be a little tricky as it requires (summarized from the [build docs](https://github.com/MobilityData/gtfs-validator/blob/master/docs/BUILD.md#packaging-as-installable-application)):
* JDK >= 15
* https://wixtoolset.org/ on the path
* .NET Framework 3.5.1

I imagine WiX can be fetched dynamically within a GitHub Action.

.NET Framework might be bundled with the Windows GitHub Action runner (?). From a quick look at the Windows 2022 runner docs, I don't see .NET Framework 3.5.1 specifically:
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md

...but the Windows 2019 runner lists `Microsoft.Net.Component.3.5.DeveloperTools`:
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

So if `windows-latest` doesn't work (which is currently the same as `windows-2022`, we might want to try `windows-2019`.

**Comment by bdferris-v2** [comment]
Are there any concerns about how often we trigger full packaging runs?  I'm not totally clear on what tier MobilityData is in, but I assume they are paying for GitHub actions, both in minutes run + storage.  Packaging will certainly use minutes + storage, so I wondered if this is something that should only be run on release (similar to Docker?) versus every PR?

**Comment by barbeau** [comment]
@isabelle-dr could answer the GitHub tier question definitively, but I'm not aware of any concerns (i.e., maybe on free tier?).

I think mirroring Docker is fine in terms of making the artifacts available - if someone wants bleeding edge they will probably be running command line. However, knowing if something is breaks in the packaging execution would be valuable prior to release, and I believe the only way to do that as of now is to run on every PR?

**Comment by bdferris-v2** [comment]
Amazingly, (and I'm probably jinxing myself here), but this mostly just seemed to work without much drama.  Per PR #1166 and https://github.com/MobilityData/gtfs-validator/actions/runs/2382685953, it's correctly producing packages for Windows, Mac, and Ubuntu/Debian.  I didn't have to do any tweaking with Wix or .NET Framework.

**Comment by isabelle-dr** [comment]
Hello! Sorry for the late reply, I wanted to make sure I understand the impact of running on every PR VS only release before answering.

I see value in packaging the app on every commit just like we do with the JAR files in `test_pack_doc.yml` because we can test if everything works fine before merging a PR or doing a release. (but maybe there is another way to test and I'm not aware of it?).
After discussion with @maximearmstrong we don't see any major inconveniences.

**Comment by maximearmstrong** [comment]
I agree. There is no concern on our side for the minutes run + storage.
