### ISSUE TITLE
Update validator instructions for the 3.1.0 release

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1172]
The instructions to run the validator are changing in the 3.1.0 release and the documentation needs to be updated to reflect the changes:
- README.md needs to be updated
- a new DOWNLOAD_SNAPSHOT_APP.md (similarly than [DOWNLOAD_SNAPSHOT_JAR.md](https://github.com/MobilityData/gtfs-validator/blob/master/docs/DOWNLOAD_SNAPSHOT_JAR.md)) needs to be created

Additional context in https://github.com/MobilityData/gtfs-validator/pull/1166#pullrequestreview-986400326

**Comment by bdferris-v2** [comment]
@isabelle-dr in `README.md`, would you want the section concerning the new app added before the existing `Run the app via command line`?  After?  To replace?  I'm curious what you think is most appropriate.

**Comment by isabelle-dr** [comment]
I think probably before the existing `Run the app via command line?`.
