### ISSUE TITLE
Add a rule that checks the presence of stop_lat & stop_lon in stops.txt

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1180]
**What problem in GTFS datasets does this new rule address? Please describe.**
The spec in `stops.stop_lat` and `stops.stop_lon` mentions ([source](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt)):
> Conditionally Required:
> - Required for locations which are stops (location_type=0), stations (location_type=1) or entrances/exits (location_type=2).
> - Optional for locations which are generic nodes (location_type=3) or boarding areas (location_type=4).

This check is missing from the validator. 

**Describe the new validation rule**
For each line in `stops.txt`, if either `stop_lat` or `stop_lon` (or both) are missing AND location_type = 0, 1 or 2, trigger a `missing_stop_coordinates` notice.

**Error vs warning**
Error

**Comment by isabelle-dr** [comment]
@aababilov, @bdferris, do you have an implementation of this notice?

**Comment by bdferris-v2** [comment]
I wasn't quite sure what you were asking here.  Are you asking if we want to contribute an implementation for this validation check?  Or if we had an existing implementation?

**Comment by isabelle-dr** [comment]
If you had an existing implementation already :)

**Comment by KClough** [comment]
@bdferris-v2 wanted to double check to see if you had an implementation already. If not, I'll gladly take this one.

**Comment by isabelle-dr** [comment]
@KClough not sure where you are with this but we have a Pull Request solving it (#1315)

**Comment by isabelle-dr** [comment]
This has been solved in #1321
