### ISSUE TITLE
feat: Multi-column Primary Key Support

### ISSUE THREAD

**Issue by bdferris-v2** [MobilityData/gtfs-validator#1187]
I've put together a proposal to better support multi-column primary keys in the validator, pulled out into a doc for easier discussion:

https://bit.ly/gtfs-validator-multi-column-primary-keys

The quick version is new extensions like Fares 2.0 have files with many-columned primary keys (4-5 columns) that are not currently possible to model using existing functionality in the validator.   I'm proposing some consolidated syntax + implementation work to support the validator's existing + new use cases.

**Comment by maximearmstrong** [comment]
Thank you for this proposal @bdferris-v2! I agree with your plan.

**Comment by KClough** [comment]
@bdferris-v2 are you still working on the implementation of this issue?

**Comment by bdferris-v2** [comment]
Yeah.  I've been in a holding pattern while waiting for code reviews from a colleague in Sydney.  However, they have started reviewing, per #1189 and #1190, so hopefully we'll have something to show for it soon.

**Comment by bdferris-v2** [comment]
With #1190 submitted, I believe we can close this issue.
