### ISSUE TITLE
Developer experience: add bin folder to .gitignore

### ISSUE THREAD

**Issue by KClough** [MobilityData/gtfs-validator#1195]
## **Feature request**
Note: We are happy to provide support to the entire community, however our [members and sponsors](https://mobilitydata.org/members/) have their issues prioritized as a benefit of their membership. MobilityData staff is aware of all issues opened, therefore there is no need for you to tag us directly. 

**Is your feature request related to a problem? Please describe.**
Provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

When building the project locally on OSX, I noticed a `main/bin` is created from the gradle build process. I believe this folder should be ignored.

**Proposed solution**

When building the project from scratch, generated code files should be ignored by source control.

**Describe alternatives you've considered**

Add `*/bin` to .gitignore

**Additional context**
Add any other context or screenshots about the feature request that can help us better understand your needs.

**Comment by bdferris-v2** [comment]
Out of curiosity, what Gradle task / command are you running that results in a `bin` folder?  I also build on Mac OS and I've never noticed such a thing.

**Comment by KClough** [comment]
```
./gradlew shadowJar
```

Maybe it is related to my JDK? I'm using `openjdk 11.0.14.1 2022-02-08`.
