### ISSUE TITLE
Packaged GTFS Validator app (v3.1.0) for macOS is damaged and can't be opened

### ISSUE THREAD

**Issue by a20r** [MobilityData/gtfs-validator#1199]
## **Bug report** 

**Describe the bug**
I am unable to start the GTFS Validator after downloading and installing the [v3.1.0 release](https://github.com/MobilityData/gtfs-validator/releases/tag/v3.1.0) for MacOS.  I have tested this on the following computers:

**How we reproduce the bug**
Steps to reproduce the behaviour:
1. Download and unzip the [v3.1.0 release for macOS](https://github.com/MobilityData/gtfs-validator/releases/download/v3.1.0/Installer-macos-v3.1.0.zip)
2. Run the `GTFS Validator-3.1.0.dmg` installer
3. Move the *GTFS Validator* application to the `Applications` directory
4. Run the *GTFS Validator* application

**Expected behaviour**
I expect the application to start successfully and for the widget to appear on the screen

**Observed behaviour**
I am shown an error message saying  *"GTFS Validator" is damaged and can't be opened. You should move it to the Trash.*

**Screenshots:** 
![](https://user-images.githubusercontent.com/2995274/176306937-ce5f9343-25cb-407b-83a2-644e2abcc39a.png)

**Environment versions**
- Validator version: [v3.1.0](https://github.com/MobilityData/gtfs-validator/releases/tag/v3.1.0) 
- Java version: 
```
$ java -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
```
- OS versions:
    - MacBook Pro (Intel, 2020) w/ macOS v12.1
    - MacBook Pro (Intel, 2019) w/ macOS v12.4
    - Mac mini (M1, 2020) w/ macOS v12.4

**Comment by isabelle-dr** [comment]
👋 Hello @a20r, thank you for opening your first issue in this project! 
If you haven't already, you can meet the community in the [MobilityData slack](https://docs.google.com/forms/d/e/1FAIpQLSczZbZB9ql_Xl-1uBtmvYmA0fwfm1UX92SyWAdkuMEDfxac5w/viewform), and join the #gtfs-validators channel for updates and questions regarding our GTFS Schedule and Real-time validators. 

A temporary fix has been made for this issue after the v3.1.0 release was published.
I just released [v3.1.1](https://github.com/MobilityData/gtfs-validator/releases/tag/v3.1.1) with the fix, can you try again?

Welcome to the community! 🎉

**Comment by a20r** [comment]
Thank you for the welcome and quick fix! I have verified that the `dmg` installs and that I can validate a GTFS zip file.

![image](https://user-images.githubusercontent.com/2995274/176348039-a380b575-4be1-44d7-88d1-fbc1e650ad38.png)

**Comment by a20r** [comment]
We can close this now?

**Comment by isabelle-dr** [comment]
Yes, closing. See you around!
