### ISSUE TITLE
Flaky acceptance_test.yml workflow?

### ISSUE THREAD

**Issue by bdferris-v2** [MobilityData/gtfs-validator#1226]
## **Bug report** 

I've noticed that `acceptance_test.yml` has been failing to complete more frequently as of late:

https://github.com/MobilityData/gtfs-validator/actions/workflows/acceptance_test.yml

While some failures (aka red X) are due to GitHub infra I believe, there are a number of failure-to-complete runs ("This run was cancelled" stop-sign with ! icon) that seem to have a consistent pattern.  Namely, when running through the queue of feeds for pre-change post-change comparison, the pipeline consistently seems to get cancelled when processing a particular feed.  Namely, 
[de-unknown-ulmer-eisenbahnfreunde-gtfs](https://storage.googleapis.com/storage/v1/b/mdb-latest/o/de-unknown-ulmer-eisenbahnfreunde-gtfs-1081.zip?alt=media)

[Example](https://github.com/MobilityData/gtfs-validator/runs/7614850295?check_suite_focus=true) - notice has the pipeline terminates with a not-super-helpful `Error: The operation was canceled.` message.

My theory is that the `de-unknown-ulmer-eisenbahnfreunde-gtfs` feed is large enough that it's running up against the 8Gb heap limit of the validator, as configured in [queue_runner.sh](https://github.com/MobilityData/gtfs-validator/blob/master/scripts/queue_runner.sh#L16).  Specifically, when I run the validator on this feed, it's utilized heap is running right up against the Heap limit:

<img width="845" alt="Screen Shot 2022-08-04 at 8 08 16 AM" src="https://user-images.githubusercontent.com/26211219/182888150-433499d4-e41e-41fd-a8bd-29e3d1da310f.png">

I think this conceivably be causing the job to fail if we hit OOM?  Not sure why it's not getting logged though.

Either way, I'd like to propose bumping the memory limit to 10G and see if it helps.

**Comment by bdferris-v2** [comment]
Or maybe it's not explicitly OOM-ing, but the memory pressure is slowing down execution, ultimately causing the job to time out?

**Comment by maximearmstrong** [comment]
Oh, well observed, thanks @bdferris-v2.

> Or maybe it's not explicitly OOM-ing, but the memory pressure is slowing down execution, ultimately causing the job to time out?

This makes a lot a sense. Let's try with 10G.

**Comment by isabelle-dr** [comment]
Closing, this was tested in #1227 and it seems to solve the problem for now.
