### ISSUE TITLE
Improve status check process for documentation PRs

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#1231]
## **Feature request**
Update the status check process for documentation PRs. 

Current options:
1. Run the workflow on PRs that only update documentation files as well.
2. Remove the requirement for status checks (not recommended). Checks would still be run, but it would be possible to merge with failed checks.
3. Require fewer status checks, but run them on all PRs, even those that only update documentation files.

**Is your feature request related to a problem? Please describe.**
Currently, a PR that only updates documentation-related files will not trigger the workflows that include the status checks required to merge.

The status checks required to merge the PR are included in
- `end_to_end.yml`
- `end_to_end_100.yml`
- `end_to_end_big.yml`
- `test_pack_doc.yml`

but these ignore the following files
```
- '**.md'
- '**.py'
- 'Dockerfile'
- '.gitignore'
- 'LICENSE'
- 'docker.yml'
- 'formatting.yml'
- 'test_pack_dock.yml'
- 'triage.yml'
- 'acceptance_test.yml'
```
which means that these workflows won't run for any PR updating only files included in that list.

**Proposed solution**
To be discussed with @isabelle-dr.

**Comment by isabelle-dr** [comment]
Closing, captured in https://github.com/MobilityData/gtfs-validator/issues/1339
