### ISSUE TITLE
Lighten end-to-end workflows or remove them

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#1233]
## **Feature request**
Currently, the end-to-end workflows test over 100 datasets at every commit. All datasets from the Mobility Database catalogs are also being tested for each commit excluding `[acceptance test skip]` in the commit message.

Since end-to-end workflows were created before the acceptance tests (partially after that [conversation](https://github.com/MobilityData/gtfs-validator/pull/712#issuecomment-776110813) but even before [here](https://github.com/MobilityData/gtfs-validator/pull/414)), we are wondering if they are still relevant now that the acceptance tests are in place. Originally, they were created to check that new code contributions do not break the validation process.

**Proposed solution**
3 potential solutions:
1. we remove them completely and use only the acceptance instead
2. Lighten the end-to-end workflows, but keep hardcoded URLs as it is right now.
3. Lighten them, but by sampling (say 5%) of the sources in the catalogs.

By lightening end-to-end workflows, but keeping them, users could push commits to PRs and have an overview of how the validation behave, while skipping acceptance tests.

**Comment by maximearmstrong** [comment]
After discussion with @isabelle-dr, our plan would be to pursue option 3. We discussed sampling 5%, which would currently be about 75 datasets. Alternatively, we could sample a fixed number of datasets, say 50-75, as the database will continue to grow.

@bdferris-v2, do you have any thoughts on this? I will open a PR shortly.

**Comment by bdferris-v2** [comment]
@maximearmstrong I don't have any major thoughts here.  Given my comments on the acceptance test PR, I'm ok with reducing the number feeds in the end-to-end test.
