### ISSUE TITLE
Broken link in RULES.md

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1236]
In RULES.md, the link [stop_times.txt best practices](https://github.com/MobilityData/GTFS_Schedule_Best-Practices/blob/master/en/stop_times.md) provided in the missing_timepoint_column notice is broken. 
Additionally, the Best Practice has no mention of timepoint, think link should refer to the specification instead.

It should be replaced by the following link:
- https://gtfs.org/schedule/reference/#stop_timestxt

**Comment by mrajen27** [comment]
Team, I will work on this issue  and raise an PR.

**Comment by isabelle-dr** [comment]
Closing, solved in #1307
