### ISSUE TITLE
[BUG] Validator crashes with any input

### ISSUE THREAD

**Issue by fabrice-v** [MobilityData/gtfs-validator#124]
**Describe the bug**
An exception is raised when trying to build the `InMemoryGtfsSpecRepository` object

**To Reproduce**
Run the validator

**Expected behavior**
The validation should run

**Witnessed behavior**
An exception is raised at the following line
https://github.com/MobilityData/gtfs-validator/blob/61d14f56a63045b646863de4855c68607e85576f/adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsSpecRepository.java#L53

**Environment used**
- OS: macOS 10.15.3
- Java version: openjdk version "11.0.4"
 
**Additional context**
Relates to changes introduced in #111

**Comment by barbeau** [comment]
To avoid issues like this prior to a merge to master, it may be worthwhile adding a simple run-time execution on CI with a tiny GTFS zip file, just to confirm everything runs end-to-end after each build.
