### ISSUE TITLE
"Validate" button disappearing from Desktop app

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1244]
**Describe the bug**
This is a bug from Marcy Jaffe at the National RTAP. They are interested in adding the validator to their toolkit now that there is a Desktop app, but they have run into a problem: after they have selected the input and output directories, the "Validate" button disappears (see screenshot below), which can create confusion or even block some users.
When she made the interface bigger, the button appeared again. 

**How we reproduce the bug**
1. Download desktop app
2. Select input and output directories

**Expected behaviour**
Click on "Validate" to run the validator

**Observed behaviour**
The Validate button is not appearing anymore on the interface. When making the interface bigger, it appears again and the validator could run properly.

**Screenshots:** 
<img width="502" alt="Screen Shot 2022-08-24 at 6 32 06 AM" src="https://user-images.githubusercontent.com/63653518/186396958-1dbbcec2-eb10-4efb-b8bd-fb6a65c7f180.png">

**Environment versions**
- validator version: 3.1.1
- OS versions: Windows

**Comment by isabelle-dr** [comment]
@bdferris, would you have a quick fix for this? Maybe make the default size for the Interface bigger?
Also, there was a message with this bug report to your attention 😊:

> Do say HI to Brian F from Marcy in Port Townsend WA - I'm still in the game!

**Comment by isabelle-dr** [comment]
Actually, it's not about the default size: even if the size is bigger, others are facing this problem: when they pick a file to validate, the button disappears.

**Comment by bdferris-v2** [comment]
@isabelle-dr sorry for just getting to this one

For "when they pick a file to validate, the button disappears": do you have a screenshot from a reporter of what this looks like?  Is it similar to the screenshot from comment #1?

For the original issue, is it possible to ask what the app looks like when they first run it, possibly with a screenshot?  Is the "Validate" button initially visible or is it hidden from the start?  If it's initially visible, is there some action that causes the button to disappear or the dimensions of the window to change?

**Comment by isabelle-dr** [comment]
Hello @bdferris-v2, 

> Is it similar to the screenshot from comment 1?

Yes, it is similar.
The "validate" button is initially visible, and when the user selects the input file, it disappears. See the video below.
We tried it with the original size of the interface, and also with an increased size that takes up 1/2 of the screen, it doesn't seem related.

https://user-images.githubusercontent.com/63653518/190186661-97ddedc1-d63d-4e4a-acf6-42c8ae1296d6.mp4

**Comment by bdferris-v2** [comment]
Interesting.  My key observation here is that after opening the file chooser dialog, the font (both size and font itself) of the app appears to change, which causes the validate button to drop off the bottom of the window because of the larger size.  Not sure why that's happening :)  My guess would be that the file chooser dialog (which is maybe native on Windows?  maybe not?) is tweaking something on the UI look-and-feel.  My initial Googling didn't reveal anything, but let me keep digging.
