### ISSUE TITLE
Enhancement request: allow JAR to output `notice_schema.json` without validating anything

### ISSUE THREAD

**Issue by lauriemerrell** [MobilityData/gtfs-validator#1256]
## **Feature request**
It would be useful to be able to export `notice_schema.json` without actually validating a feed, so that we can automatically update our schema information for validation notices, for example when we upgrade validator versions. 

Currently, it seems that if you are using the `-n` command line option to generate `notice_schema.json` ([docs](https://github.com/MobilityData/gtfs-validator/blob/master/docs/USAGE.md#via-cli-app)), you still have to specify `-i` or `-u`, i.e., you have to actually validate a feed. 

**Is your feature request related to a problem? Please describe.**
We use the validator in our pipeline and it would be convenient to be able to monitor for notice schema changes without having to actually validate a feed. We would perhaps want to run a separate job on a different cadence just to check for validation schema changes when we upgrade validator versions, for example. 

**Proposed solution**
I would like to be able to run the validator JAR from the command line using the `-n` option without specifying an input feed in `-i` or `-u`. 

**Describe alternatives you've considered**
We can just define a test feed that we always use to validate when we are trying to generate `notice_schema.json`. This is not too onerous, it is a fine interim solution. However it would be nice to not have to do this. 

**Additional context**
This is not a high priority, simply a nice to have.

**Comment by bdferris-v2** [comment]
Just to confirm the behavior you are seeing, when you run the command-line jar with options like `-n -o /output-directory`, are you not seeing the schema written at all?  Or are you just seeing a non-zero exit code from the application?

I can confirm the latter behavior (non-zero exit code), which we should fix, but I can't confirm the former behavior (schema not written at all).
