### ISSUE TITLE
Check whether expired services (calendars) exist on schedule feed

### ISSUE THREAD

**Issue by owades** [MobilityData/gtfs-validator#1279]
### Describe the problem

The [GTFS Best Practices](https://gtfs.org/schedule/best-practices/) include the following best practice:

`Remove old services (expired calendars) from the feed.`

We don't have a check that looks for expired calendars

### Describe the new validation rule

If there exists a row in calendar.txt with end_date < TODAY_DATE, or a row in calendar_dates.txt with date < TODAY_DATE, trigger an "expired_calendar" notice

### Severity

Warning

**Comment by isabelle-dr** [comment]
This sounds good, thanks for opening this!

**Comment by bradyhunsaker** [comment]
I will give this a try. I am inclined to rename the file MissingCalendarAndCalendarDateValidator.java as CalendarAndCalendarDateValidator.java and include these checks there.

Any concerns about renaming a file like that?

**Comment by isabelle-dr** [comment]
No concerns, you can go ahead.
(cc @bdferris-v2)

**Comment by bradyhunsaker** [comment]
I was working on this, but I just realized I think it is a duplicate of (part of) https://github.com/MobilityData/gtfs-validator/issues/886
Could you confirm that?

**Comment by isabelle-dr** [comment]
You are right, this issue looks like the second portion of #886! 
Please note that @KClough started to work on this in #1289
