### ISSUE TITLE
[REQUEST] Document validator's rules

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#128]
**Is your feature request related to a problem? Please describe.**
Rules implemented in the validator project should be documented.

**Describe the solution you'd like**
This documentation should be done in a human readable markdown document like https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/RULES.md

**Describe alternatives you've considered**

**Additional context**

**Comment by barbeau** [comment]
This is implemented at https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md, but needs to be updated as the rules are ported to the annotation-based validator for v2.0.
