### ISSUE TITLE
Fix broken links in RULES.md

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1294]
### Describe the problem

Some links in the References section of [RULES.md](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md) are broken. These links are important to understand what the validation problem is. 

The broken links that were flagged so far are the following: 
- [ ] link to stop_times spec (there is an extra "s" character):
  - [x] in [stop_without_stop_time](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#stop_without_stop_time)
  - [ ] in [stop_has_too_many_matches_for_shape](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#stop_has_too_many_matches_for_shape)
  - [x] in [stops_match_shape_out_of_order](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#stops_match_shape_out_of_order)
  - [x] [stop_too_far_from_shape_using_user_distance](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#stop_too_far_from_shape_using_user_distance)
  - [x] [stop_without_stop_time](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#stop_without_stop_time)
- [x] all links that point to the Best Practice GitHub repo (the structure was changed in [this PR](https://github.com/MobilityData/GTFS_Schedule_Best-Practices/pull/47))
  - [x] I know the reference in [missing_timepoint_column](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#missing_timepoint_column) is broken, but there might be more

Please comment on this issue if you know of any others!

**Comment by dsaldonid** [comment]
Hi!
Do you mind if I take this one? I'm a first timer looking to make any contribution I can!

**Comment by isabelle-dr** [comment]
Hey @dsaldonid,
Sure, go ahead 😊. Let us know if you find everything you need, you might want to check out our [contribution guidelines](https://github.com/MobilityData/gtfs-validator/blob/master/docs/CONTRIBUTING.md).

Thanks for helping out!
