### ISSUE TITLE
Welcome bot and Bug triage workflows aren't working

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1298]
### Describe the bug

We have a bug triage workflow that should run every time a new issue is open with a bug label. It sends a message and adds the issue to the Bug triage board.
We have a welcome bot that sends an automatic message when:
- someone opens an issue for the first time on this repo
- someone opens a PR for the first time on this repo
- a PR is merged by a first-time contributor on this repo

The welcome bot is configured in https://github.com/MobilityData/gtfs-validator/blob/master/.github/config.yml
The bug triage is configured in https://github.com/MobilityData/gtfs-validator/blob/master/.github/workflows/triage.yml

It looks like they aren't working anymore.

### Steps/Code to Reproduce

The welcome bot didn't run when [this PR](https://github.com/MobilityData/gtfs-validator/blob/master/.github/workflows/triage.yml) was opened by a first-time contributor.

The bug triage didn't run when [this issue](https://github.com/MobilityData/gtfs-validator/issues/1296) was open.

### Expected Results

The workflows run. 

See [this issue](https://github.com/MobilityData/gtfs-validator/issues/1235) where both workflows ran in August.

### Actual Results

nothing

### Validator version

4.0.0

### Operating system

MacOS

**Comment by lionel-nj** [comment]
Hello @isabelle-dr, for the triage, it looks like a column/project has been deleted from the repository's. 

To fix, you should map to the new column/project  😃 I was just passing by to check on how my baby gtfs-validator is doing. Looks like he's been growing a lot! v4 already!! They grow up so fast! 


<img width="1007" alt="Screen Shot 2022-12-04 at 11 50 41 PM" src="https://user-images.githubusercontent.com/35747326/205552282-c0268e13-3f60-4a47-bdf3-ad8e6bc76d9e.png">

**Comment by isabelle-dr** [comment]
Oh hey there @lionel-nj,

Your baby is doing pretty well 🐥.
Thanks for the insights on how to fix this bug. It matters to us that new contributors are welcomed with cat GIFs, a legacy of our Chief Gif Officer! 😉

**Comment by isabelle-dr** [comment]
The welcome bot is now fixed, but the bug triage is still broken. 

I've added a "Bug triage" board with a "Requires investigation" column and I still get this message: 
<img width="624" alt="Screenshot 2023-02-14 at 11 17 34 AM" src="https://user-images.githubusercontent.com/63653518/218795593-6733a9e5-9b95-41f2-be3e-17356b2d4d3f.png">

**Comment by jcpitre** [comment]
About bug triage, the external Github action we are using (alex-page/github-project-automation-plus) does not work with the new types of projects in Github. Apparently they have the classic version of projects, that works with the external action we use and the V2 version, that is now the default, for which the action does not work. See https://github.com/alex-page/github-project-automation-plus/issues/81#issuecomment-1552390481

One workaround would be to create the bug triage project asa classic project. But it's possible if we already have a classic project. I guess Github want to get rid of classic projects ASAP.

**Comment by fredericsimard** [comment]
I found this, could it be why the welcome bot doesn't fire?

* The first-time contributor might not have added their name to the `contributors` file in the repository. This file is used to track who has contributed to the project, and it is used by the behaviorbot to determine if a contributor is a first-time contributor.
* The first-time contributor might not have pushed their commit to the `master` branch. The behaviorbot only scans the `master` branch for new commits, so if the first-time contributor pushed their commit to a different branch, the behaviorbot would not see it.

**Comment by fredericsimard** [comment]
I've made tiny changes to the bug triage workflow, we'll see when it is triggered next if it works.

**Comment by fredericsimard** [comment]
Bug triage is fixed. Turns out there is no need to create an action, the new Projects have Workflows you can use to do certain actions based on conditions.

I've set two workflows, one that moves the new issue or PR to the Bug triage project, and the second is to move the newly added item to the project in the Requires investigation column. Tada!!

https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/quickstart-for-projects#configure-built-in-automation
