### ISSUE TITLE
Initial support for GTFS Fares v2 - Fare Containers

### ISSUE THREAD

**Issue by bdferris-v2** [MobilityData/gtfs-validator#1301]
Currently, a proposal to add fare containers and payment methods to the GTFS spec is being discussed in https://github.com/google/transit/pull/355.  This is an initial tracking bug to add validation support for the new files and fields introduced in that proposal.

**Comment by isabelle-dr** [comment]
Thanks for opening this @bdferris-v2, I am labeling it as blocked until the PR is merged.

**Comment by bdferris-v2** [comment]
Sounds good.  I actually managed to get the validation logic mostly implemented yesterday.  You can see a preview at:

https://github.com/MobilityData/gtfs-validator/compare/issue/1301/fare_containers?expand=1

I haven't generated a PR yet because the code is blocked by #1302.

For the most part, the validation was pretty straightforward (a good sign to me!), though it did lead to the two comments I added to the spec proposal doc.
