### ISSUE TITLE
The HTML file doesn't work on large reports

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1306]
### Describe the bug

This was flagged by a user working at a GTFS consulting company. 
It seems like when there is a high number of notices triggered, the HTML report doesn't respond well. 
The dataset attached triggers 1000 instances of `missing_timepoint_value` and 55294 instances of `equal_shape_distance_diff_coordinates`. When I try to open details on one of these two, the file is either really slow, or breaks and gives me a blank error page. 

### Steps/Code to Reproduce

- Run validator on the dataset provided.
- Open the HTML file and try to open details for the `missing_timepoint_value` notice.
- The report stops responding. 

### Expected Results

I am able to see the details of the notices.

### Actual Results

Error, blank page.

### Files used

[Westchester_County_Bee-Line_System-20220829T194048Z-e3571abf-0284-4b6d-8a3c-0a9f8dbd8d33-89455444-11e2-4cee-8d9e-7834adb84666.zip](https://github.com/MobilityData/gtfs-validator/files/10246051/Westchester_County_Bee-Line_System-20220829T194048Z-e3571abf-0284-4b6d-8a3c-0a9f8dbd8d33-89455444-11e2-4cee-8d9e-7834adb84666.zip)

### Validator version

3.1.1

### Operating system

Mac OS

### Additional notes

We should have an alternative when an occurrence is really high:
- the user can see the total number of times the notice is triggered, and just show 20 rows in "details" as examples, with a clear mention that this is a sample only.

**Comment by isabelle-dr** [comment]
@briandonahue we might need to change the structure of the JSON report when we have many occurrences of the same notice to only provide a sample or a mention that the notice is present in every record of a file

**Comment by briandonahue** [comment]
@isabelle-dr 
> @briandonahue we might need to change the structure of the JSON report when we have many occurrences of the same notice to only provide a sample or a mention that the notice is present in every record of a file

Perhaps we should leave the JSON as-is, as it may potentially be used in some automated remediation process or something, and we just limit the rows output in the HTML to a sample, like maybe the first 50 or 100 examples of each notice? I tested this with the West Chester file and it does work with this minimal change. We could add text to indicate this is just a sample.

**Comment by isabelle-dr** [comment]
@davidgamez do you have thoughts on what solutions to implement here?

**Comment by davidgamez** [comment]
I agree with @briandonahue. We can leave the JSON file as-is for the same reason. The HTML report can limit the notices to some rows per notice and clarify that it's not the full list. I would be more restrictive in the number of rows per notice, 10 or 20. Doing some math with 10 notice types and 20 individual violations per notice, the report will show 200 rows to review. At that point, it might be more important to know what notices are not in compliance in general than every individual violation. We can also refer to the JSON report for the full list of individual violations.

**Comment by briandonahue** [comment]
@davidgamez Happy to set whatever limit you prefer. Each notice has it's own "accordion" so you can expand/collapse the example records for each notice.

**Comment by davidgamez** [comment]
@briandonahue I have no strong preference for the actual number of notices. The issue here is not rendering the notices that are scoped with the accordion; it's the performance and memory issues in the browser, as too many nodes are created. I can see that 20 - 50 notices are reasonable per notice _type_, but this is an arbitrary selection. What about if we test different numbers and check how they behave?

**Comment by briandonahue** [comment]
@davidgamez without any limit, the Westchester report used over 1GB of RAM to render and hung my browser significantly.  Reducing to 100 reduced RAM usage to under 70 MB.  Further reduction didn't seem to make a big difference, but I think 50 seems a more "scrollable" amount, so I updated it to 50.

I just tested using the Task Manager view of Chrome to check RAM... open to other ideas if you have other preferences.

**Comment by davidgamez** [comment]
Thanks for the stats 💪 , @briandonahue, It seems memory went down significantly after the cuts.  I'm OK to keep it at 50 for now and return to the design table if more performance issues are raised or feedback related to the number of notices shown.
