### ISSUE TITLE
[REQUEST] Implement Agency language vs Feed language (GTFS rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#131]
**Is your feature request related to a problem? Please describe.**
Agency language and Feed language must be the same. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as TYPE_AGENCY_LANG_AND_FEED_LANG_MISMATCH.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if language for agencies is consistent with feedinfo.txt

**Describe alternatives you've considered**

**Additional context**
Line 36 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by barbeau** [comment]
This rule should be reviewed by @timMillet before being implemented. I'm not sure it is an official requirement in the current GTFS spec.

**Comment by maximearmstrong** [comment]
Maybe we could flag it as a warning if it occurs? Since it's in both Google GTFS validator and Google Type Error?

**Comment by barbeau** [comment]
@maximearmstrong We'll need to go through the process of determining whether it's something we want to adopt into the official GTFS spec. If so, and there is consensus among the community, then it would be an error. If not, then this could be one of the configurable values that gets changed depending on which .json configuration you load into the validator. So if you load a "Google" configuration it could indicate it as an error, but others may be just a warning.

**Comment by timMillet** [comment]
`agency.feed_lang` (many) may not match `feed_info.feed_lang` (unique).  It's not a requirement in the spec and I see normal situations where these fields could be different.

I agree I could help on defining what should be an error, and what should/could be a warning.

**Comment by fabrice-v** [comment]
Ok so I guess the question is how the spec handles these files being different, is there a clear precedence rule as to which one to use over the others? It can have an impact on deserialization of numerical values (decimal . vs , for example), and probably other things I dont have in mind.

**Comment by timMillet** [comment]
`feed_info.feed_lang` is the default language of the dataset: "This setting helps GTFS consumers choose capitalization rules and other language-specific settings for the dataset." It has precedence on the others. Heads-up: `mul` meaning multilingual is allowed.

`feed_info.feed_lang` is required but may not be provided as `feed_info.txt` is optional. In this case, `agency.feed_lang` should be used as the default language of the dataset. Heads-up: many `agency.feed_lang` may be provided, with different values. There are no rules to order them.

I'd flag the use of `,` in decimal values as a notice, not an error, no matter the dataset language. The use of `.` is not mandatory but `,` may restrict data consumption.

Hope this may help. Tell me when you'll have the other things in mind.

**Comment by fabrice-v** [comment]
Yes ok I see, that does help a lot.
