### ISSUE TITLE
[Docs] `feed_expiration_date_7_days` and `feed_expiration_date_30_days` code names in RULES.md do not align with actual codes from validator

### ISSUE THREAD

**Issue by lauriemerrell** [MobilityData/gtfs-validator#1322]
### Describe the problem

In RULES.md, two rules are listed as `feed_expiration_date_7_days` and `feed_expiration_date_30_days`. In the actual validator output, the codes are `feed_expiration_date7_days` and `feed_expiration_date30_days`. 

I scraped RULES.md to get human readable error descriptions for our pipeline, and the joins failed because of this discrepancy. I am able to just fix it manually but it would be nice if these were consistent.

### Suggest a fix or an alternative

Either change RULES.md to align with the actual validator code outputs or change the validator to use the version with another underscore, I am not sure the considerations associated with either change (is there a style guide here that should be followed?) but I think they should be consistent.

**Comment by isabelle-dr** [comment]
Hi @lauriemerrell, thanks for opening this issue! 

These codes are created automatically and I think the fact that this one contains a number is causing this issue. 
I propose changing RULES.md as a fix, opened #1323 to fix it.
