### ISSUE TITLE
Downgrade PlatformWithoutParentStation to Info

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1328]
### Describe the problem

It's not a spec recommendation.
See https://gtfs.org/schedule/reference/#stopstxt

### Describe the new validation rule

remove the rule

**Comment by jcpitre** [comment]
Manual testing:

- First step was to have the validator produce the notice.
   - Used an existing dataset: au-queensland-bowen-gtfs-1167.zip
   - edited stops.txt. Changed the first line from
      - `720000,720000,"Williams St at Gregory Street",, -20.013671, 148.245930,1,http://translink.com.au/stop/720000/gtfs/,0,,`
      - `720000,720000,"Williams St at Gregory Street",, -20.013671, 148.245930,1,http://translink.com.au/stop/720000/gtfs/,0,,720006`
   - Essentially giving a platform code to this stop while there is no parent station. The 720006 platform code is just the id of another stop randomly chosen in stops.txt
   - Ran the validator with the original code and it generated a Warning
   - Re-ran the validator with the modified code and it generated an Info.
