### ISSUE TITLE
[REQUEST] Implement Stop must have parent station (GTFS rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#135]
**Is your feature request related to a problem? Please describe.**
A Stop must have a parent station to exist. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as TYPE_LOCATION_WITHOUT_PARENT_STATION.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if stop has no parent station according to the stop type.

**Describe alternatives you've considered**

**Additional context**
Line 42 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by fabrice-v** [comment]
@timMillet Could you clarify what the spec says about requirements of parent_station filed for stop? Reading the spec I concluded that while it's forbidden for Station (location_type=2), it is optional for all other location_type values, was that a misread?
