### ISSUE TITLE
[chore]: Add unit tests to web validator classes

### ISSUE THREAD

**Issue by davidgamez** [MobilityData/gtfs-validator#1356]
## Description

Add unit tests to web validator classes added as part of #1317.

**Comment by KClough** [comment]
@davidgamez should we have a separate issue for tracking service vs client unit tests?

**Comment by davidgamez** [comment]
@KClough I think so. Let's have two independent issues for unit testing.

**Comment by themightychris** [comment]
Cypress E2E tests for the frontend are scoped in #1390 and implemented in #1396
