### ISSUE TITLE
Add metadata in the validator report

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1363]
### Describe the problem

Metadata is a piece of key information, it can provide a quick overview of what is included in the dataset:
- the size: number of stops, routes, trips
- the files that are present (if `frequency.txt` is present -> it's a [frequency-based](https://gtfs.org/schedule/examples/frequencies/) service)
- information about the agency (name, phone number & e-mail if provided, and the publisher)
- the spec "features" present (fares v1, fares v2, pathways)

It can be used to answer:
- How much work is it going to take to ingest this data?
- How many datasets contain Fares v2? (assumed if running this validator on a group of datasets)
- Is this a frequency-based trip? 
- Are shapes included?
- etc

### Proposed solution

Add a section in the report that contains metadata (it could have a less jargon-y name, such as "Overview").

For efficiency when the validator is used via the command line, We could allow users to run only the portion that triggers the list of notices, or the portion that generates the metadata.

The content I am proposing for this section is inspired by a series of user interviews, and by looking at other validators that exist. This will evolve with time, but I suggest we start with:

1. file presence: what files are present in the dataset?

2. "counts": number of agencies, routes, trips, stops, shapes, blocks (using the `id` fields)
  
3. Feed info (from `feed_info.txt`, which is optional so not always provided)
  - start and end date (when provided)
  - publisher name (required)
  - publisher URL (required)
  - language (required)

4. information about the agencies (from `agency.txt`, which is required)
  - name (required)
  - url (required)
  - phone number (when provided)
  - email (when provided)

5. presence of spec features (based on [this script](https://github.com/MobilityData/mobility-database-catalogs/blob/main/update_gtfs_schedule_sources.py) from Mobility Database)
  - fares-v1 
  - fares-v2
  - flex-v1
  - flex-v2
  - pathways

### Other information could be added, where additional research is needed.

6. More "features" (I want to confirm how to define these ones, how many we need, and how they relate to fares-v1 and fares-v2 concepts).
  - wheelchair-accessible fields
  - bike-allowed field
  - etc

7. More calendar information
  - first and last day of service 

8. Provide detailed information per agency
  -  for example: the first and last service day for each agency in the dataset. I am especially inspired by how transport.data.gouv displays this, here is what it looks like for MTC's dataset that contains many agencies.

<img width="300" alt="Screenshot 2023-03-24 at 5 46 14 PM" src="https://user-images.githubusercontent.com/63653518/227647249-59b831fd-6e56-4319-81ab-3a07b7d03b80.png">

### Alternatives you've considered

Add this type of thing as an `INFO` validator notice. 
It would have been a reasonable thing to do also, especially because `INFO` isn't well defined, but I think `INFO` gives us a place to put the "not technically a spec violation but FYI you might want to have a look" type of things, such as unknown files and columns, or unused stations.

I think this type of information deserves a new section. Happy to be challenged if anyone thinks this should belong alongside the validator notices.

**Comment by briandonahue** [comment]
@isabelle-dr @bdferris-v2 @davidgamez I'm looking into this. I see some metadata is being [compiled in the realtime validator](https://github.com/MobilityData/gtfs-realtime-validator/blob/master/gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/validation/GtfsMetadata.java).  I'm wondering if it's worth porting that into `gtfs-validator` and having the realtime validator reference that, or whether I should create new metadata classes/aggregators from scratch in `gtfs-validator`? Any thoughts?

**Comment by briandonahue** [comment]
@bdferris-v2 This was my initial impression - that we'd need to basically re-create, maybe porting some bits and pieces, the metadata classes and aggregation.  It seems like we use a lot of reflection to build table containers, etc, so will need to dig into all that and see where it makes sense to build up overall metadata.  Just wanted to make sure I was on the right track. And of course, I'm open to any other suggestions on approach.

**Comment by briandonahue** [comment]
@isabelle-dr it seems to me in the [script](https://github.com/MobilityData/mobility-database-catalogs/blob/main/update_gtfs_schedule_sources.py) you linked, the Flex V1 check is looking for fields in `stop_times.txt` that don't exist in the `GtfsStopTimeSchema` or in the specification... are they outdated, or am I missing something?

**Comment by isabelle-dr** [comment]
Hello @briandonahue. 
I did not expect that you would start so quickly 🙈. 
We have drafted a document that gives more details about this issue.
[Here is a link to the doc](https://docs.google.com/document/d/157X9lMTkZHH7oYxK1fYPiY-rMh_VWyPMW_s9wImOP-I/edit#).
Please have a look at it, you can comment on it with any questions.

Regarding Flex: this has not been adopted officially, so it's not appearing in our schema files (yet). If there a way around that?

**Comment by briandonahue** [comment]
@isabelle-dr Thanks! At initial glance, I think what I did so far is in line with what is in the document. Re: flex, I would have to add those files/schemas to the codebase to be able to add them to the metadata. It is possible, but maybe should be a separate task/issue?
