### ISSUE TITLE
[REQUEST] Implement travel speed verification between stops (GTFS rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#137]
**Is your feature request related to a problem? Please describe.**
Going from a stop to another one should not be too fast. This is true for consecutive stops and for stops that are far from each other. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as TYPE_FAST_TRAVEL_BETWEEN_CONSECUTIVE_STOPS and TYPE_FAST_TRAVEL_BETWEEN_FAR_STOPS.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if trip is too fast according the stop times, schedule and shape.

**Describe alternatives you've considered**

**Additional context**
Line 47 and 48 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by LeoFrachet** [comment]
duration = to_stop_time.arrival_time - from_stop_time.departure_time
distance = distanceBetweenCoor(from_stop.lat, from_stop.lon, to_stop.lat, to_stop_lon)

speed = distance/duration

If speed is above 1km/h then BAAAAAAD

**Comment by barbeau** [comment]
I think you could technically call this out-of-spec, because the spec and best practices don't reference any threshold (to my knowledge). But I think this error is probably one of the most common error in feeds, so I'd consider it high priority.
