### ISSUE TITLE
Web Validator: Integrate Monitoring Service

### ISSUE THREAD

**Issue by KClough** [MobilityData/gtfs-validator#1372]
### Describe the problem

In order to help alert infrastructure admins if there is a problem with the web validator, we recommend using a monitoring service like New Relic. 

This will allow the infrastructure team to be notified when there is any issue with the service and help provide data to inform performance tuning.

This data will also help to provide some analysis on how the validator is used. 

Newrelic provides both JS (client) and Java (service) libraries. 

We believe the [free tier](https://newrelic.com/pricing) should provide sufficient benefit to cover the scenarios above. 

- one free full platform user and 100 GB/month of data ingested included

### Proposed solution

> Why New Relic?
> 
> Real, actionable insights into your stack
> Correlate issues across your stack. Debug and collaborate from your IDE. AI assistance at every step. All in one connected experience - not a maze of charts
> 
> Troubleshoot infrastructure before. Not after.
> Find root cause faster. Correlate infrastructure health with performance and customer impact on one platform.
> 
> Dashboards, alerts, and integrations all in one place
> Our Instant Observability quickstarts bundle everything you need to start monitoring like a pro right out of the box.
> 
> Quickly integrate with hundreds of tools and open standards.
> Integrate easily with leading cloud providers. New Relic is committed to open standards, open instrumentation, and the open communities that support them.

[Pricing info here](https://newrelic.com/pricing)

### Additional context

https://github.com/MobilityData/gtfs-validator/pull/1317

**Comment by themightychris** [comment]
New Relic provides a lot of plug-and-play value and the best visibility in terms of end-to-end performance analysis.

Where it's relatively weaker is in error analysis which Sentry excels at. Both provide a ton of value out of the box with relatively minimal setup effort and costs so I recommend setting up both for strong visibility
