### ISSUE TITLE
Web Validator: Add Sentry to Service + Client to capture errors

### ISSUE THREAD

**Issue by KClough** [MobilityData/gtfs-validator#1373]
### Describe the problem

In order to maintain quality of service, we should use a monitoring service in order to triage unexpected errors + exceptions. We recommend [Sentry](https://sentry.io/welcome/). 

Sentry has client libraries for both Javascript and Java. 

### Proposed solution

Add Sentry library to both the web client and web service. 

[Pricing](https://sentry.io/pricing/).

### Additional context

https://github.com/MobilityData/gtfs-validator/pull/1317

**Comment by davidgamez** [comment]
👁️ @fredericsimard 👁️
