### ISSUE TITLE
Update README.md with Web UI, publish 4.1.0 release, update external links to the Web UI

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1378]
We are almost done with the issues we had lined-up for 4.1.0!

To do:
- [x] Update the README.md file with the Web UI
- [x] Publish the release on GH
- [ ] ~~evaluate the impact of the release on stakeholders (new errors and warnings) and outreach to let them know @emmambd ~~
- [x] Update the validation page on gtfs.org to link to the new web UI
- [x] Publish the press release
- [x] Send e-mail to orgs that asked to be updated when we have a release
- [x] Outreach to orgs that are linking to this validator to tell them they can update the link to the Web UI
    - [x] Cal ITP (in the Data Quality Guidelines)
    - [x] Google (link in partnerdash)
    - [x] FTA (for the National Transit Database)
    - potentially others! I will use an online tool to find where we have links to this validator

**Comment by isabelle-dr** [comment]
@davidgamez let me know when you have the comparison of V4 and v4.1 using the acceptance test so we can reach-out to agencies that are affected by the release (new or disappearing notices)

**Comment by emmambd** [comment]
@isabelle-dr Which online tool were you going to use to find external references to the validator?
