### ISSUE TITLE
[REQUEST] Implement Feed has a language verification (GTFS rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#139]
**Is your feature request related to a problem? Please describe.**
A feed must have a language defined. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as TYPE_FEED_HAS_NO_LANGUAGE.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if empty or if lang is in ISO639.

**Describe alternatives you've considered**

**Additional context**
Line 51 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by LeoFrachet** [comment]
easy

**Comment by lionel-nj** [comment]
Implemented in https://github.com/MobilityData/gtfs-validator/pull/81
