### ISSUE TITLE
Mixed case validation notice schema is incomplete

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1392]
### Describe the problem

Mixed case validation was introduced in #1340.
In the validation report, we don't see the record values that trigger this notice, only the number of the row (see image below).
Seeing the actual value here would encourage the user to fix the issue because they would see what the rider would see.
Additionally, the `filename` name doesn't follow our naming conventions, it should be `fileName`.

<img width="1426" alt="Screenshot 2023-04-19 at 6 42 11 PM" src="https://user-images.githubusercontent.com/63653518/233215293-de8642f6-620f-4e46-a4ec-a08ddc73f9ea.png">

### Proposed solution

I recommend adding a `FieldValue` in the schema that displays the value of the faulty record, and changing `filename` to `fileName` to follow our naming conventions.

 

### Alternatives you've considered

Status quo

**Comment by isabelle-dr** [comment]
@briandonahue, would you be able to fix this issue? :)

**Comment by briandonahue** [comment]
@isabelle-dr I've started #1393, but there is an issue in master (#1394) blocking me at the moment.

Also, I believe @bdferris-v2 confirmed this in another conversation, but all notices and documentation are currently using `filename`, all lower-case, at the moment, so I'm leaving that field name as-is for now and we discuss whether this convention should be changed globally.
