### ISSUE TITLE
Web Validator: add link details to results page

### ISSUE THREAD

**Issue by themightychris** [MobilityData/gtfs-validator#1395]
@ryon 

On the results page, add:

- [ ] a notice informing the user that they can share the URL of their results with others for at least 30 days
- [ ] a link the `report.json` file that is right next to `report.html` in the storage bucket

**Comment by isabelle-dr** [comment]
Good idea! 
Am I understanding correctly that the URL link itself is only working for 30 days?

Would be nice to have an option that allows the user to copy the URL in one click.
The flow could be (similar to other "share" functionalities).
- click on a Share button
- copy the URL link

**Comment by themightychris** [comment]
@isabelle-dr well the links will work until we purge results and a process for actually purging aged results isn't in our immediate scope, so right now they'll work indefinitely... but we want to set conservative expectations

Good point re: a handy way to copy, I'll leave that to @ryon's consideration

**Comment by isabelle-dr** [comment]
Ok that makes sense. 

For the JSON -> you thinking of adding a download link or will it be an online instance of the JSON?

**Comment by ryon** [comment]
See my PR for more details: https://github.com/MobilityData/gtfs-validator/pull/1397

https://user-images.githubusercontent.com/1154929/233803546-d368112c-7a90-4735-bb49-a33dadbdf574.mov
