### ISSUE TITLE
Error "Sorry, only ZIP files are supported at this time." when uploading zip file

### ISSUE THREAD

**Issue by Bertware** [MobilityData/gtfs-validator#1404]
### Describe the bug

When uploading a valid GTFS file, the file is rejected as it is not considered a GTFS file.

### Steps/Code to Reproduce

- Navigate to https://gtfs-validator.mobilitydata.org/
- Either use the upload button or drag-and-drop a zip file (both produce the same result)
- The javascript console shows 'file type error application/x-zip-compressed'
- The user interface shows "Sorry, only ZIP files are supported at this time."

### Expected Results

The file is accepted

### Actual Results

The file is rejected as "not a zip file"

### Screenshots

![Screenshot](https://user-images.githubusercontent.com/1094793/235180493-5b2e94a6-85b6-414f-96ad-7b84f8905486.png)

### Files used

[skane.zip](https://github.com/MobilityData/gtfs-validator/files/11354682/skane.zip)

### Validator version

1680987682907

### Operating system

Windows 10

### Additional notes

Using Firefox 112.0.2 with uBlock Origin installed. Disabling uBlock Origin does not make any difference.

**Comment by Bertware** [comment]
This issue can also be reproduced in Microsoft Edge version 112

**Comment by KClough** [comment]
Did some initial triage on this issue. When I attempt to check the mime type of the supplied zip file via command line, I get the following result:

```bash
➜  Downloads file --mime-type skane.zip
skane.zip: application/java-archive
```

Currently, the system only accepts `application/zip`.  

Additional testing is required to determine if we can easily support `application/java-archive` files.

**Comment by isabelle-dr** [comment]
I just tested the file provided, it worked on my computer 🤔.
![Screenshot 2023-05-01 at 12 16 34 PM](https://user-images.githubusercontent.com/63653518/235485905-b731a4cb-b592-4fdc-a68e-2a6aef02f0da.png)

**Comment by Bertware** [comment]
> skane.zip: application/java-archive

Interesting, seems like I should double-check how we create these zip-files to ensure they have the correct mime-type. If this is the issue, I'd suggest making the `file type error application/x-compressed` message in the javascript console a bit more clear, since i figured it meant the file I uploaded was of the type `application/x-compressed`.

> I just tested the file provided, it worked on my computer 🤔.

I re-tested by downloading the file from Github thinking Github might have altered some mime-code, but the same error persists. Could this be OS or browser dependent?

**Comment by emmambd** [comment]
This seems to be an OS dependent bug - I tried to recreate this on a Macbook Pro on Chrome, Firefox and Safari with no luck, but was able to recreate it on a Windows 10 instance using Edge.

**Comment by jcpitre** [comment]
I took a look and on Windows it seems the mime-type the browser uses is _application/x-zip-compressed_ whereas on Mac it's _application/zip_
The code in +page.svelte only checks for application/zip.
We should also check for application/x-zip-compressed
