### ISSUE TITLE
Web Validator: Refactor error handling

### ISSUE THREAD

**Issue by KClough** [MobilityData/gtfs-validator#1419]
### Describe the problem

The original implementation relies on the Google Cloud Pub Sub's automatic retry functionality. This worked well when we were debugging out of memory issues, and needed to increase the infrastructure capacity to handle larger files.

However, after reviewing some production errors, some issues like large GTFS files or unexpected exceptions will retry multiple times despite the fact that the same result will occur.

In order to provide better UX, we can store any unhandled exception message and update the web client to pass this information to the user. 

### Proposed solution

In order to accomplish this, I propose the following changes:

- Update the service logic to always write a job json file, currently it is only used if there is a countryCode or url supplied
- Update the service logic so that we store processing status to the job json file
- Update the service error handling logic to write an error status + message to the job json file
- Update the service error handling logic to respond with 2xx message to prevent retries
- Update the client to poll for the job json file + status complete rather than the report file
- Update the client to show the error message when the job json reports an error status

**Comment by davidgamez** [comment]
This issue had been addressed by #1688 and #1689
