### ISSUE TITLE
Output fieldName of missing_recommended_field notice even if there is no column

### ISSUE THREAD

**Issue by takohei** [MobilityData/gtfs-validator#1425]
### Describe the bug

It is specified in [RULES.md](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#missing_recommended_field) that the notice of missing_recommended_field should have fieldNames.

However, if there is no column in the header, the fieldName is not output.
So it is difficult for us to identify which field is unset.

### Steps/Code to Reproduce

Validate attached feed.
It has no column for feed_contact_email and no value for feed_contact_url in the feed_info.txt.

### Expected Results

In report.json, both feed_contact_email and feed_contact_url notices have fieldNames.
```
    {
      "code": "missing_recommended_field",
      "severity": "WARNING",
      "totalNotices": 2,
      "sampleNotices": [
        {
          "filename": "feed_info.txt",
          "csvRowNumber": 2.0
          "fieldName": "feed_contact_email "
        },
        {
          "filename": "feed_info.txt",
          "csvRowNumber": 2.0,
          "fieldName": "feed_contact_url"
        }
      ]
    }
```

### Actual Results

In report.json, the feed_contact_url notice has fieldName, but the feed_contact_email notice has no fieldName.
```
    {
      "code": "missing_recommended_field",
      "severity": "WARNING",
      "totalNotices": 2,
      "sampleNotices": [
        {
          "filename": "feed_info.txt",
          "csvRowNumber": 2.0
        },
        {
          "filename": "feed_info.txt",
          "csvRowNumber": 2.0,
          "fieldName": "feed_contact_url"
        }
      ]
    }
```

### Screenshots

The detail table of report.json has value but no header of fieldName.
![image](https://user-images.githubusercontent.com/48475419/235476055-c131ea8b-a0bc-482a-9ab5-b6fa675d203a.png)

### Files used

[no_mail_column_no_url_value_akocity.zip](https://github.com/MobilityData/gtfs-validator/files/11366168/no_mail_column_no_url_value_akocity.zip)
[report.json.txt](https://github.com/MobilityData/gtfs-validator/files/11366243/report.json.txt)

### Validator version

4.1.0

### Operating system

Windows

### Java version

18

### Additional notes

This is just a guess as I do not have a development environment, but the following code may not get the column name if there is no column header.

https://github.com/MobilityData/gtfs-validator/blob/19ed06d894a0ee44f104bf54cae3301d3c7ef7ed/core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java#L134-L138

**Comment by takohei** [comment]
I checked the variables using the debugger and my guess was correct.

If a recommended column is not in the header, columnIndex will be -1 and getColumnName() will not return the column name, so the feedName will not be output.
I am not sure how to fix it properly.

**Comment by isabelle-dr** [comment]
Thank you for opening this issue @takohei!
Our team will have a look at it shortly.

**Comment by takohei** [comment]
@isabelle-dr 
Thanks for your reply and triage.

As a test, I changed the argument of axX()@RowParser.java from FieldLevelEnum to GtfsColumnDescriptor and it worked well.

**Comment by qcdyx** [comment]
Hello @takohei, you are right. Using the GtfsColumnDescriptor is the way to go. I fix this issue by using this approach. Thanks for digging deep into the code.
