### ISSUE TITLE
Gradle aggregrateJavadocJar hangs indefinitely.

### ISSUE THREAD

**Issue by bdferris-v2** [MobilityData/gtfs-validator#1431]
As discussed on #gtfs-validators, the command `./gradlew aggregateJavadocJar` hangs indefinitely for me and seemingly for others as well.  This task is executed automatically as part of a `./gradlew build` call.

Interestingly, `aggregateJavadoc` runs successfully for me and it's only the jar phase that hangs.  When run the jar step specifically, I see that `gtfs-validator-4.1.1-SNAPSHOT-javadoc.jar` is being generated... and it's gigantic.  Multiple GBs and it will keep on growing if you let the command continue to run.  So looks like the task is stuck in some sort of loop where it's attempting to create a never-ending jar file.

This looks similar to this issue: https://github.com/freefair/gradle-plugins/issues/640 which unfortunately has no responses.

This is on the `master` branch with MacOS and openjdk 11.0.19 2023-04-18 LTS.

**Comment by bdferris-v2** [comment]
I tried upgrading the `io.freefair.aggregate-javadoc-jar` plugin to `8.0.1` but this did not fix the issue.

**Comment by bdferris-v2** [comment]
Interestingly, the `io.freefair.aggregate-javadoc-jar` plugin was added by me (!) per discussion in https://github.com/MobilityData/gtfs-validator/pull/1125#issuecomment-1116568232 to work around an issue with the old aggregation plugin we were using.

Critically, I can't find any indication that anyone actually cares about the Javadoc _jar_  file (does anyone care about the Javadoc at all?).  In fact, we only execute `aggregateJavadoc` in `test_pack_doc.yml`, not `aggregateJavadocJar`.  And it turns out freefair provides a version of the plugin that doesn't export the jar command.  So I think we can just switch to that and be fine?  I've confirmed that `build` runs successfully when I make this change locally.

**Comment by mfnalex** [comment]
> does anyone care about the Javadoc at all

Yes, I do. I'd like to create an aggregated javadoc .jar and aggregated javadocs as html, unfortunately I got the same issue. https://github.com/freefair/gradle-plugins/issues/798  Has anyone yet found a fix for this?

**Comment by mfnalex** [comment]
Maybe this fixes your issue, it did work for me: https://github.com/freefair/gradle-plugins/issues/798#issuecomment-1565452423
