### ISSUE TITLE
[REQUEST] Determine order to process gtfs entities

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#144]
**Is your feature request related to a problem? Please describe.**
Before implementing GTFS validation rules, the order in which gtfs entities should be handled must be determined based on "conditionaly required" and ID fields. 

This information is available at http://gtfs.org/reference/static

**Comment by lionel-nj** [comment]
**Suggestion:**
1. feed_info.txt
2. agency.txt
3. fare_rules.txt
4. routes.txt
5. calendar.txt
6. calendar_dates.txt
7. routes.txt
8. shapes.txt
9. trips.txt
10. attributions.txt
11. frequencies
12. levels.txt
13. stops.txt
14. transfers.txt
15. pathways.txt
16. fare_attributes.txt
17. stop_times.txt
18. translations.txt


**Note**:  feed_info.txt is optional but required if translations.txt is provided. Therefore, one must check the existence of translations.txt in the first place, then proceeed to semantic validation.

**Comment by lionel-nj** [comment]
This issue is to ease or formalize the order to process entities @maximearmstrong

**Comment by barbeau** [comment]
This GTFS data model (from [TransitWiki](https://www.transitwiki.org/TransitWiki/index.php/General_Transit_Feed_Specification)) may help with the IDs:

![image](https://user-images.githubusercontent.com/928045/80810041-f595ad00-8b90-11ea-934c-962dcc81b68a.png)

**Comment by barbeau** [comment]
@lionel-nj From a quick scan the above list mostly looks good! One change - fare_attributes.txt needs to be before fare_rules.txt.

**Comment by barbeau** [comment]
Oh, and frequencies.txt needs to be before trips.txt.

**Comment by lionel-nj** [comment]
> Oh, and frequencies.txt needs to be before trips.txt.

Actually, frequencies.txt has a field trip_id that refers to trips.txt, so I think that it should be after trips.txt

**Comment by barbeau** [comment]
@lionel-nj Ah, sorry, you're right - got that one backwards.
