### ISSUE TITLE
Web Validator hangs after supplying non-zip URL

### ISSUE THREAD

**Issue by evansiroky** [MobilityData/gtfs-validator#1445]
### Describe the bug

Potentially related to #1440, if a URL to a non-zip file is provided, the web validator will hang and not be able to proceed.

### Steps/Code to Reproduce

1. Open web validator
2. Enter `http://www.google.com` as the URL
3. Press the validate button

### Expected Results

There should be an error that says that the URL does not appear to contain a zip file.

### Actual Results

Web app hangs.

### Screenshots

![Screen Recording 2023-05-23 at 11 37 58 AM](https://github.com/MobilityData/gtfs-validator/assets/3112493/5ce8e07a-815f-446f-bd5c-f2367eb06b07)

### Files used

none

### Validator version

latest

### Operating system

Web

**Comment by Rossellaross87polito** [comment]
hello i have updated a zip file and the report of the validator is:
GTFS Schedule Validation Report
104789 notices reported (0 errors, 104783 warnings, 6 infos)
This validation report was generated using the [Canonical GTFS Schedule validator](https://github.com/MobilityData/gtfs-validator).

Use this report alongside the [rules](https://gtfs-validator.mobilitydata.org/rules.html) page to get more details about the validation issues.

there is a problem in the plug in.
Could you help me?
[gtfs_compressed.zip](https://github.com/MobilityData/gtfs-validator/files/11566605/gtfs_compressed.zip)

**Comment by isabelle-dr** [comment]
@Rossellaross87polito is the problem that the report wasn't rendering properly / not at all?
If this is the case, it's probably because the report contains too many notices. 
We limited the number of records to appear on the report in #1433 which was merged last week. Can you try again?

**Comment by isabelle-dr** [comment]
@evansiroky thank you for opening this. 
We will have a look at it this week.
