### ISSUE TITLE
Deploy web client+service to a staging environment on push to master

### ISSUE THREAD

**Issue by themightychris** [MobilityData/gtfs-validator#1487]
While #1486 removes the behavior of deploying the web client+service to production on each push to master in favor of only doing it on release, we want to create a new staging environment that we can deploy to on each merge/push to `master`.

The staging environment can use the same GCS bucket as production for storing uploads/results since they are keyed to random UUIDs.

**Comment by davidgamez** [comment]
> @davidgamez is `https://gtfs-validator-staging.mobilitydata.org/` the best URL for it to live at?

It looks good to me.

cc: @fredericsimard

**Comment by fredericsimard** [comment]
LGTM. I would need the IP or what to point at to add the DNS entry.

**Comment by davidgamez** [comment]
Closed by #1560
