### ISSUE TITLE
[REQUEST] Implement unique route names verification (GTFS rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#149]
**Is your feature request related to a problem? Please describe.**
Route short and long names should be unique, and their combination should be unique. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as TYPE_ROUTE_NAME_REUSED.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if route_short_name and route_long_name combination is not used multiple times.

**Describe alternatives you've considered**

**Additional context**
Line 76 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by barbeau** [comment]
To help differentiate this vs https://github.com/MobilityData/gtfs-validator/issues/150 - my understanding is that this issue is comparing across multiple records from the routes.txt file, while https://github.com/MobilityData/gtfs-validator/issues/150 is looking at route short and long name within the same record.

**Comment by maximearmstrong** [comment]
Exactly, here it is the combination that should be unique, i.e. a route short name can't be associated to 2 different route long names

**Comment by timMillet** [comment]
It happens that different routes have the same `routes.route_short_name` values:
- if they are not part of the same agency (e.g: feed IDFM, Paris FR)
- they are not part of the same "service brand" like regular bus routes, school bus routes (feed: Auckland Transport, Auckland NZ)

It happens that different routes have the same `routes.route_long_name` values:
- When routes do not have actual long names, but the service brand like Express or Commuter is included within the `routes.route_long_name` (feed: some US agencies), as the Best Practices say.

So the validator should issue a warning but not an error. The warning message must explicit that if routes have the same route_short_name or route_long_name, they **must** be different routes serving different areas; and **must not** be different trips of the same route or different directions of the same route.
