### ISSUE TITLE
Add validation support for Time-Variable Fares

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1494]
### Describe the problem

We are about to add time-variable Fares to GTFS , the spec addition can be found in https://github.com/google/transit/pull/357. 

This validator needs to be updated, ideally before we open the vote so that
- we can catch any interpretation ambiguities
- the stakeholders that are already working with the addition can validate it (via a branch).at

### Proposed solution

Update the schema and add the new rules to this validator. 
Overview of the changes:
1. Added the `timeframes.txt` file and added `from_timeframe_group_id`, `to_timeframe_group_id` to `fare_leg_rules.txt`

2. New Requirements
- Values greater than `24:00:00` in `timeframes.start_time` and `timeframes.end_time` are forbidden (ERROR)
- `timeframes.start_time` and `timeframes.end_time` can either both be defined, or neither. Having only one is an error. (ERROR)
- There must not be overlapping time intervals for the same `timeframe_group_id` and `service_id` values (ERROR)

**Comment by isabelle-dr** [comment]
@bdferris let us know if you're still interested to work on this one & have the capacity in the coming week(s).
I am also interested to know if you think we need additional validation around times. 
We think we'll be able to open the vote before the end of June.

**Comment by bdferris-v2** [comment]
Yeah, I should be able to help with this.
