### ISSUE TITLE
Update NEW_RULES.md after latest changes

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1509]
### Describe the problem

In the past few months, we have modified the way we generate new rules in this validator, mainly:
- in the PRs related to this issue https://github.com/MobilityData/gtfs-validator/issues/1324
- in this PR https://github.com/MobilityData/gtfs-validator/pull/1489

The [RULES.md](https://github.com/MobilityData/gtfs-validator/blob/master/docs/NEW_RULES.md) describes to contributors how to add a new notice to this validator which is now outdated. We should update RULES.md so that it is representative of the current practice.

**Comment by AnuragSingh612** [comment]
Assign it to me pls.

**Comment by bdferris-v2** [comment]
We've made a lot of updates to `NEW_RULES.md` based on the changes described above already.  Is there a specific piece that needs updating?

**Comment by davidgamez** [comment]
I verified that `NEW_RULES.md` is updated with the latest supported rules implementation. Closing this issue for now.
