### ISSUE TITLE
[REQUEST] Implement route short name length verification (GTFS Rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#151]
**Is your feature request related to a problem? Please describe.**
Route short name should be less or equal the maximum length allowed. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as TYPE_ROUTE_SHORT_NAME_IS_TOO_LONG.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if route_short_name length is not greater than 6 characters.

**Describe alternatives you've considered**

**Additional context**
Line 79 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by maximearmstrong** [comment]
GTFS Spec specifies that `route_short_name` should be 12 characters long and not 6, so this will be implemented.

**Comment by barbeau** [comment]
@maximearmstrong We do need to be careful about what is said in the main GTFS spec (https://gtfs.org/reference/static/#routestxt) vs best practices (https://gtfs.org/best-practices/).

Generally, IMHO if a rule is stated in the GTFS spec, then it should be an error, but if it's not in the spec and appears only in the GTFS Best Practices, then it should be a warning.

So, in this case, the best practices say it shouldn't be longer than 12 characters, but the spec is silent, so it should be a warning.

This needs feedback from @timMillet too.

**Comment by maximearmstrong** [comment]
Rule implemented in PR #214

**Comment by maximearmstrong** [comment]
@barbeau, @timMillet confirmed it should be a warning. I will move it.

**Comment by timMillet** [comment]
I agree 100% with @barbeau. Anything related to best practices cannot be an error, but must be a warning.

**Comment by maximearmstrong** [comment]
Modification implemented in PR #217
