### ISSUE TITLE
[REQUEST] Implement route short and long names presence (GTFS Rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#152]
**Is your feature request related to a problem? Please describe.**
Route should have both a short name and long name. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as TYPE_ROUTE_BOTH_SHORT_NAME_AND_LONG_NAME_PRESENT.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies both presence.

**Describe alternatives you've considered**

**Additional context**
Line 81 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by barbeau** [comment]
@timMillet Another potential candidate for a GTFS spec change.

GTFS spec (https://gtfs.org/reference/static#routestxt) says differently than this Python validation rule:

>Either route_short_name or route_long_name must be specified, or potentially both if appropriate.

Best practices (https://gtfs.org/best-practices/#routestxt) actually say:

>At least one of route_short_name or route_long_name must be specified, or potentially both if appropriate. If the route does not have a long name, please specify a route_short_name and use an empty string as the value for this field.

**Comment by timMillet** [comment]
@barbeau I wouldn't make a GTFS spec change IMHO. For having monitored tons of these fields back when I was working at Transit app, it's true that sometimes providing only one of them makes sense. I often saw `route_short_name` values populated with `route_long_name` abbreviations that only exist in the GTFS feed, and never showed up by the transit agency to its riders in the real life. Also, I often checked for `route_long_name` values on the transit agency website to fill missing ones in the feed, and I couldn't find any official ones.

@maximearmstrong Missing  both `route_short_name` and `route_long_name` should not be an error, but could be a simple notice.

**Comment by maximearmstrong** [comment]
Rule implemented in PR #217
