### ISSUE TITLE
Automate generation of release artifacts

### ISSUE THREAD

**Issue by davidgamez** [MobilityData/gtfs-validator#1525]
### Describe the problem

As part of the release cycles, automate the generation of the release artifact. This automation of the artifact generation standard across releases reduces human errors. 
List of artifacts:
- CLI version of gtfs-validator(jar file)
- OS desktop installers
- rules.json
- Java sources(zip file) - TBD 
- Java docs(zip file) - TBD 

Part of #1523

### Proposed solution

Use GitHub actions to generate all necessary artifacts

**Comment by cka-y** [comment]
@davidgamez  since we are deprecating the desktop version do we still want to add the installer as an artifact?

**Comment by davidgamez** [comment]
> @davidgamez since we are deprecating the desktop version do we still want to add the installer as an artifact?

Let's include the artifacts related to the desktop app, as the _desktop application deprecation_ will only occur if statistics support it; in any case, the effort of attaching the artifacts is not huge.
