### ISSUE TITLE
Get list of validators that couldn't run because of a parsing problem

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1537]
### Describe the problem
Currently this tool logs all validators that **didn't** run. We want to log a list of validators that **couldn't** run (because of a parsing problem. Should exclude validators that are optional and should not be run on the specific feed.
In order to achieve https://github.com/MobilityData/gtfs-validator/issues/1536 and then https://github.com/MobilityData/gtfs-validator/issues/1485

I need to see the notices that were not triggered but could be present in my dataset.
- **Users should only see validators in the parsing [error log](https://github.com/MobilityData/gtfs-validator/issues/1193#issuecomment-1618954067) that are relevant to their feed**. If I don’t have any GTFS fields that are of the [Color field type](https://gtfs.org/schedule/reference/#field-types), then the [route_color_contrast](https://github.com/MobilityData/gtfs-validator/blob/master/main/src/main/java/org/mobilitydata/gtfsvalidator/validator/RouteColorContrastValidator.java) is irrelevant. It doesn’t run, and I don’t need to even know about it.
- If I do have GTFS fields that are of the Color field type (e. g. route_color and route_text_color), and they are properly formatted, then either I do get the route_color_contrast notice, or I don’t. If I do, my dataset is violating a GTFS recommendation.
- Same situation than above, but my color fields are not properly formatted. Then I will get the invalid_color in my errors.
:warning: But I also want to know that if the route_color_contrast is not in my list of notices, it’s not because my data is good. My dataset might or might not violate this GTFS recommendation. This notice could be present, we can’t ensure that it’s not.

User should only see the list of validators that are relevant to their feed. For example, 

### Proposed solution

To do!

### Alternatives you've considered

- Related PR:  https://github.com/MobilityData/gtfs-validator/pull/1496

**Comment by qcdyx** [comment]
@isabelle-dr @emmambd Just ask for clarification, does this tool only log the name of the validators that couldn't run due to parsing problem which generates a CsvParsingFailedNotice?

**Comment by emmambd** [comment]
Hey @qcdyx! I'd recommend looking through the [closed issues in the parsing errors label for more context](https://github.com/MobilityData/gtfs-validator/issues?q=label%3A%22parsing+errors%22+is%3Aclosed). Particularly the PR @cka-y created here: https://github.com/MobilityData/gtfs-validator/pull/1526/files

**Comment by qcdyx** [comment]
Hey @isabelle-dr @emmambd could you provide some datasets that present the problem?

**Comment by qcdyx** [comment]
In which category would the validator generating route_color_contrast go for the two following use cases?
the data has routes.txt but no route_color
the data has routes.txt with route_color, although it’s not formatted properly
I suppose the feasibility depends on if we've been able to parse the components at all before the validation breaks...if we haven't, the user is essentially stuck with the full list to troubleshoot. (In this case, we could try to organize the error message into components so the user at least knows which validators to care about). Not sure how this works technically.
We have a route colors component, so
in scenario #1 - if we're able to evaluate that route colors component doesn't exist = route_color_contrast is in category #2.
in scenario #2, - if we're able to evaluate the route color does exist = route_color_contrast is in category #1

**Comment by qcdyx** [comment]
https://docs.google.com/spreadsheets/d/1iqvzJV_YWmFyYGtpbO2dqGMbf4XEjvar3rt9SxHU-xY/edit#gid=0
If GTFS component is not included, validation report should not be present to the users.

**Comment by bdferris-v2** [comment]
@qcdyx I'm not sure I understand your proposal here.  Based on your comment and what I also heard from Emma + Isabel, is your proposal to calculate the set of validators that did or did not run to compute a separate GTFS feed, validate that, and then compare the outputs?  This does not seem like a viable option to me.  I'm not sure why it's not more straightforward just to instrument the code to track what actually ran and what didn't for a single feed?

**Comment by qcdyx** [comment]
> @qcdyx I'm not sure I understand your proposal here. Based on your comment and what I also heard from Emma + Isabel, is your proposal to calculate the set of validators that did or did not run to compute a separate GTFS feed, validate that, and then compare the outputs? This does not seem like a viable option to me. I'm not sure why it's not more straightforward just to instrument the code to track what actually ran and what didn't for a single feed?

Hello @bdferris-v2 I go ahead with your proposal and added singleFileValidatorsWithParsingErrors and singleEntityValidatorsWithParsingErrors. The console output is changed to "Some validators were skipped because the GTFS files they rely on could not be parsed" and displays Multi-file validators, Single-file validators and Single-entity validators with parsing errors
