### ISSUE TITLE
Github action package_installers.yml fails

### ISSUE THREAD

**Issue by jcpitre** [MobilityData/gtfs-validator#1540]
### Describe the bug

See https://github.com/MobilityData/gtfs-validator/actions/runs/5603326832/attempts/1

The action fails with this in the logs:
```
Error: jdk.tools.jlink.plugin.PluginException: Duplicate resources: {lib/libj2gss.dylib=[java.security.jgss, java.security.sasl], bin/serialver=[jdk.crypto.cryptoki, jdk.crypto.ec], bin/jrunscript=[java.sql, java.security.jgss, java.transaction.xa, java.xml, java.security.sasl], lib/libosxkrb5.dylib=[java.security.jgss, java.security.sasl], conf/logging.properties=[java.sql, java.security.jgss, jdk.crypto.cryptoki, java.naming, java.logging, java.prefs, java.transaction.xa, java.xml, java.security.sasl, jdk.crypto.ec], lib/libj2pcsc.dylib=[java.sql, java.transaction.xa, java.xml], lib/libj2pkcs11.dylib=[jdk.crypto.cryptoki, jdk.crypto.ec], bin/javac=[jdk.crypto.cryptoki, jdk.crypto.ec]}


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:pkg:jlink'.
> Process 'command '/Users/runner/hostedtoolcache/Java_Zulu_jdk/17.0.8-7/x64/bin/jlink'' finished with non-zero exit value 1
```
I presume the installers are not built.

### Steps/Code to Reproduce

It can be reproduced on a local machine by installing java 17.0.8-zulu then running:
```
./gradlew :app:pkg:prepareModulesDir
./gradlew :app:pkg:jlink
```

If java 17.0.7-zulu is installed instead locally, there is no error.

The action downloads the latest version of zulu 17. I presume the latest version changed to 17.0.8 some time between the previous run of the github action (that was successful) and the run that failed.

### Expected Results

No error.

### Actual Results

Error

### Validator version

version 4.1.1-SNAPSHOT

### Operating system

irrelevant

**Comment by jcpitre** [comment]
I did not find anything related to that problem in the java release notes and in google in general.

Since it's pretty clear that java 17.0.8-zulu is the problem, as a workaround we should force usage of the 17.0.7-zulu version in the package_installers.yml github action

**Comment by cka-y** [comment]
Tasks:
- [ ] Investigate the problem including checking java version
- [ ] Add investigation results to story
- [ ] Fix
