### ISSUE TITLE
[REQUEST] Implement stop distance from trip shape verification (GTFS Rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#155]
**Is your feature request related to a problem? Please describe.**
A stop should not be too far away from its trip shape. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as  TYPE_STOP_TOO_FAR_FROM_SHAPE and TYPE_STOP_TOO_FAR_FROM_SHAPE_USING_USER_DISTANCE.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if a stop is not 1000m far away from its trip shape.

**Describe alternatives you've considered**

**Additional context**
Line 107 and 108 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by barbeau** [comment]
Looks like GTFS best practices are actually more strict than 1000m:
https://gtfs.org/best-practices/#shapestxt

>Route alignments (in shapes.txt) should be within 100 meters of stop locations which a trip serves.

**Comment by LeoFrachet** [comment]
hard

**Comment by fabrice-v** [comment]
Using a geospatial library

- for each trip
  - retrieve shape point collection from trip shape
  - pass collection to library with and expand parameter of 100m
  - retrieve an expanded shape
  - for each stop in trip, check if polygon contains the stop coordinates

**Comment by barbeau** [comment]
If you use spatial4j/JTS this is actually pretty straight-forward to implement. We implemented very a similar "is the vehicle position within X meters of the trip shape" in the GTFS-RT validator as part of rule ["E029 - Vehicle position far from trip shape"](https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/4070cbe50b0d69a27ae2506f1531ced2d37818c7/RULES.md#E029).

Basic logic:
1. Use spatial4j/JTS to buffer the trip shape line by X meters to create a polygon with an edge X meters from the line.
1. For each vehicle position, test if the position is contained within the polygon (also using spatial4j/JTS)

Here's the dependency:

```
        <!-- Spatial operations -->
        <dependency>
            <groupId>org.locationtech.spatial4j</groupId>
            <artifactId>spatial4j</artifactId>
            <version>0.6</version>
        </dependency>
        <dependency>
            <groupId>com.vividsolutions</groupId>
            <artifactId>jts</artifactId>
            <version>1.13</version>
        </dependency>
```

Pre-processing steps:
1. First we [build polylines](https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/validation/GtfsMetadata.java#L177) out of each trip shape.

In real-time:
1. For each vehicle position, we [check if the vehicle position is outside the trip shape buffer](https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/4070cbe50b0d69a27ae2506f1531ced2d37818c7/gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/validation/rules/VehicleValidator.java#L192).
    * There is a call to [`GtfsMetaData.getBufferedTripShape()`](https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/validation/GtfsMetadata.java#L377), which lazy-initializes the polygons by buffering the polylines. We lazy-initialized this for memory efficiency -  it's likely that only a small subset of GTFS trips will be active in real-time, so it doesn't make sense to create polygons for all GTFS trips up front. For this use case of the static validator, though, it may make sense to just go ahead and pre-process these if you know you're going to be checking all the GTFS trips anyway

**Comment by barbeau** [comment]
@fabrice-v I can work on this, given that I've already implemented a very similar version for the RT validator.

**Comment by lionel-nj** [comment]
Per discssion with @barbeau  and @timMillet:

This is linked to https://github.com/MobilityData/gtfs-validator/issues/357: if a stop is between 10m and 100m away from the trip shape it is related to -> this is an warning
If the stop is more than 100m away from the trip shape it is relate to -> this is an error.
