### ISSUE TITLE
Implement stop name and descriptions different for each stop (GTFS Rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#156]
**Is your feature request related to a problem? Please describe.**
Two stops should not have the same name and description. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as TYPE_STOP_WITH_SAME_NAME_AND_DESCRIPTION.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if stops names and descriptions are different for each one.

**Describe alternatives you've considered**

**Additional context**
Line 111 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by dudebrains01** [comment]
This rule should be modified: Two stops should not be in the same location (i.e. duplicated stops), but it is normal for multiple stops to have the same name (e.g. one stop on either side of the street).

**Comment by isabelle-dr** [comment]
Labeling as blocked because there is no mention of this check in the spec of best practices. 
The community asked for a check for a duplicated stop (same name, very close lat/long coordinates), which is a different check.

**Comment by emmambd** [comment]
@isabelle-dr Just to check my understanding, this notice is different than https://gtfs-validator.mobilitydata.org/rules.html#same_name_and_description_for_stop because it's checking that each stop name and description is unique across all stops, not just for 1 individual stop?

**Comment by emmambd** [comment]
Closed with [same_name_and_description_for_stop](https://gtfs-validator.mobilitydata.org/rules.html#same_name_and_description_for_stop)
