### ISSUE TITLE
Package installers CI step failing

### ISSUE THREAD

**Issue by davidgamez** [MobilityData/gtfs-validator#1567]
# Description

The package installer CI workflow is failing to start on Github actions. This seems to be related to GitHub actions that are not publicly accessible anymore. The list of inaccessible actions are: `devbotsxyz/import-signing-certificate`, `devbotsxyz/xcode-notarize` and `devbotsxyz/xcode-staple`.

Example of failing workflow: https://github.com/MobilityData/gtfs-validator/actions/runs/6114964556/job/16631408879?pr=1566

# Expected behavior

Package installers CI step executes successfully.

**Comment by bdferris-v2** [comment]
It's weird.  It looks like https://github.com/devbotsxyz/ deleted all their repos.
