### ISSUE TITLE
Jitpack packages should be generated at release time

### ISSUE THREAD

**Issue by jcpitre** [MobilityData/gtfs-validator#1585]
### Describe the problem

In https://github.com/MobilityData/gtfs-validator/issues/1473 there was a problem for jitpack to build release 4.1.0 of the validator jars.
We should make sure jitpack builds the jars properly as part of the release.

### Proposed solution

We need to have a dummy build with have this in build.gradle:

```
repositories {
   ...
    maven { url 'https://jitpack.io' }
    mavenCentral() // <2>
}

dependencies {
   ...
    implementation 'com.github.MobilityData:gtfs-validator:v4.1.0'
}
```
Adjust for the release tag (v4.1.0 in this case)
The project could have a simple "Hello World" java class. 

This dummy build has to be executed as part of the release, ideally from a Github action. 
Errors running the build should be reported and maybe block the release.

**Comment by emmambd** [comment]
Closing since jitpack has been replaced with Maven at #1596
