### ISSUE TITLE
Limit the number of shapes trip_distance_exceeds_shape_distance supports

### ISSUE THREAD

**Issue by davidgamez** [MobilityData/gtfs-validator#1589]
# Description

As part of the investigation of #1587, we came across a feed to ~40M of shapes to validate. The current validator's implementation needs to be optimized to handle large feeds; see #1358. The recently merged  #1553 introduced validation on shapes that expands resource usage on the validator. As a _temporary_ solution until #1358 provides a better way to manage large files, we propose limiting the number of the shapes that trip_distance_exceeds_shape_distance's validator supports.

Tasks:
- [ ] Investigate an approximate higher number of shapes that trip_distance_exceeds_shape_distance can support.
- [ ] Implement logic to skip the validator when the shape count is above the limit and log why the validator is being skipped.
- [ ] _Add the validator to the list of validators that didn't run due to limit_

**Comment by emmambd** [comment]
@cka-y It's this guy: https://storage.googleapis.com/storage/v1/b/mdb-latest/o/de-unknown-ulmer-eisenbahnfreunde-gtfs-1081.zip?alt=media

**Comment by cka-y** [comment]
From the `master` branch, here’s what I found regarding `TripAndShapeDistanceValidator` performance for the example feed:
- With the validator, validation takes about 199 seconds.
- Without it, it's around 183 seconds.

The difference is roughly 16 seconds, which seems reasonable for the volume of shapes (~40M) we're handling. This performance impact seems manageable. I believe we don’t currently have data on much larger sets of shapes, but so far, it doesn’t seem necessary to make further adjustments. 

Thoughts?

**Comment by emmambd** [comment]
Closing given there were significant improvements in the last pre release analytics: #1703
