### ISSUE TITLE
Implement transfer route and trip verification (GTFS rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#160]
**Is your feature request related to a problem? Please describe.**
A transfer should have valid route and trip. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as  TYPE_TRANSFER_WITH_INVALID_ROUTE_AND_TRIP.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies route and trip ids are not missing.

**Describe alternatives you've considered**

**Additional context**
Line 129 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by fabrice-v** [comment]
@lionel-nj , why TBD?

**Comment by dudebrains01** [comment]
Huh. This is a special case where the Google Validator was checking for validity for [Google GTFS extentions.](https://developers.google.com/transit/gtfs/reference/gtfs-extensions#TripToTripTransfers).

This rule can be abolished.

**Comment by bdferris-v2** [comment]
I believe this validation was actually implemented in PR #1267.
