### ISSUE TITLE
Display ERRORS first on validator documentation

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1605]
On the validator documentation, the order is currently: 
- WARNINGS
- ERRORS
- INFO

<img width="340" alt="Screenshot 2023-11-20 at 3 54 41 PM" src="https://github.com/MobilityData/gtfs-validator/assets/63653518/f4e7e709-b687-4b37-bc63-62c6373b1ffb">

We should modify it so that ERRORS appear first.

**Comment by davidgamez** [comment]
This seems to be related to the lack of sorting on the [rules.html page](https://github.com/MobilityData/gtfs-validator/blob/b01aff17594cd6e884c9fd5c76763c8ce462d1da/web/client/src/routes/rules.html/%2Bpage.svelte#L10) after a group by operation.
