### ISSUE TITLE
New validation rules for networks and route_networks

### ISSUE THREAD

**Issue by mobilitydataio** [MobilityData/gtfs-validator#1618]
# `Commit Nº 1`
## AUTHOR × DATE
* **Tzu-Jen Chan** ( _tzujenchanmbd_ )
* **November 28, 2023**   @   03:26 PM ETC (08:26 PM UTC)
## MESSAGE
```
[GTFS-Fares v2] Add networks.txt & route_networks.txt (#405)
* Add networks.txt & route_networks.txt
* Modify presence of routes.network_id
Changed to Conditionally Forbidden
* Modify fare_leg_rules.network_id
* Modify primary key of route_networks.txt
* Revise link
```
## FILES CHANGED
> ### https://github.com/google/transit/commit/ac95ec2cf9d64c50a354423090d8922a1fba635a

```
https://github.com/google/transit/commit/ac95ec2cf9d64c50a354423090d8922a1fba635a
```
---

New Rules for 

- ERROR: Forbid routes.network_id AND routes_networks.txt in the same dataset. (presence: Conditionally Forbidden). Includes routes.network_id as just a header.
- ERROR: Forbid routes.network_id AND networks.txt in the same dataset. (presence: Conditionally Forbidden). Includes routes.network_id as just a header.

- ERROR: 1 route_id can only be defined in 1 network_id. (1 route_id can't be associated with multiple network_ids).

Test feed from ITO World: https://docs.google.com/spreadsheets/d/1iyb8SCRxEXiK8-PHq0_Ut1_QUbeUEbQF6yZiA54WztU/edit#gid=628660671

**Comment by isabelle-dr** [comment]
Adding some examples of bad data

### Invalid data sample 1
routes.txt
route_id | route_name | network_id
-- | -- | --
1 | name1 | A
2 | name2 | A
3 | name3 | A
4 | name4 | A

networks.txt
network_id | network_name
-- | --
A | network_A

### Invalid data sample 2
routes.txt
route_id | route_name | network_id
-- | -- | --
1 | name1 | 
2 | name2 | 
3 | name3 | 
4 | name4 | 

networks.txt
network_id | network_name
-- | --
A | network_A

**Comment by tzujenchanmbd** [comment]
Adding some examples of **good** data.

### Valid data example 1
routes.txt
route_id | route_name | 
-- | -- | 
1 | name1 | 
2 | name2 | 
3 | name3 | 
4 | name4 | 

networks.txt
network_id | network_name
-- | --
A | network_A

route_networks.txt
network_id | route_id
-- | --
A | 1
A | 2
A | 3
A | 4

### Valid data example 2
routes.txt
route_id | route_name | network_id
-- | -- | --
1 | name1 | A
2 | name2 | A
3 | name3 | A
4 | name4 | A

**Comment by cka-y** [comment]
@isabelle-dr @tzujenchanmbd could you please specify what information you'd like to see in the report for each notice?

**Comment by emmambd** [comment]
@cka-y Let's start with: 

| Error  | Report table fields | 
|---|---|
|  ERROR: Forbid routes.network_id AND routes_networks.txt in the same dataset. (presence: Conditionally Forbidden). Includes routes.network_id as just a header. | networkIdA (from routes.txt), networkIdB (from route_networks.txt)   | 
| ERROR: Forbid routes.network_id AND networks.txt in the same dataset. (presence: Conditionally Forbidden). Includes routes.network_id as just a header. | networkIdA (from routes.txt), networkIdB (from networks.txt)    |  
| ERROR: 1 route_id can only be defined in 1 network_id. (1 route_id can't be associated with multiple network_ids).| routeId,  networkIdA, networkIdB
