### ISSUE TITLE
[REQUEST] Implement trip has time and is usable verification (GTFS rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#162]
**Is your feature request related to a problem? Please describe.**
A trip should have a beginning time and ending time, and be usable. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as TYPE_TRIP_WITH_NO_TIME_FOR_FIRST_STOP_TIME,  TYPE_TRIP_WITH_NO_TIME_FOR_LAST_STOP_TIME and TYPE_TRIP_WITH_NO_USABLE_STOPS.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if a trip has a time set for first stop time and last stop time, and that the trip is usable (more than 1 stop).
https://github.com/google/transitfeed/blob/master/transitfeed/schedule.py line 1298

**Describe alternatives you've considered**

**Additional context**
Line 136, 137 and 138 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by barbeau** [comment]
@maximearmstrong I'm not sure I understand TYPE_TRIP_WITH_NO_USABLE_STOPS here. Could you please explain that in more detail, and perhaps link to the Python code?

**Comment by maximearmstrong** [comment]
Sure, I added the link above. The trip must have a time for first stop, another one for last stop, and must have more than one stop to be usable.

**Comment by lionel-nj** [comment]
From my understanding, all `trips` should be refered to in table `StopTime`

https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/schedule.py#L1299

Am I correct to assume this @barbeau ?

**Comment by barbeau** [comment]
>From my understanding, all Trips should be referred to (at least once) in table StopTime
>
>https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/schedule.py#L1299 (line 1299)

Correct - looks like this is a warning in the Python validator:

```python
      if not count_stop_times:
        problems.OtherProblem('The trip with the trip_id "%s" doesn\'t have '
                              'any stop times defined.' % trip.trip_id,
                              type=problems_module.TYPE_WARNING)
```

>However, I am not sure of how to interpret this piece of code: https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/schedule.py#L1309 (from lines 1309 to 1312)

This code block:

```python
        if len(trip._headways) > 0:  # no stoptimes, but there are headways
          problems.OtherProblem('Frequencies defined, but no stop times given '
                                'in trip %s' % trip.trip_id,
                                type=problems_module.TYPE_ERROR)
```

...looks like it references frequencies.txt, based on https://github.com/google/transitfeed/blob/1c7f8c03612ac5c9c2b3f9a4cac6c229a04376b9/transitfeed/trip.py#L471:

```python
    self._headways.append((start_time, end_time, headway_secs, exact_times))
```

The way I read this is if a trip_id has a record in frequencies.txt but doesn't have any records in stop_times.txt then this is an error.

I'm not sure why one is considered an error and the other just a warning - I would consider them both errors.

Same with the following IF checking if a trip only has a single StopTime record:

```python
      elif count_stop_times == 1:
        problems.OtherProblem('The trip with the trip_id "%s" only has one '
                              'stop on it; it should have at least one more '
                              'stop so that the riders can leave!' %
                              trip.trip_id, type=problems_module.TYPE_WARNING)
```

I'd consider this an error too.

Thoughts from @timMillet are welcome!

**Comment by lionel-nj** [comment]
- [ ] verify all trips are referred to at least once in `stop_times.txt`
- [ ] verify each `stop_times.txt` contains at least two stops
- [x] verify first and last stop times have `start_time` and `end_time`: [E044](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#E044)

To be updated...
