### ISSUE TITLE
from_stop_id and to_stop_id not required for transfer_type 4 & 5

### ISSUE THREAD

**Issue by brodyFlannigan** [MobilityData/gtfs-validator#1621]
### Describe the bug

Hi!

The GTFS specification does not explicitly require that `from_stop_id` and `to_stop_id` be provided for records in `transfers.txt` with a `transfer_type` of `4` or `5`. However, the validator reports a `missing_required_field` error if these two fields are not provided. 

### Steps/Code to Reproduce

Using the online GTFS validator, validate this file:
[transcollines-qc-ca-fares-transfers.zip](https://github.com/MobilityData/gtfs-validator/files/13636130/transcollines-qc-ca-fares-transfers.zip)

(Ignore the other errors about translations and shape distances, those are known and being worked on)

### Expected Results

Validator should **not** report a `missing_required_field` error if `from_stop_id` and `to_stop_id` are not provided in `transfers.txt` if `transfer_type` = `4` or `5` 

### Actual Results

Validator returns a `missing_required_field` error if `from_stop_id` and `to_stop_id` are not provided in `transfers.txt` if `transfer_type` = `4` or `5`

### Files used

[transcollines-qc-ca-fares-transfers.zip](https://github.com/MobilityData/gtfs-validator/files/13636130/transcollines-qc-ca-fares-transfers.zip)

(Ignore other errors about translations and shape distances, those are known and are being worked on)

### Validator version

4.2.1-SNAPSHOT

### Operating system

(Web version of validator)

**Comment by davidgamez** [comment]
Hi @brodyFlannigan, thanks for your contribution. PR #1772 addresses this issue. There is also a great discussion (google/transit#455) regarding clarifying the rule in the spec. We plan to have this fix in the next release(date TBD, sometime this summer). Please feel free to look over the PR and add your comments.
