### ISSUE TITLE
Implement trip distance vs. shape verification (GTFS rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#163]
**Is your feature request related to a problem? Please describe.**
The distance traveled by a trip should be less or equal to the max length of its shape. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as TYPE_TRIP_WITH_OUT_OF_ORDER_SHAPE_DIST_TRAVELED.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if distance travelled is smaller than shape length. If not, generate an ERROR.

**Describe alternatives you've considered**

**Additional context**
Line 141 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by barbeau** [comment]
@maximearmstrong Could you point us to where this rule is implemented in the Python validator? I don't see it from a quick search.

**Comment by maximearmstrong** [comment]
@barbeau Here https://github.com/google/transitfeed/blob/master/transitfeed/trip.py#L644

**Comment by isabelle-dr** [comment]
Labeling as blocked because there is no mention of this in the spec or best practices

**Comment by isabelle-dr** [comment]
We have a PR open to add this to the spec: https://github.com/google/transit/pull/380, which would unblock this issue for the validator 🥳.
