### ISSUE TITLE
Feed generates error to authorize upload

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1632]
### Describe the bug

When using the feed URL https://www.maricopa-az.gov/home/showpublisheddocument/6491/638307291320330000, it generates an "Error authorizing upload". 

### Steps/Code to Reproduce

- Go to Web UI 
- Input https://www.maricopa-az.gov/home/showpublisheddocument/6491/638307291320330000 in "Or load from a URL" field 
- Validate feed 
- Generate "Error authorizing upload" error

### Expected Results

Feed generates report successfully. 

### Actual Results

<img width="641" alt="Screenshot 2023-12-19 at 5 58 48 AM" src="https://github.com/MobilityData/gtfs-validator/assets/90632321/19f917d6-e5c4-49b4-8d3d-53a72620d310">

### Validator version

4.2.0 

### Operating system

MacOS

**Comment by davidgamez** [comment]
Reopen this issue as it's also present while creating a job on the web validator.
