### ISSUE TITLE
Test setting threshold of 1.11m on equal_shape_dist_diff_coordinates

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1638]
### Describe the problem

There are recurring concerns that the [equal_shape_dist_diff_coordinates error is too sensitive](https://github.com/MobilityData/gtfs-validator/issues/1258) to very small differences between coordinate values. Upon looking at the history of the rule, it was originally proposed to [use 1.11m as a threshold between coordinates](https://github.com/MobilityData/gtfs-validator/pull/1083#issuecomment-1004250458). There was discussion to [set it as an ERROR above 1.11m and a WARNING below 1.11m](https://github.com/MobilityData/gtfs-validator/pull/1083#issuecomment-1010188909). At the time when we had fewer feeds in the Mobility Database, this seemed to have minimal value (e.g few feeds were impacted by the threshold change). Now that it's two years later, it's worth testing this with our current feed repository as a starting point to see how many feeds are impacted by it, and propose a more permissive threshold if needed. 

### Proposed solution

- Apply a 1.11m threshold to equal_shape_dist_diff_coordinates ERROR (>= 1.11m)
- Create a WARNING for equal_shape_dist_diff_coordinates( <1.11m)
- Re-run the acceptance tests to see how many feeds are impacted and what the difference is between coordinates for the feeds affected. 

### Alternatives you've considered

- [Defining a threshold based on analysis run on percentiles from the Mobility Database](https://github.com/MobilityData/gtfs-validator/issues/1258). Using 1.11m as a threshold seems like a good starting point to test the impact of values on the feeds.

### Additional context

Current rules that have set thresholds, to review logic: 

- [fast_travel_between_consecutive_stops](https://gtfs-validator.mobilitydata.org/rules.html#fast_travel_between_consecutive_stops-rule)
- [fast_travel_between_far_stops](https://gtfs-validator.mobilitydata.org/rules.html#fast_travel_between_far_stops-rule)
- [stop_too_far_from_shape](https://gtfs-validator.mobilitydata.org/rules.html#stop_too_far_from_shape-rule)

**Comment by emmambd** [comment]
Tasks: 

- [ ] Set threshold on rule 
- [ ] Review acceptance tests from PR

**Comment by cka-y** [comment]
[Here is the results from the acceptation tests ](https://github.com/MobilityData/gtfs-validator/files/14316222/acceptance_test_report.3.zip) -- 6% (92) dropped `ERROR` notices from #1675
