### ISSUE TITLE
Add remaining GTFS Features to the Validator

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1640]
### Describe the problem

The spec team at MobilityData has started to structure the spec into features (e.g Wheelchair Accessibility, Pathways) to 1) make it easier for newcomers to the spec to understand what use cases can be addressed with it and 2) make it easy for governments and operators to require specific features in contracts and regulatory requirements. 

[In progress spreadsheet here](https://docs.google.com/spreadsheets/d/1kpbKOzlHtsJIPo3B4ABYu-Nxwvqutjcdcvgpa0wZvtA/edit#gid=1997312156)

We started adding these to the validator metadata report so the community can see what features are in different feeds and to also help with our own internal analytics. The first iteration of this list tracks **the presence of features** in the feed, as in if there is 1 occurrence, we count it. 

Now that the list of features and its logic are almost finalized, we need to 1) add new features that are missing in the validator and 2) do some minor change of logic. 

### Proposed solution

[FeedMetadata](https://github.com/MobilityData/gtfs-validator/blob/master/main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java)

Logic should check values so there has to be 1 record (not just the column headers) for each feature

- [x] ~~Change Bikes Allowed = if at least 1 value of bikes_allowed in trips.txt defined. Remove check for values 2 or 3.~~ (already done) 
- [x] Change Zone-Based Fares = if 1 record in areas.txt
      - [MBTA: Example feed](https://cdn.mbta.com/MBTA_GTFS.zip)
- [x] Change name of Frequency-Based Trips feature to Frequencies
    - [Bullrunner: Example feed download link](https://github.com/CUTR-at-USF/bullrunner-gtfs-realtime-generator/blob/master/bullrunner-gtfs.zip)
- [x] Add Route-Based Fares = If at least 1 value of network_id in routes.txt defined OR 1 record in networks.txt
      - [MBTA: Example feed](https://cdn.mbta.com/MBTA_GTFS.zip)
- [x] Add Time-Based Fares = If 1 record in timeframes.txt
- [x] Add Transfer Fares = If 1 record in fare_transfer_rules.txt
      - [MBTA: Example feed](https://cdn.mbta.com/MBTA_GTFS.zip)
- [x] Add Pathways (extra) = If 1 occurrence of max_slope OR min_width OR length OR stair_count in pathways.txt
      - [MBTA: Example feed](https://cdn.mbta.com/MBTA_GTFS.zip)
- [x] Add Levels = If 1 record in levels.txt
      - [MBTA: Example feed](https://cdn.mbta.com/MBTA_GTFS.zip)

**Comment by qcdyx** [comment]
![image](https://github.com/MobilityData/gtfs-validator/assets/5789435/71dccf88-2029-4adb-b862-53a9246e5749)

**Comment by qcdyx** [comment]
![image](https://github.com/MobilityData/gtfs-validator/assets/5789435/4e4d5c5c-c6ca-42ca-ac8a-8b1eea96f73a)

**Comment by emmambd** [comment]
Re-opening for @qcdyx outstanding PR for Route-Based Fares
