### ISSUE TITLE
CLI and desktop versions not available for download

### ISSUE THREAD

**Issue by yashgt** [MobilityData/gtfs-validator#1641]
### Describe the problem

The documentation says , the CLI and desktop version can be downloaded. However, the release page does not have a download link.

**Comment by davidgamez** [comment]
Hi @yashgt, here is the GitHub release page with our latest release with all the downloadable links, including CLI and multiple OS desktop applications: https://github.com/MobilityData/gtfs-validator/releases/tag/v4.2.0.

**Comment by emmambd** [comment]
Hi @yashgt! Since @davidgamez answered your question, I'm going to close this issue. Feel free to open a new one if you run into another issue or need to clarify anything with the community.
