### ISSUE TITLE
[REQUEST] Implement service exists for a trip (GTFS rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#165]
**Is your feature request related to a problem? Please describe.**
A trip should be related to an existing service. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as  TYPE_TRIP_WITH_UNKNOWN_SERVICE_ID.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if service id exists in services list.

**Describe alternatives you've considered**

**Additional context**
Line 145 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by barbeau** [comment]
@timMillet This rule is actually directly related to a discussion we're having right now with GTFS ServiceChanges v3.1:
https://bit.ly/gtfs-service-changes-v3_1

The question is what's the best practice for including inactive service in static GTFS that could be activated later via real-time.

Looks like Google's current rule (as well as community Python validator) is that service_ids defined for trips must exist in calendar.txt or calendar_dates.txt.

**Comment by timMillet** [comment]
IMHO, `trips.service_id` that are not defined in `calendar.service_id` or `calendar_dates.service_id` should be flagged with a notice, like "Do you plan to trigger these service_ids with ServiceUdpates? If yes, ignore this message; if no, please resolve".

But if GTFS-ServiceUpdates within GTFS-ServiceChanges is not likely to be adopted anytime soon (in less than 1 year maybe?), maybe it would be worth to reject these values in the meantime. Idk how much it is on the dev side.

**Comment by barbeau** [comment]
For now I'd suggest that we stick with the existing Python validation rule - I think that should shape our solution in ServiceChanges, unless we have a good reason to go against it.
