### ISSUE TITLE
Web validator retries with bad zip file

### ISSUE THREAD

**Issue by jcpitre** [MobilityData/gtfs-validator#1651]
### Describe the bug

I fed a (really) bad zip file to the Web validator. The file is just a text file for which I changed the extension to .zip. 
After that I can see in the web validator logs ([here](https://console.cloud.google.com/run/detail/us-east1/gtfs-validator-web/logs?hl=en&project=web-based-gtfs-validator) You need access) that the validator failed with the data as expected but then reruns the validator multiple times. 
Which give the same results since it's the same input data. 

### Steps/Code to Reproduce

See above

### Expected Results

Some error message saying the file is no good and not do any retry with the same data.

### Actual Results

According to the logs the system is retrying with the same data a bunch of times. See screenshot

### Screenshots

Here are the logs with the retries:

![image](https://github.com/MobilityData/gtfs-validator/assets/106176106/815dab3a-13f2-4811-8739-9227d5585c8b)

### Validator version

4.2.0

### Operating system

irrelevant

**Comment by jcpitre** [comment]
A note about the logs:
Since the web validator can receive many requests at the same time, it's quite difficult in the logs to know which entry goes with which request.
The job id can be used for some logs.
Sometimes it's the thread name, but these are reused randomly.

We should some common string for all the logs related to a request so the logs can be easily filtered.

**Comment by davidgamez** [comment]
> A note about the logs: Since the web validator can receive many requests at the same time, it's quite difficult in the logs to know which entry goes with which request. The job id can be used for some logs. Sometimes it's the thread name, but these are reused randomly.
> 
> We should some common string for all the logs related to a request so the logs can be easily filtered.

We need to use a logger in the Spring web context that has access to the HTTP span and trace-id.

**Comment by davidgamez** [comment]
Tasks:
- Modify web validator cloud run retry policy. When the zip file is corrupted, don't retry.
- Test with valid and invalid zip files.

**Comment by qcdyx** [comment]
Based on my research, this bug is caused by an invalid condition of a while loop in the gtfs web validator. It keeps waiting until a report.html is generated. I'll share details in standup. @davidgamez

**Comment by emmambd** [comment]
Scope of this issue is to add the GCP logging - #1688 and #1689 created for the other tasks.
