### ISSUE TITLE
The gradle-wrapper.jar is not up-to-date with gradle version.

### ISSUE THREAD

**Issue by HappyHacker123** [MobilityData/gtfs-validator#1655]
### Describe the problem

Currently gtfs-validator is using gradle 7.4 as mentioned in gradle-wrapper.properties and the checksum of current wrapper.jar is 33ad4583fd7ee156f533778736fa1b4940bd83b433934d1cc4e9f608e99a6a89. However, as can be seen from official doc https://gradle.org/release-checksums/, the expected checksum of wrapper.jar 7.4 should be 575098db54a998ff1c6770b352c3b16766c09848bee7555dab09afc34e8cf590. The inconsistency means that the wrapper.jar is stale and should be updated.

# Possible Solution 

### Proposed solution

As mentioned in gradle official document https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper, you will need to run the wrapper task a second time to make sure the wrapper.jar is updated. You can run the below command in the root project. Automatically the wrapper scripts will be generated by gradle with corresponding version.
```
bash gradlew wrapper
```

**Comment by cka-y** [comment]
👋 @HappyHacker123! Thanks for highlighting the checksum mismatch with our `gradle-wrapper.jar`.  You're right -- this discrepancy suggests that our wrapper might be outdated or incorrectly set up. We will take a look ASAP! 

Feel free to open a PR if you'd like to jump in and help with the update. Your contributions are always welcome!

**Comment by qcdyx** [comment]
Hey @HappyHacker123 Thanks again for posting this issue. A fix is ready for review in this PR https://github.com/MobilityData/gtfs-validator/pull/1677.
