### ISSUE TITLE
Add documentation on logic for GTFS components

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1661]
### Describe the problem

As GTFS components evolve, we want to provide clear public documentation on how we're defining the "presence" of a GTFS component. This will help us make decisions in the future if we want more granular calculations (e.g tracking the actual usage of a component in the feed). [The code is here.](https://github.com/MobilityData/gtfs-validator/blob/master/main/src/main/java/org/mobilitydata/gtfsvalidator/report/model/FeedMetadata.java).

### Proposed solution

- A 2 column table where each component has its associated logic.

### Alternatives you've considered

- Programmatically generating this (may be too time consuming for the value at the moment)

**Comment by jcpitre** [comment]
Added a column in [this preadsheet](https://docs.google.com/spreadsheets/d/1kpbKOzlHtsJIPo3B4ABYu-Nxwvqutjcdcvgpa0wZvtA/edit#gid=1997312156)

I can make it into a user facing document after it's been reviewed.
