### ISSUE TITLE
Filter out acceptance tests from validator usage report

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1668]
### Describe the problem

As part of running analytics for #1520, we created a dashboard that displays how many times the validator is run for the website, CLI, and desktop app. The CLI number is artificially high because of the acceptance tests we run on each PR.

### Proposed solution

A method to filter out acceptance test runs from the usage report — potentially a parameter we add to ignore runs.

**Comment by davidgamez** [comment]
Tasks
- Add parameter to the CLI skip validator updates verification
- Modify acceptance tests
