### ISSUE TITLE
Table not properly rendered in notices 

### ISSUE THREAD

**Issue by jcpitre** [MobilityData/gtfs-validator#1672]
### Describe the bug

In the PR for #1624, @qcdyx  corrected a table used as an example for the route_long_name_contains_short_name notice so it was properly rendered in report.html.
@qcdyx noticed at that time that there was at least one another table not properly rendered https://github.com/MobilityData/gtfs-validator/issues/1624#issuecomment-1938910089

We should review tables and other text for all notices to make sure they are properly rendered.

List of notices: 

- duplicate_route_name [(test feed)](https://gtfs-validator-results.mobilitydata.org/ad21072b-2d2c-46ab-8e7b-d03bf452eb17/report.html)
- fast_travel_between_consecutive_stops [(test feed)](https://gtfs-validator-results.mobilitydata.org/abe93227-9cae-4f40-bf56-1bb6a9d91553/report.html)
- route_long_name_contains_short_name (SOLVED) 

### Steps/Code to Reproduce

If you look at the example report from #1624 (https://gtfs-validator-results.mobilitydata.org/c01332bb-3040-4f79-9bd4-48ea89925f54/report.html), you will notice that there is a table for notice fast_travel_between_consecutive_stops tht is not properly displayed.
![image](https://github.com/MobilityData/gtfs-validator/assets/106176106/d0db7e55-6b39-456b-a911-2261f5470021)

### Expected Results

A properly rendered table.

### Actual Results

See screenshot above

### Validator version

4.2.0

### Operating system

irrelevant

**Comment by davidgamez** [comment]
Tasks:
- Review table references on notices documentation
- Fix formatting in notices
- Test generated documentation on the report and the rules documentation(QA)
