### ISSUE TITLE
Changes to certain GTFS features

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1679]
After a final round of reviews, we have made the following changes to the GTFS feature mapping. See Sergio's comment below.

Acknowledging that this has already been added to the validator and might not be part of the next release.

Current validator implementation here: https://github.com/MobilityData/gtfs-validator/blob/master/docs/FEATURES.md

**Comment by emmambd** [comment]
As part of this issue, we should also link each individual feature in the HTML report to its associated feature heading in https://gtfs.org/getting_started/features/overview/. In the tooltip summary it should link to https://gtfs.org/getting_started/features/overview/

**Comment by Sergiodero** [comment]
I created a summary table with all the changes needed based on [this version of the features list](https://github.com/MobilityData/gtfs-validator/blob/master/docs/FEATURES.md) vs what we currently implemented in GTFS.org

For further reference check GTFS.org's [features page](https://gtfs.org/getting_started/features/overview/) and [this list](https://docs.google.com/spreadsheets/d/1kpbKOzlHtsJIPo3B4ABYu-Nxwvqutjcdcvgpa0wZvtA)

Feature group (old) | Feature name | Changes
-- | -- | --
Accessibility | Text-to-speech | N/A
Accessibility | Wheelchair accessibility | Split into two (also split corresponding rules):"Stops Wheelchair Accessibility" & "Trips Wheelchair Accessibility"
Accessibility | Route Colors | Classify under new group: Base add-ons
Accessibility | Bike Allowed | Classify under new group: Base add-ons
Accessibility | Translations | Classify under new group: Base add-ons
Accessibility | Headsigns | Classify under new group: Base add-ons
Fares | Fare Products | N/A
Fares | Fare Media | N/A
Fares | Route-Based Fares | N/A
Fares | Time-Based Fares | N/A
Fares | Zone-Based Fares | N/A
Fares | Transfer Fares | Renamed: “Fares Transfers”
Fares | Fares V1 | N/A
Pathways | Pathways (basic)* | Rename: “Pathway Connections”
Pathways | Pathways (extra)* | Rename: “Pathway Details”
Pathways | Levels | N/A
Pathways | In-station traversal time | N/A
Pathways | Pathways directions | Rename: “Pathway Signs”
Pathways | Location types | Classify under new group: Base add-ons
Metadata | Feed Information | Classify under new group: Base add-ons
Metadata | Attributions | Classify under new group: Base add-ons
Flexible Services | Continuous Stops | N/A
Shapes | Shapes | Classified under new group: Base add-ons
Transfers | Transfers | Classified under new group: Base add-ons
Frequency-based Services | Frequencies | Classified under new group: Base add-ons

Finally, just for visibility there are still 4 Features pending to be added as part of the [Flexible services](https://gtfs.org/getting_started/features/flexible_services/) group:

- Booking Rules
- Predefined Routes with Deviation
- Zone-based Demand Responsive Services
- Fixed-Stops Demand Responsive Services

**Comment by qcdyx** [comment]
Tasks:

- [ ] review the feature names table and apply the changes
- [ ] add tests
- [ ] ask spec team members to review the PR

**Comment by emmambd** [comment]
Added documentation links to HTML report as a task for this issue
