### ISSUE TITLE
[REQUEST] Implement agency email verification (GTFS rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#168]
**Is your feature request related to a problem? Please describe.**
An agency should have a valid email if it is defined. This is a GTFS rule implemented in Google Python validator as ValidateAgencyEmail.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if email field is empty. If not, verifies if email is valid with regex.

**Describe alternatives you've considered**

**Additional context**
Line 156 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by barbeau** [comment]
This deviates from the GTFS spec too - agency_email is optional in agency.txt:
https://gtfs.org/reference/static#agencytxt

So another potential candidate for configuration.

**Comment by maximearmstrong** [comment]
Rule implemented, emails (GTFS type) are now verified in PR #214
