### ISSUE TITLE
Acceptance test optimization

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1698]
We want to make this process less time-intensive. Suggestions so far: 

- [ ] Better document filtering 
- [x] Add performance analysis to the acceptance tests so we catch code changes with memory issues
- [x] Remove auto-run acceptance tests in draft mode
- [ ] Reuse acceptance test reports when _possible_. Make sure if the master artifacts are +30 days we run the validator.
- [x] Fix warnings in gh action

**Comment by emmambd** [comment]
@cka-y An out of scope question but asking since it's coming up as I'm reviewing Flex feeds: the performance test is about **the amount of time it takes to parse a feed**, correct? I'm wondering as well about getting stats on **the number of feeds that have unparsable rows grouped by file**

**Comment by cka-y** [comment]
It's about the amount of time it takes to validate the feed including parsing time. We could look into adding stats aboute the number of feeds with unparsable errors -- shall we open an issue for that?

**Comment by emmambd** [comment]
@cka-y Can do :) Out of scope for this iteration
