### ISSUE TITLE
Publish Validator Release 5.0 

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1702]
It's time for a new validator release!

To do:

- [x] Publish the release following the steps in [RELEASE.md](https://github.com/MobilityData/gtfs-validator/blob/master/docs/RELEASE.md) (Jean-Claude)
- [ ] Send the release e-mail to users that asked to be informed via e-mail (Emma)
- [ ] Blog post (Emma)

**Comment by jcpitre** [comment]
- I had to upload the installers zip files by hand as the GH action does not do it.
- I had to publish the jars be hand on the terminal since the publish_assets.yml GH action executed the publish seemingly successfully but nothing appeared in Sonatype.
