### ISSUE TITLE
[REQUEST] Implement frequency exact times verification (GTFS rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#173]
**Is your feature request related to a problem? Please describe.**
Frequency times should be exact times. This transfer should have a valid duration. This is a GTFS rule implemented in Google Python validator as ValidateExactTimes.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if time is equal to its casted integer form.
https://github.com/google/transitfeed/blob/master/transitfeed/frequency.py

**Describe alternatives you've considered**

**Additional context**
Line 162 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by barbeau** [comment]
@maximearmstrong Could you provide more implementation detail on this too, or link to Python code?

**Comment by maximearmstrong** [comment]
I added the link in the description.

**Comment by barbeau** [comment]
Oh, ok, thanks. So it's just verifying that frequencies.txt `exact_times` field is a `0` or `1` value, right?

**Comment by maximearmstrong** [comment]
Exactly
