### ISSUE TITLE
Modify Mobility Database workflow so when new validator version is released, run the validator on all latest datasets

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1746]
Modify [Mobility Database workflow](https://github.com/MobilityData/mobility-feed-api) so when new validator version is released, run the validator on all latest datasets

**Comment by cka-y** [comment]
Tasks:
- [ ] Create or reuse release action to trigger [http cloud function ](https://console.cloud.google.com/functions/details/northamerica-northeast1/update-validation-report?env=gen2&project=mobility-feeds-dev&tab=testing) [note: has to be after web validator is updated]
