### ISSUE TITLE
Flex: Add location group schema and update stop time schema

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1749]
### Describe the problem

We want to be able to support Flex as a part of #1721, we need to add a schema for the new file [location_groups.txt](https://gtfs.org/schedule/reference/#location_groupstxt) and [update the stop times schema](https://gtfs.org/schedule/reference/#stop_timestxt) to include new fields and modify stop_id from required to conditionally required.

### Proposed solution

New schema. Test by checking if:

- foreign_key_violation is triggered when location_group_id is defined in stop_times.txt but not in  location_groups.txt. Test with [modified-flex-feed-4226672-missing.zip](https://github.com/MobilityData/gtfs-validator/files/15266056/modified-flex-feed-4226672-missing.zip). I removed location_group_id 4226672 from location_groups.txt in https://data.trilliumtransit.com/gtfs/islandtransit-wa-us/islandtransit-wa-us--flex-v2-TEST.zip to test this.

- Check that missing_required_field no longer triggers when there's no stop_id in stop_times.txt AND a present `id` in `locations.geojson` OR `location_group_id` in `location_groups.txt`. Check with https://data.trilliumtransit.com/gtfs/islandtransit-wa-us/islandtransit-wa-us--flex-v2-TEST.zip

- Run performance tests on the implications of adding/checking additional fields in stop_times.txt 

- Update notice in #1810 to reflect requirements here for [`duplicate_geography_id`](https://docs.google.com/document/d/1QABoIeOdR6lAB7A6_X6WIbZwC7EnAIZvm_hRNwNQeoI/edit#heading=h.z8mjdmhjvvrb)

**Comment by cka-y** [comment]
Tasks:
- [ ] Add `location_groups.txt` schema
- [ ] Update `stop_times.txt` schema
  - [ ] Modify `stop_id` from required to conditionally required
  - [ ] Add `location_group_id`
  - [ ] Add `location_id`
  - [ ] Add `start_pickup_drop_off_window`
  - [ ] Add `end_pickup_drop_off_window`
  - [ ] Add `pickup_booking_rule_id`
  - [ ] Add `drop_off_booking_rule_id`
 - [ ] Add validation for the all the conditionally required fields (`stop_id`, `location_group_id`, `location_id`, `start_pickup_drop_off_window`, `end_pickup_drop_off_window`)
 - [ ] Unit tests

**Comment by cka-y** [comment]
Blocked until #1750 is completed

**Comment by emmambd** [comment]
As part of QA for this issue: 


Test #1776 and #1761
