### ISSUE TITLE
Flex: Add locations.geojson schema 

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1750]
### Describe the problem

We want to be able to support Flex as a part of https://github.com/MobilityData/gtfs-validator/issues/1721, we need to add a schema for the new file [locations.geojson](https://gtfs.org/schedule/reference/#locationsgeojson).

### Proposed solution

- New schema 
- Modify and test duplicate_key. Test with 
[duplicate-area-548-locations-geojson.zip](https://github.com/MobilityData/gtfs-validator/files/15266191/duplicate-area-548-locations-geojson.zip). Duplicated area_548 in https://data.trilliumtransit.com/gtfs/islandtransit-wa-us/islandtransit-wa-us--flex-v2-TEST.zip to test this. 
- Modify and test foreign_key_violation when location_id is defined in stop_times.txt but not in locations.geojson. Test with 
[foreign_key_violation_area_1137.zip](https://github.com/MobilityData/gtfs-validator/files/15275795/foreign_key_violation_area_1137.zip) to verify. 
- [Check if there are performance issues locally with the test feeds in the proposal document](https://docs.google.com/document/d/1QABoIeOdR6lAB7A6_X6WIbZwC7EnAIZvm_hRNwNQeoI/edit#heading=h.kub1orgyqh1t), to see if there are persistent issues with parsing failing for Flex data based on what was found in #1752 

- Special considerations given this is a geojson file when we only supported txt files before

**Comment by qcdyx** [comment]
Continues #1758 
How to setup gradle dependencies of GeoTools?
1. add the following dependencies into gtfs-validator/core/build.gradle
    implementation 'org.geotools:gt-main:31.2'
    implementation 'org.geotools:gt-shapefile:31.2'
    implementation 'org.geotools:gt-geojson:31.2'
    implementation 'org.geotools:gt-api:31.2'
    implementation 'org.locationtech.jts:jts-core:1.19.0'
2. add OGeo repository into the repositories block of gtfs-validator/build.gradle
        maven {
            url 'https://repo.osgeo.org/repository/release/'
        }
3. run ./gradlew build

**Comment by jcpitre** [comment]
Tasks:
- [ ] Read locations.geojson and extract tabular data (id, etc), provide sample validator and notice
- [ ] Add validators and notices minimum necessary to remove false positive #1749 #1797 
- [ ] Obtain geometry data and make overlap calculations
- [ ] Add other validators to fully support Flex
