### ISSUE TITLE
Flex: Update stop schema and add missing_stop_id rule

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1754]
### Describe the problem

In order to support Flex as a part of https://github.com/MobilityData/gtfs-validator/issues/1721, we need to 

1) modify the stop schema so stop_id is no longer a required field
2) add a new rule for missing_stop_id and checks for ids across stop_id, location_group_id, and locations.id

### Proposed solution

- Test to check that missing_required_field is no longer triggered when stop_id is not provided 
- Add new missing_stop_id rule. Test with [no-stop-id-for-trip-t_5735996_b_81516_tn_0.zip](https://github.com/MobilityData/gtfs-validator/files/15266279/no-stop-id-for-trip-t_5735996_b_81516_tn_0.zip)  I removed the stop_id associated with the trip_id t_5735996_b_81516_tn_0 in stop_times.txt from https://data.trilliumtransit.com/gtfs/islandtransit-wa-us/islandtransit-wa-us--flex-v2-TEST.zip to test this. 
- In depth review of acceptance test results, given the widespread implications of this change 

<table>
  <tr>
   <td><strong>File name</strong>
   </td>
   <td><strong>Spec language</strong>
   </td>
   <td><strong>Notice to update or add</strong>
   </td>
   <td><strong>Validator logic</strong>
   </td>
   <td><strong>Notice table columns</strong>
   </td>
  </tr>
  <tr>
   <td>stops.txt, location_groups.txt, locations.geojson
   </td>
   <td>In stops.txt:
<p>
stop_id 
<p>
<a href="https://github.com/google/transit/pull/433/files#diff-3ecf0760eb54b4953728042a1e30586705dc2335807be94faae0de5829cd12a1R203">ID must be unique across all `stops.stop_id`, locations.geojson `id`, and `location_groups.location_group_id` values.</a>
<p>
In stop_times.txt:
<p>
<a href="https://github.com/google/transit/pull/433/files#diff-3ecf0760eb54b4953728042a1e30586705dc2335807be94faae0de5829cd12a1R289">stop_id **Required** if `stop_times.location_group_id` AND `stop_times.location_id` are NOT defined.<br>- </a>
   </td>
   <td>New notice to address use case that was previously covered in missing_required_field:
<p>
missing_stop_id
   </td>
   <td>ERROR: 
Generate if there is no stop_id, location_group_id, OR location_id

<p><br>
Description should specify that the producer should add stop_id to stops.txt
   </td>
   <td>lineNumber and tripId
   </td>
  </tr>
</table>

### Additional context

This seems to be the most substantial change to the previous files and requirements of the spec from the new Flex changes. We're curious to hear from consumers about this modification and the work required for them to incorporate this change.

**Comment by davidgamez** [comment]
Tasks:
- [ ] Investigate if it's possible to keep the same missing required field notice in case of non-flex feeds

**Comment by emmambd** [comment]
After further clarification, this change is not required. `stop_id` is still required in all cases where `stops.txt` is still provided. The decision to define `stops.txt` as conditionally required is an ongoing discussion in the spec: https://github.com/google/transit/issues/452
