### ISSUE TITLE
Flex: Update missing_trip_edge rule to create exception 

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1755]
### Describe the problem

In order to support Flex as a part of https://github.com/MobilityData/gtfs-validator/issues/1721, we need to create an exception for the missing_trip_edge rule.

Depends on #1749 

### Proposed solution

- [ ] Add exception for missing_trip_edge rule:

<table>
  <tr>
   <td><strong>File name</strong>
   </td>
   <td><strong>Spec language</strong>
   </td>
   <td><strong>Notice to update or add</strong>
   </td>
   <td><strong>Validator logic</strong>
   </td>
   <td><strong>Notice table columns</strong>
   </td>
  </tr>
  <tr>
   <td>stop_times.txt
   </td>
   <td>arrival_time, departure_time
<p>
<a href="https://github.com/google/transit/pull/433/files#diff-3ecf0760eb54b4953728042a1e30586705dc2335807be94faae0de5829cd12a1R287">Forbidden** when `start_pickup_drop_off_window` or `end_pickup_drop_off_window` are defined.</a>
   </td>
   <td>missing_trip_edge
   </td>
   <td>If a trip has a start_pickup_dropoff_window or end_pickup_drop_off_window, do not trigger this error.
   </td>
   <td>
   </td>
  </tr>
</table>

Test with https://data.trilliumtransit.com/gtfs/islandtransit-wa-us/islandtransit-wa-us--flex-v2-TEST.zip to make sure the error is not triggered.

**Comment by qcdyx** [comment]
Tasks:

- [ ] add the logic to make sure this error doesn't get triggered for flex feeds
- [ ] add tests
- [ ] review acceptance tests
