### ISSUE TITLE
Explore running validation on feeds with unknown_column notices

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1770]
### Describe the problem

Investigation in #1767 showed that Flex feeds are not being parsed because they have the `unknown_column` notice. We want to be confident that this is the reason why Flex feeds are having parsing issues.

### Proposed solution

- Run analysis to see how many feeds in the acceptance tests have the `unknown column` notice (can use the Raw Data from the last analysis)

**Comment by jcpitre** [comment]
Tasks:

- [ ] Investigate why unknown column leads to unparsable
- [ ] Test by adding a column to a feed without errors and see what happens

**Comment by qcdyx** [comment]
1. It's the missing_required_field 'stop_id' that leads to a validation error, which makes stop_times.txt have a status of UNPARSABLE_ROWS.
2. added a 'UNKNOWN_COLUMN'  to stop_times.txt of browncounty-mn-us--flex-v2 dataset, run GTFS validator, no UNPARSABLE_ROWS for stop_times.txt.

**Comment by emmambd** [comment]
Closing this issue as a duplicate of #1767
