### ISSUE TITLE
Include a warning/update in the HTML report that Flex rules have not been added to the validator yet

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1778]
### Describe the problem

Some stakeholders have expressed confusion that they're getting invalid errors, because Flex rules have not been implemented in the validator yet. We should include a notice in the html reports that Flex rules are yet to be implemented. 

### Proposed solution

Display an alert in HTML validation report when any Flex feature is registered: 

- Booking Rules
- Predefined Routes with Deviation
- Zone-based Demand Responsive Services
- Fixed-Stops Demand Responsive Services

e.g "Not all GTFS-Flex validation rules have been added yet. This work is still in progress. [You can manually review all the validation rules for Flex data here](https://docs.google.com/document/d/1QABoIeOdR6lAB7A6_X6WIbZwC7EnAIZvm_hRNwNQeoI/edit#heading=h.mky28yjwt08z)."

Should display at the top of the page. Can use a similar style to the alerts on the Mobility Database, but in black and white: https://mobilitydatabase.org/feeds/mdb-934

**Comment by cka-y** [comment]
Needs #1844 to be merged since there were some changes in the features naming for flex features.

**Comment by qcdyx** [comment]
Clarification: @emmambd Shall we also add the alert on the Web UI?

Tasks:

- [ ] add the logic based on the proposed solution
- [ ] display the alert on the HTML report and the Web UI
- [ ] add tests

**Comment by cka-y** [comment]
@emmambd could you please validate that the requirements are:
- Add an indicator in the html report when flex features are detected
- Add a generic indicator in the web UI

**Comment by emmambd** [comment]
Just in the HTML report, please!
