### ISSUE TITLE
Backend services not validating dataset in staging environment

### ISSUE THREAD

**Issue by cka-y** [MobilityData/gtfs-validator#1782]
### Describe the bug

When using the backend services to validate a dataset in the staging environment, the validation process never completes. Additionally, the bucket ([stg-gtfs-validator-results](https://console.cloud.google.com/storage/browser/stg-gtfs-validator-results?project=web-based-gtfs-validator)) used to store the results remains completely empty, indicating that the bug has been present for some time or that all data in the bucket has been deleted.

Relates to https://github.com/MobilityData/mobility-feed-api/issues/491

### Steps/Code to Reproduce

1. Open the [web UI](https://gtfs-validator-staging.mobilitydata.org/).
1. Use the following URL to attempt validation: https://storage.googleapis.com/mobilitydata-datasets-prod/mdb-1/mdb-1-202406071555/mdb-1-202406071555.zip.
1. Initiate the validation process.

### Expected Results

The dataset should be validated successfully, and the results should be stored in the designated bucket and displayed in the UI.

### Actual Results

The validation process never completes, and the UI displays a loading indicator indefinitely. The designated bucket remains empty, with no validation results stored.

### Validator version

5.0.2-SNAPSHOT

### Operating system

MacOS

**Comment by davidgamez** [comment]
Closed by MobilityData/gtfs-infrastructure#4
