### ISSUE TITLE
Exit gates (pathway_mode=7) must not be bidirectional.

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1786]
### Describe the problem

The spec says in [pathways.is_bidirectional](is_bidirectional): 

> Exit gates (pathway_mode=7) must not be bidirectional.

I believe we don't have a validation rule for this currently. 

### Describe the new validation rule

Trigger an error if in pathways, there are records with `pathway_mode=7` and `is_bidirectional=1`

### Sample GTFS datasets

Here a modified dataset Berlin where in pathways, the first record should trigger the error. 
[Archive.zip](https://github.com/user-attachments/files/16281793/Archive.zip)

### Severity

ERROR

**Comment by Alessandro100** [comment]
Task
[] Add the rule
[] Unit tests
[] Validate acceptance tests

**Comment by qcdyx** [comment]
@emmambd what is the wording for this ERROR?

**Comment by emmambd** [comment]
@qcdyx `bidirectional_exit_gate`
