### ISSUE TITLE
[REQUEST] Implement schedule agencies ID verification (GTFS rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#179]
**Is your feature request related to a problem? Please describe.**
A schedule should not have IDless agencies, except if there's only a single agency defined. Agencies ID must be valid. This is a GTFS rule implemented in Google Python validator as ValidateIdlessAgency and ValidateRouteAgencyId.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : Verifies if an agency is IDless. An agency can be IDless only if a single agency is defined. Verifies if route agencies ID are valid (in agencies set).
https://github.com/google/transitfeed/blob/master/transitfeed/schedule.py line 1281

**Describe alternatives you've considered**

**Additional context**
Line 171 and 172 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by lionel-nj** [comment]
Implemented in https://github.com/MobilityData/gtfs-validator/pull/269

**Comment by fabrice-v** [comment]
@lionel-nj can that issue be closed? Let me know if that's NOT the case

**Comment by lionel-nj** [comment]
@fabrice-v This issue  can be closed., however verification of foreign key `agency_id` remains to do for GTFS `attributions.txt` and `fare_attributes.txt`. Keeping this issue opened as a reminder.

**Comment by lionel-nj** [comment]
Closing this issue

**Comment by lionel-nj** [comment]
Closing this issue, will backport implementation to check validity of fare_attributes.agency_id and `attributions.agency_id` in a future PR.
