### ISSUE TITLE
feed_info.txt should be added to missing_required_file when translations.txt exists

### ISSUE THREAD

**Issue by mobilitydataio** [MobilityData/gtfs-validator#1791]
# `Commit Nº 2`
## AUTHOR × DATE
* **isabelle-dr** ( _isabelle-dr_ )
* **July 18, 2024**   @   04:17 AM ETC (08:17 AM UTC)
## MESSAGE
```
Update requirement for feed_info.txt (#460)
* Update requirement for feed_info.txt
* Remove bold from Recommended
```
## FILES CHANGED
> ### https://github.com/google/transit/commit/cc60dc4275cc44662163efa8cefd3e9e5e504978

```
https://github.com/google/transit/commit/cc60dc4275cc44662163efa8cefd3e9e5e504978
```
---

**Comment by isabelle-dr** [comment]
@emmambd heads-up that there is also [#470](https://github.com/google/transit/commit/38a74f9a7a7bf1863c432f2d2d90cc164d430774), in this issue, where we've added:

> The shapes.txt file should be included for all route-based services (not for zone-based demand-responsive services).

To validate this automatically, we'd need to do: if the feed contains services other than zone-based DRT services, shapes.txt should be included.
cc @tzujenchanmbd

**Comment by emmambd** [comment]
@isabelle-dr Ah good catch! it didn't show up in the linked diff so I missed it :)

**Comment by Alessandro100** [comment]
Tasks
[] require feed_info.txt when translations.txt exists. Add conditional require to feed_info.txt
[] test it with feed id (to be provided)
[] review acceptance tests (if needed)

**Comment by qcdyx** [comment]
For clarification: 
The logic should be:
1. when translations.txt exists, if there's no feed_info.txt, create missing required file notice.
2. when there's no translation.txt, and no feed_info.txt either, create missing recommended file notice.
Correct? @emmambd

**Comment by emmambd** [comment]
@qcdyx You got it! We're modifying feed_info.txt to be conditionally required in cases where translations.txt exists
