### ISSUE TITLE
Prevent listing in web-validator public bucket

### ISSUE THREAD

**Issue by davidgamez** [MobilityData/gtfs-validator#1796]
### Describe the bug

As reported [here](https://mobilitydata-io.slack.com/archives/C03E10N96QL/p1722887095380469), the public GCP bucket allows listing. 

### Steps/Code to Reproduce

- Go to https://gtfs-validator-results.mobilitydata.org/ .

### Expected Results

- Listing operation should be blocked.

### Actual Results

- The XML listing content is returned

### Validator version

Web-validator(all versions)

### Operating system

Web

**Comment by qcdyx** [comment]
staging env - not publicly accesible
<img width="780" alt="image" src="https://github.com/user-attachments/assets/30cd25e5-0415-4a28-96ce-f16f7391ad0d">

**Comment by emmambd** [comment]
Just a thought - is it possible for us to include some kind of "error response" on this page, prompting users to go back to gtfs-validator.mobilitydata.org?

**Comment by davidgamez** [comment]
This fix intends to block the listing action but allow get actions. If the bucket is fully private, the app stops working. Currently, staging is returning 403 Forbidden when accessing files. 

https://github.com/user-attachments/assets/ffbdd60a-2fb0-45f1-afa3-df1657d35f7e

**Comment by emmambd** [comment]
@davidgamez So "success" is basically what @qcdyx's implemented, then? Is it possible to have a second issue for actually making this page descriptive?

**Comment by davidgamez** [comment]
> @davidgamez So "success" is basically what @qcdyx's implemented, then? Is it possible to have a second issue for actually making this page descriptive?

What is implemented in staging blocks users from using the web validator. We need to allow retrieval of files from the bucket and block just listing operations.

**Comment by qcdyx** [comment]
Hello @emmambd, @davidgamez and I created a new access role "Mobility Storage Get" in the stg-gtfs-validator-results GCP bucket. Could you try validating a GTFS file in staging https://gtfs-validator-staging.mobilitydata.org/? If it works, I'll apply the same change in prod.

**Comment by emmambd** [comment]
@qcdyx When I try to validate a feed on staging to generate the results page, the feed just never validates. 


![Image](https://github.com/user-attachments/assets/00b87fa3-88f4-4aca-9d44-188d25587580)

**Comment by davidgamez** [comment]
@emmambd Please try again; it should be OK now.

**Comment by emmambd** [comment]
Looks good to me! Access now denied without listing. 
<img width="931" alt="Screenshot 2024-08-21 at 2 19 35 PM" src="https://github.com/user-attachments/assets/a433abd1-a8f2-45e4-99c3-50fb3b032471">

**Comment by qcdyx** [comment]
Access denied without listing on Prod. Ready to be closed. <img width="510" alt="image" src="https://github.com/user-attachments/assets/2e2e9e7b-a6bc-4c61-8456-724540af141e">
