### ISSUE TITLE
Modify stops.txt to be conditionally required 

### ISSUE THREAD

**Issue by mobilitydataio** [MobilityData/gtfs-validator#1797]
# `Commit Nº 1`
## AUTHOR × DATE
* **Tzu-Jen Chan** ( _tzujenchanmbd_ )
* **August 7, 2024**   @   03:56 PM ETC (07:56 PM UTC)
## MESSAGE
```
Change stops.txt presence because of demand responsive services  (#472)
* Change stops.txt presence because of DRT
* change condition wording for stops.txt
```
## FILES CHANGED
> ### https://github.com/google/transit/commit/40800847529786577e5dae9382ff73764986eb16

```
https://github.com/google/transit/commit/40800847529786577e5dae9382ff73764986eb16
```
---

**Comment by emmambd** [comment]
Tasks: 

- [ ] Modify stops.txt annotation: from Required to Conditionally Required
- [ ] Add a new rule `missing_stops_file`, which should be generated in cases where there is no stops.txt, OR location_groups.txt OR locations.geojson. Description should specify that the producer should add stops.txt.

**Comment by emmambd** [comment]
Unblocked once #1750 is merged

**Comment by tzujenchanmbd** [comment]
Clarification on `missing_stops_file` rule:
The notice should be generated in cases where there is no `stops.txt` and `locations.geojson`. Not related to `location_groups.txt`.

**Comment by cka-y** [comment]
thanks @tzujenchanmbd for the clarification -- i updated the tasking to reflect that!
