### ISSUE TITLE
Flex: Add location group stops schema

### ISSUE THREAD

**Issue by jcpitre** [MobilityData/gtfs-validator#1811]
### Describe the problem

We want to be able to support Flex as a part of https://github.com/MobilityData/gtfs-validator/issues/1721, we need to add a schema for the new file [location_group_stops.txt](https://gtfs.org/documentation/schedule/reference/#location_group_stopstxt)

### Proposed solution

- New schema
- Make sure notices are created for foreign key references for location_group_id and stop_id (based on [reference document](https://gtfs.org/documentation/schedule/reference/#location_group_stopstxt))
- Also make sure the notices are created if required fields are missing

**Comment by emmambd** [comment]
Duplicate of #1749
