### ISSUE TITLE
Flex: invalid_prior_notice_duration_min

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1828]
### Describe the problem

See below

### Describe the new validation rule

[`invalid_prior_notice_duration_min` as defined in the table here](https://docs.google.com/document/d/1QABoIeOdR6lAB7A6_X6WIbZwC7EnAIZvm_hRNwNQeoI/edit#heading=h.fhjv4kui4obw)

### Severity

Error

**Comment by qcdyx** [comment]
Tasks:

- [ ] add logic to the forbidden_prior_day validator and add a new notice
- [ ] add tests
- [ ] review auto-generated documentation
- [ ] review acceptance tests
