### ISSUE TITLE
Flex: missing_prior_notice_duration_min

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1830]
### Describe the problem

See below

### Describe the new validation rule

[`missing_prior_notice_duration_min` as defined in the table here](https://docs.google.com/document/d/1QABoIeOdR6lAB7A6_X6WIbZwC7EnAIZvm_hRNwNQeoI/edit#heading=h.fhjv4kui4obw)

### Severity

Error

**Comment by qcdyx** [comment]
Tasks:

- [ ] implement the logics
- [ ] add unit test
- [ ] review documentation
- [ ] review the acceptance tests
