### ISSUE TITLE
Optimisation: Do not run validators on columns that are not present

### ISSUE THREAD

**Issue by jcpitre** [MobilityData/gtfs-validator#1839]
### Describe the problem

In #1749 we got to a point where one of the datasets was so big that we got out of memory issues and the time to run increased significantly.
We could check if a column exists in a file and not run validators related to that column.
In particular for foreign key validator, if the column that has the annotation does not exist, don't run the validator.
This could be useful in particular for stop_times, that usually has the most number of records and, with the addition of flex, has now 5 fields with the ForeignKey annotation.

Note:  #1747 tackles the same problem, but is much broader in scope.

### Proposed solution

See above
The exact mechanism TBD

**Comment by jcpitre** [comment]
[See here](https://docs.google.com/spreadsheets/d/e/2PACX-1vTH4WMg9vMiLyjtdcqj8V7GQD4cIbWTeYR5I5l5cNfUb2gKUa7bGVgx4NsHvX0bMWhqOi1HaPtfLHZs/pubhtml) for a sheet with all the validators we use.

- SingleEntityValidators:
   - For SingleEntityValidators, the validator is called for every entity in the table being processed. Not calling the validator could lead to significant time saving.
   - For generated validators:
      - Validators are generated when fields in the schema are annotated with:
         - MixedCase
         - EndRange
         - CurrencyAmount
         - LatLon
      - We do know which column need to be validated, because the columns are annotated in the schema (e.g. See MixedCase annotation in  [GtfsBookingRulesSchema.java](https://github.com/MobilityData/gtfs-validator/blob/f89774add7b7abf938f22df6f41d5ad2f1f2f61f/main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsBookingRulesSchema.java#L43C2-L50C27)). But we don't know if it's OK to not call the validator if the column is not present.
      - We could go on an annotation case by case basis. 
         - For example, for MixCase fields, it's OK not to call the validator, but all annotated columns have to be absent since the generated validators check all the MixCase annotated columns in one call of the validate method. For example, for [GtfsBookingRulesSchema.java](https://github.com/MobilityData/gtfs-validator/blob/f89774add7b7abf938f22df6f41d5ad2f1f2f61f/main/src/main/java/org/mobilitydata/gtfsvalidator/table/GtfsBookingRulesSchema.java#L43C2-L50C27) the validate method checks for MixedCase for the 3 fields (message, pickupMessage and dropOffMessage) in one sweep.
         - We would thus need specific code for MixedCase and the other generating annotations if applicable.
      - For custom validators (not generated) e.g.: [AttributionWithoutRoleValidator](https://github.com/MobilityData/gtfs-validator/blob/master/main/src/main/java/org/mobilitydata/gtfsvalidator/validator/AttributionWithoutRoleValidator.java)
         - We could add a parameter to the GtfsValidator annotation that would list the fields for which it's OK not to call the validator if the column is not present. 

- FileValidators
   - TDB

**Comment by davidgamez** [comment]
Thanks, @jcpitre; this is a very detailed proposal. I support the idea of implementing a _shouldCallValidate_. As this method depends on the information that the validator posses after its creation and not an specific row;  I suggest calling this method instead of before validating each row, before adding the validator to the executable validator list. This will reduce the amount of calls as will be one per file instead of one per row. In addition, we can have a report of the skipped validators due to missing columns similar to the one we have with the unparsable rows.
