### ISSUE TITLE
[BUG] Incorrect sample usage command line

### ISSUE THREAD

**Issue by cptCloud** [MobilityData/gtfs-validator#184]
**Describe the bug**
Input parameter given as sample usager in README.md should be with -i instead of -e

**To Reproduce**
java -jar gtfs-validator-v1.1.0.jar -u https://transitfeeds.com/p/mbta/64/latest/download -z input.zip -e input -o output

**Expected behavior**
java -jar gtfs-validator-v1.1.0.jar -u https://transitfeeds.com/p/mbta/64/latest/download -z input.zip -i input -o output

**Witnessed behavior**
<pre>Could not parse command line arguments: Unrecognized option: -e</pre>

**Screenshots**
N/A

**Environment used**
- OS: Ubuntu
- Java version: 11
 
**Additional context**
N/A

**Comment by fabrice-v** [comment]
Hi @cptCloud . The change was introduced recently https://github.com/MobilityData/gtfs-validator/commit/d55683b78aa905bf0b8ad186ae66a4483898928a via https://github.com/MobilityData/gtfs-validator/issues/114

If you are using the released version, please refer to the README corresponding to the same tag, for example
https://github.com/MobilityData/gtfs-validator/blob/v1.1.0/README.md
