### ISSUE TITLE
Validator Accepts Replacement Character in `stop_name` Field

### ISSUE THREAD

**Issue by YuliaTom** [MobilityData/gtfs-validator#1840]
### Describe the problem

Mobility Data Validator currently accepts the Unicode replacement character (`�`) in the `stop_name` field. This character typically indicates a decoding error and should not be present in valid data. While I've specifically noticed the acceptance of this replacement character, I am unsure if other similar problematic characters are also being accepted. Ideally, the validator should flag or reject `stop_name` fields containing the replacement character and potentially other similar invalid characters, as was done by the older GTFS validator, FeedValidator - https://github.com/google/transitfeed/tree/master, which raised a Unicode error (E33) for invalid values in the stop_name field. Implementing similar checks in future releases would help prevent data issues caused by improperly decoded or malformed input. Could this behavior be reviewed and corrected in future releases please? Thank you for your consideration and for your continued work on this project! 

### Describe the new validation rule

replacement_char = "\uFFFD"
if replacement_char in stop_name:
	trigger_error("invalid_character_in_stop_name", stop_name)

### Sample GTFS datasets

[auckland_gtfs.zip](https://github.com/user-attachments/files/16991535/auckland_gtfs.zip)

**Comment by emmambd** [comment]
Thanks for flagging this @YuliaTom! The fix for this will be part of our next release (you can see the change in #1892)

**Comment by YuliaTom** [comment]
Brilliant! Thank you very much for your work!

**Comment by qcdyx** [comment]
Hey @YuliaTom Glad to help! Thanks for catching the issue!
