### ISSUE TITLE
Modify stop_too_far_from_shape to only check stop_times.txt rows with stop_id

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1881]
### Describe the problem

Based on [this feed ](https://data.trilliumtransit.com/gtfs/garfieldcounty-wa-us/garfieldcounty-wa-us--flex-v2.zip  )and its [associated validation report](https://staging-gtfs-validator-results.mobilitydata.org/88aaebaa-d761-4936-8000-f9615552a5db/report.html), right now `stop_too_far_from_shape` is being triggered on stop times that don't have a stop_id. 

### Proposed solution

Modify `stop_too_far_from_shape` so it only checks stop times records that have a stop_id. It should ignore stop times that don't have a stop_id.

**Comment by tzujenchanmbd** [comment]
In other words - It ignores stop times that don't have a `stop_id`
