### ISSUE TITLE
Flex: create exception for decreasing_or_equal_stop_time_distance

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1882]
### Describe the problem

[Based on this old feed](https://data.trilliumtransit.com/gtfs/mountadams-wa-us/mountadams-wa-us.zip) and [its associated validation report,](https://staging-gtfs-validator-results.mobilitydata.org/6a9c405f-11ab-4824-9b3d-6d77fa39d13f/report.html), there are deviated routes for this agency, where drivers can deviate off a fixed route to a specific zone based on demand booking. 

In this feed, there are cases where [`decreasing_or_equal_stop_time_distance`](https://gtfs-validator.mobilitydata.org/rules.html#decreasing_or_equal_stop_time_distance-rule) is triggered on stop times with `location_id` or `location_group_id` rather than `stop_id`.

This is confusing, because the `stop_id` column will be null in this case. 

![Image](https://github.com/user-attachments/assets/388c7b19-7a4c-4b5d-a421-295f8a232acd)

### Proposed solution

Create an exception for rows where a `shape_dist_traveled` value is provided and has either an associated `location_id` or `location_group_id`. These rows should be omitted and will be covered in #1885 

Sample datasets: 

https://data.trilliumtransit.com/gtfs/mountadams-wa-us/mountadams-wa-us.zip
http://data.trilliumtransit.com/gtfs/thurston-wa-us/thurston-wa-us--flex-v2.zip

**Comment by davidgamez** [comment]
For clarification, should we ignore only the rows with location ID and location group ID or any trip with a row with this condition? 

For example:

Let's assume that all trip _1_ rows violate _decreasing_or_equal_stop_time_distance_.

`stop_times.txt`
| trip_id    | stop_id | location_id | location_group_id | ...other fields...
| -------- | ------- | ------- |------- |------- |
| 1  | stop_x  | | | | ...
| 1  | stop_1  | | | | ...
| 1  |  | location_1 | | | ...

In this case, should I expect **no notice** to be triggered or **one notice** for the second row and the third row to be ignored?

**Comment by tzujenchanmbd** [comment]
The latter one. We still want to trigger the notice for the second row.

**Comment by jcpitre** [comment]
I just added code for that as part of https://github.com/MobilityData/gtfs-validator/issues/1885

**Comment by davidgamez** [comment]
> I just added code for that as part of [#1885](https://github.com/MobilityData/gtfs-validator/issues/1885) See PR [#1896](https://github.com/MobilityData/gtfs-validator/pull/1896)

That was not part of #1885 scope ;-)

**Comment by jcpitre** [comment]
I know now. I did not realize.
