### ISSUE TITLE
Flex: modify stop_without_stop_time to exclude stops associated with a used location_group

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1883]
### Describe the problem

Based on the acceptance test changes from https://github.com/MobilityData/gtfs-validator/pull/1834#issuecomment-2346566136, there are changes in fixed stop demand responsive services where a stop_id will not be referenced explicitly in stop_times.txt and therefore would generate the `stop_without_stop_time` warning, even though the stop_id is technically used. 

### Proposed solution

Create an exception for this rule: 

If there's a location_group_id referenced in stop_times.txt, go through the original location_group file and check all the stops associated with that id. If a stop exists in the location_group that is being used in stop_times, don't trigger the warning.

**Comment by qcdyx** [comment]
stop_id can be referenced directly or indirectly
check if stop_id is referenced
if not, check if location_group_id is referenced
if stop is a part of location_group, it can be referenced
in one entry, you can reference only 1

**Comment by qcdyx** [comment]
Hey @emmambd could you provide a test feed please? I tried some datasets based on the comments https://github.com/MobilityData/gtfs-validator/pull/1834#issuecomment-2346566136, no luck.

**Comment by qcdyx** [comment]
@emmambd did you try using de-unknown-postauto-ag-gtfs-2053? https://opentransportdata.swiss/de/dataset/gtfsflex/permalink
