### ISSUE TITLE
[REQUEST] Implement start and end dates verification for a service period

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#191]
**Is your feature request related to a problem? Please describe.**
A service should have valid start and end dates. This is a GTFS rule implemented in Google Python validator as ValidateStartDate, ValidateEndDate and ValidateDate.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if a service start and end dates are not missing and valid (format).
https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/serviceperiod.py#L318

**Describe alternatives you've considered**

**Additional context**
Line 176, 177 and 179 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by lionel-nj** [comment]
Implemented in 5c68f8d4b2acc4f888e8f4a49d1d30db84dca849
