### ISSUE TITLE
[REQUEST] Implement shape ID verification

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#194]
**Is your feature request related to a problem? Please describe.**
A shape should have a shape ID. This is a GTFS rule implemented in Google Python validator as ValidateShapeID.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if shape ID is not missing.
https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/shape.py#L116

**Describe alternatives you've considered**

**Additional context**
Line 181 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by lionel-nj** [comment]
Implemented in https://github.com/MobilityData/gtfs-validator/pull/70
