### ISSUE TITLE
[REQUEST] Implement stop times arrival and departure seconds verification

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#198]
**Is your feature request related to a problem? Please describe.**
A stop time should have valid arrival and departure seconds (time from midnight). This is a GTFS rule implemented in Google Python validator as an inner verification in StopTimes __init__.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if arrival and departure seconds are not left blank and if are valid. Verifies if departure time is not before arrival time.
https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/stoptime.py#L81

**Describe alternatives you've considered**

**Additional context**
Line 186 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by barbeau** [comment]
Also note that values greater than 24:00:00 are allowed:
https://gtfs.org/reference/static#stop_timestxt

There are some other good rules related to the same fields in the same *init()* function.

**Comment by fabrice-v** [comment]
Possibly most or all those checks done in `StopTimeBuilder`
