### ISSUE TITLE
[REQUEST] Implement shape distance travelled verification

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#200]
**Is your feature request related to a problem? Please describe.**
The distance travelled in a shape at a stop should be valid. This is a GTFS rule implemented in Google Python validator as an inner verification in StopTimes __init__.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies is distance is a float.
https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/stoptime.py#L154

**Describe alternatives you've considered**

**Additional context**
Line 186 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by lionel-nj** [comment]
Implemented in https://github.com/MobilityData/gtfs-validator/pull/88
