### ISSUE TITLE
[REQUEST] Implement to and from stops verification for a transfer

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#201]
**Is your feature request related to a problem? Please describe.**
A transfer should have valid "to" stop and "from" stop IDs. This is a GTFS rule implemented in Google Python validator as ValidateFromStopIdIsPresent, ValidateToStopIdIsPresent, ValidateFromStopIdIsValid and ValidateToStopIdIsValid.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if both stop are valid (present in schedule stop keys) and not missing.
https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/transfer.py#L62

**Describe alternatives you've considered**

**Additional context**
Line 187, 188, 190 and 191 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by lionel-nj** [comment]
Implemented in b756eddb0c9831d195ce027333a5b6e6b5e73dd9
