### ISSUE TITLE
[REQUEST] Implement transfer type verification

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#202]
**Is your feature request related to a problem? Please describe.**
A transfer type should be valid if not empty. This is a GTFS rule implemented in Google Python validator as ValidateTransferType.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if transfer type is in range (0, 4) if not empty.
https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/transfer.py#L74

**Describe alternatives you've considered**

**Additional context**
Line 189 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by lionel-nj** [comment]
Implemented in b756eddb0c9831d195ce027333a5b6e6b5e73dd9
