### ISSUE TITLE
[REQUEST] Implement stop order verification for a trip

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#204]
**Is your feature request related to a problem? Please describe.**
A trip should have ordered stop/stop time and first stop time should not be none. This is a GTFS rule implemented in Google Python validator as an inner verification in AddStopTimeObject.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies each stop added are in order by verifying stops sequence.
https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/trip.py#L110

**Describe alternatives you've considered**

**Additional context**
Line 193 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by barbeau** [comment]
Similar to https://github.com/MobilityData/gtfs-validator/issues/193, note that the actual CSV file contents for any GTFS file aren't guaranteed to be in order by any field. I believe the Python tool sorts by `stop_sequence` and then applies the validation rules.

**Comment by LeoFrachet** [comment]
I think it is out of spec. @barbeau what do you think? If Google is enforcing it still day one it means we could add it to the spec.

**Comment by barbeau** [comment]
If we're saying that the CSV files needs to be sorted by stop_sequence, correct, it's out of spec. CSV contents aren't guaranteed to be ordered (and if Google's current internal validator in PartnerDash still enforces this, then yes, it could be added to the spec).

However, looking at the Python code at https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/trip.py#L143:

```python
      stoptime.stop_sequence = row[0] + 1
      prev_secs = max(row[1], row[2])
      if new_secs != None and new_secs < prev_secs:
        problems.OtherProblem(
            'out of order stop time for stop_id=%s trip_id=%s %s < %s' %
            (util.EncodeUnicode(stoptime.stop_id),
             util.EncodeUnicode(self.trip_id),
             util.FormatSecondsSinceMidnight(new_secs),
             util.FormatSecondsSinceMidnight(prev_secs)))
    self._AddStopTimeObjectUnordered(stoptime, schedule)
```

...it looks like this rule actually checks if the *times* are out of order. In other words, the trip shouldn't travel backwards in time as the vehicle progresses. This is in spec.

**Comment by barbeau** [comment]
@fabrice-v I removed the "out-of-spec" label - let me know if you disagree.

**Comment by barbeau** [comment]
This rule is also related to https://github.com/MobilityData/gtfs-validator/issues/212 - that issue specifically calls out "increasing time and distance". I'd need to review the Python code more to better understand the difference. Looks like the code linked to in https://github.com/MobilityData/gtfs-validator/issues/212 is related to timepoints and comparing sequential departure/arrival times?

**Comment by lionel-nj** [comment]
Our current implementation automatically orders `StopTime` entities by `stop_sequence` for a given `trip_id`.
Next step: check that times are in order for a given `StopTime` entity.

Note: as specified by @barbeau, the spec does not enforce ordering within a csv file, this verification will not (yet) implemented.

> If we're saying that the CSV files needs to be sorted by stop_sequence, correct, it's out of spec. CSV contents aren't guaranteed to be ordered (and if Google's current internal validator in PartnerDash still enforces this, then yes, it could be added to the spec).
> 
> However, looking at the Python code at https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/trip.py#L143:
> 
> ```python
>       stoptime.stop_sequence = row[0] + 1
>       prev_secs = max(row[1], row[2])
>       if new_secs != None and new_secs < prev_secs:
>         problems.OtherProblem(
>             'out of order stop time for stop_id=%s trip_id=%s %s < %s' %
>             (util.EncodeUnicode(stoptime.stop_id),
>              util.EncodeUnicode(self.trip_id),
>              util.FormatSecondsSinceMidnight(new_secs),
>              util.FormatSecondsSinceMidnight(prev_secs)))
>     self._AddStopTimeObjectUnordered(stoptime, schedule)
> ```
> 
> ...it looks like this rule actually checks if the _times_ are out of order. In other words, the trip shouldn't travel backwards in time as the vehicle progresses. This is in spec.

he times are out of order.

**Comment by lionel-nj** [comment]
@barbeau from my understanding the code linked to #212 checks:

-  if `arrival_time` > `departureTime` (which is already implemented in use case `ValidateStopTimeDepartureTimeAfterArrivalTime`
- distance increases along a trip (will chat about that rule when back @fabrice-v)

The piece of the python validator code linked to this issue (https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/trip.py#L144) checks: 
`departure_time` are in order for a sequence of `StopTime`.

**Comment by barbeau** [comment]
Close, I think - my read of https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/trip.py#L144 for this issue is that it's getting the arrival time for stop_time for stop N, and then comparing it against the max value of the arrival and departure time for the previous stop N - 1 to make sure it occurs later in time. Given that we're already checking if `arrival_time` > `departureTime` in a separate rule, then I believe this issue can be reduced to:

`IF arrival_time for stop[N] is < departure_time for stop[N - 1] THEN it's an error.`

You can't only compare sequential departure times because you'd miss this type of error:

|arrival time | departure time |
| --- | --- |
| 10:00  |   10:00 |
| 9:59    |  10:01 |
| 10:01  |  10:02 |

I think the other distinction between this issue and #212 [Python code](https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/trip.py#L595) is that #212 seems to be checking only timepoint values - although off the top of my head timepoints should be a subset of all stop_times.txt data, so I'm not sure why they would be checked for the exact same time travel logic separately...

**Comment by lionel-nj** [comment]
Oh true, good catch!
