### ISSUE TITLE
[REQUEST] Implement trip frequency verification 

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#206]
**Is your feature request related to a problem? Please describe.**
A trip should have frequencies with valid start and end times, valid headway seconds and exact times. This is a GTFS rule implemented in Google Python validator as an inner verification in AddFrequency.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if start and ends times are not missing and valid (format), verifies if headway seconds is not missing and an integer greater than zero. Verifies start and end times order. Verifies that exact times should be set to 0 or 1.
https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/trip.py#L403

**Describe alternatives you've considered**

**Additional context**
Line 196 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by lionel-nj** [comment]
- `frequencies.start_time` checked in https://github.com/MobilityData/gtfs-validator/pull/83
- `frequencies.end_time` checked in https://github.com/MobilityData/gtfs-validator/pull/83
- `1>=frequencies.headway_secs=>0` checked in https://github.com/MobilityData/gtfs-validator/pull/83

**Comment by lionel-nj** [comment]
Use case `ValidateFrequenciesStartTimeBeforeEndTime` upcoming.
