### ISSUE TITLE
[REQUEST] Implement bikes allowed in a trip verification 

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#210]
**Is your feature request related to a problem? Please describe.**
Bike allowance in a trip should be indicated. This is a GTFS rule implemented in Google Python validator as ValidateBikesAllowed.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if bike allowance is set to yes, no or unknown.
https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/trip.py#L542

**Describe alternatives you've considered**

**Additional context**
Line 200 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by lionel-nj** [comment]
Implemented in 40c56bfeb98d0e168b0d7101cb94b439e699231a
