### ISSUE TITLE
[REQUEST] Implement CSV file is not empty (CSV rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#213]
**Is your feature request related to a problem? Please describe.**
A CSV file should not be empty. This is a CSV rule implemented in Google Python validator raising an EmptyFile error.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Line 204 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by dudebrains01** [comment]
This rule is meant to flag completely empty CSV files, where no headers are provided. This is **invalid** and constitutes an **error** ([spec here](https://github.com/MobilityData/transit/blob/master/gtfs/spec/en/reference.md#file-requirements))

Many feeds have CSV files with headers but no data. This is **valid**. (For example see [frequencies.txt for Transcollines](http://transitfeeds.com/p/transcollines/1275/latest/file/frequencies.txt))
