### ISSUE TITLE
[REQUEST] Add command-line execution to CI builds

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-validator#221]
**Is your feature request related to a problem? Please describe.**
There have been a few issues (most recently https://github.com/MobilityData/gtfs-validator/issues/218) where changes that have passed CI and been merged have broken runtime execution.

**Describe the solution you'd like**
IMHO, it would be a good idea to add command-line execution on at least a small real-world GTFS dataset as part of CI to test end-to-end execution prior to merging PRs.

For example, we could add a few lines to the [GitHub CI config](https://github.com/MobilityData/gtfs-validator/blob/master/.github/workflows/gradle.yml) to download an archived GTFS dataset from a fixed time (e.g., MBTA at https://transitfeeds.com/p/mbta/64/20200521) and execute the basic validation against the set. I'm not sure what the current validation time against MBTA GTFS, so if that's too long we could choose a smaller dataset.

If this is implemented, the return code of the app would need to be tested to ensure that a crashing app actually fails the CI build - see https://stackoverflow.com/a/6775860/937715.

**Describe alternatives you've considered**

1. Do nothing
1. Add more integration tests

**Comment by fabrice-v** [comment]
Excellent point. The execution time on MTBA right now is around 30s on my local machine, give or take. Is that reasonable? That would also give us a gross idea of our performance.
I'm a bit confused by the linked information, does that mean we have to explicitely return 0 at the end of our main? My understanding from the error messages in intelliJ is that a code different from 0 was returned when it errored, but maybe that's because it's run into the IntelliJ environment.

**Comment by barbeau** [comment]
@fabrice-v I would say let's try with MBA GTFS and see how long it takes on CI. CI execution will likely be significantly slower than your machine. Although still probably faster than running Android tests on an emulator on CI 😛.

>My understanding from the error messages in intelliJ is that a code different from 0 was returned when it errored, but maybe that's because it's run into the IntelliJ environment.

Yes, sorry, I should of been clearer. My understanding is the same as yours - standard behavior is that if the Java app crashes on CI then a non-zero return code is returned, and the CI should fail. But we should still test to make sure. One easy way to test is after the CI is configured, branch off the commit that causes the existing runtime failure, and another minor change to a file, and open a PR. It should still crash and hopefully CI would fail.

**Comment by barbeau** [comment]
WIP PR at https://github.com/MobilityData/gtfs-validator/pull/253.
