### ISSUE TITLE
Ensure consistency regarding nullability annotations

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#226]
**Is your feature request related to a problem? Please describe.**
GTFS entities PR regularly involve nullability annotations. However, their use is not consistent from an entity to another one.

**Describe the solution you'd like**
Annotations should be used for entity class fields, and constructor, before entity method declarations, but also for entity builder methods parameters.

**Additional context**

- [x] agency.txt
- [x] routes.txt
- [x] trips.txt -> e23f7d8945f9365e6d547bbeb29733874f7a45b6
- [x] calendar.txt -> ab7bd7d292efb18a502c3ce6eba79a0ca2c6e75e
- [x] feed_info.txt -> 29842148fc790656f291924ea63c14660b8007a3
- [x] calendar_dates.txt -> bf3df779704f5516282f9c498e5f14c9fcfc0441
- [ ] [shapes.txt](https://github.com/MobilityData/gtfs-validator/pull/70)
- [x] transfers.txt -> d9f5002ddae18a19f4010ab26d54be49a2da8a30
- [x] pathways.txt -> 09900015f9cf5a881846ddfa4eb05ac3bcc0a805
- [x] levels.txt -> 271de2f632790282221fa0f83371894492dddc34
- [x] fare_attributes.txt -> 00d140f397de8f1dd4df029987848c4085507a14
- [x] fare_rules.txt -> 80384526ff4c7cb0487dd989edc1bd603cfc7deb
- [x] attributions.txt -> ec52f4a9d1a5aa9f47d0c4a7713f5f25fc2c0274

**Comment by barbeau** [comment]
Closing, outdated with new v2 architecture
