### ISSUE TITLE
[REQUEST] Implement unique Stop ID verification (GTFS Rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#230]
**Is your feature request related to a problem? Please describe.**
Every Stop ID should be unique in stops.txt.

**Describe the solution you'd like**
Verify a Stop ID is not duplicated in stops.txt

**Describe alternatives you've considered**

**Additional context**
GTFS Spec http://gtfs.org/reference/static/#stopstxt

**Comment by fabrice-v** [comment]
Done in Stop class builder
