### ISSUE TITLE
[REQUEST] Implement unique Route ID verification (GTFS Rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#231]
**Is your feature request related to a problem? Please describe.**
Every Route ID should be unique in routes.txt.

**Describe the solution you'd like**
Verify a Route ID is not duplicated in routes.txt

**Describe alternatives you've considered**

**Additional context**
GTFS Spec http://gtfs.org/reference/static/#routestxt

**Comment by lionel-nj** [comment]
Implemented in https://github.com/MobilityData/gtfs-validator/pull/57
