### ISSUE TITLE
[REQUEST] Implement unique Trip ID verification (GTFS Rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#232]
**Is your feature request related to a problem? Please describe.**
Every Trip ID should be unique in trips.txt.

**Describe the solution you'd like**
Verify a Trip ID is not duplicated in trips.txt

**Describe alternatives you've considered**

**Additional context**
GTFS Spec http://gtfs.org/reference/static/#tripstxt

**Comment by lionel-nj** [comment]
Implemented in https://github.com/MobilityData/gtfs-validator/pull/59
