### ISSUE TITLE
[REQUEST] Implement unique Service ID verification (GTFS Rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#233]
**Is your feature request related to a problem? Please describe.**
Every Service ID should be unique in calendar.txt.

**Describe the solution you'd like**
Verify a Service ID is not duplicated in calendar.txt

**Describe alternatives you've considered**

**Additional context**
GTFS Spec http://gtfs.org/reference/static/#calendartxt

**Comment by lionel-nj** [comment]
Implemented in https://github.com/MobilityData/gtfs-validator/pull/82
