### ISSUE TITLE
[REQUEST] Implement unique Service ID and Date pair in calendar_dates.txt (GTFS Rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#234]
**Is your feature request related to a problem? Please describe.**
Every Service ID and Date pair should be unique in calendar_dates.txt.

**Describe the solution you'd like**
Verify a Service ID and Date pair is not duplicated in calendar_dates.txt

**Describe alternatives you've considered**

**Additional context**
GTFS Spec http://gtfs.org/reference/static/#calendar_datestxt

**Comment by lionel-nj** [comment]
Implemented in https://github.com/MobilityData/gtfs-validator/pull/84
