### ISSUE TITLE
[REQUEST] Implement unique Fare ID verification (GTFS Rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#235]
**Is your feature request related to a problem? Please describe.**
Every Fare ID should be unique in fare_attributes.txt.

**Describe the solution you'd like**
Verify a Fare ID is not duplicated in fare_attributes.txt

**Describe alternatives you've considered**

**Additional context**
GTFS Spec http://gtfs.org/reference/static/#fare_attributestxt

**Comment by lionel-nj** [comment]
Implemented in https://github.com/MobilityData/gtfs-validator/pull/120
