### ISSUE TITLE
[REQUEST] Implement unique Shape ID verification (GTFS Rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#238]
**Is your feature request related to a problem? Please describe.**
Every Shape ID should be unique in shapes.txt.

**Describe the solution you'd like**
Verify a Shape ID is not duplicated in shapes.txt

**Describe alternatives you've considered**

**Additional context**
GTFS Spec http://gtfs.org/reference/static/#shapestxt

**Comment by barbeau** [comment]
This rule actually isn't possible - `shapes.txt` is unique from other tables in that the ID field isn't a primary key, but a foreign key to `trips.txt`. `trips.txt` just contains a `shape_id` for the trip, and all records in `shapes.txt` matching that ID define the shape. The data looks like:

~~~
shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence
A_shp,37.61956,-122.48161,0
A_shp,37.64430,-122.41070,6
A_shp,37.65863,-122.30839,11
~~~

**Comment by maximearmstrong** [comment]
@barbeau thanks for the info! I did not know that.
