### ISSUE TITLE
[REQUEST] Implement default colors for Route

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#239]
**Is your feature request related to a problem? Please describe.**
Route color must default to white (FFFFFF) when field is left empty.
Route text color must default to black (000000) when field is left empty.

**Describe the solution you'd like**
Defaults should be set when Route builds.

**Describe alternatives you've considered**

**Additional context**
GTFS Spec http://gtfs.org/reference/static/#routestxt

**Comment by barbeau** [comment]
@maximearmstrong Is this to help test for contrast when only one of the two color fields is provided?

For any GTFS field, I think it's useful to be able to understand when the producer provided a value, and when they did not. I'd be a little concerned if we lose the ability to distinguish between this in the internal data model.

**Comment by maximearmstrong** [comment]
@barbeau I think it is to help for the contrast, yes. This rule was taken directly from the [GTFS spec for routes.txt](http://gtfs.org/reference/static/#routestxt).
Should we implement it?

**Comment by barbeau** [comment]
So there are two topics here:
1. How we interpret empty default color fields when using them in general validation
1. How we store data internally for the case when the GTFS field was empty

Looking at [ValidateRouteColorAndTextContrast](https://github.com/MobilityData/gtfs-validator/blob/82888de0c32ef0a5437d09c4db2246a49b9a3c25/usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateRouteColorAndTextContrast.java), for (1) above if the field is

For (2) - IMHO when parsing the data from GTFS into the `Route` object we shouldn't populate it with the default value if the producer didn't provide the field. Instead, we should leave the field as null and then in the rule check if the value is null, and if so then use the default value in the rule implementation. This way we keep the knowledge in the data model that the producer didn't provide any value for this field, which can be useful for other rules.

**Comment by lionel-nj** [comment]
Per discussion, this will not be implemented: the interpretation of `routes.route_color` would not te straighforward.
