### ISSUE TITLE
[REQUEST] Implement semantic verification of fields route_sort_order in routes.txt

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#241]
**Is your feature request related to a problem? Please describe.**
This numeric fields should be user configurable so that suspicious values can be reported.

**Describe the solution you'd like**

- [x] Add new Warning notice:
  - `SuspiciousRouteSortOrderNotice`

- [x] Add support to provide thresholds for this field via configuration file and/or command line

- [ ] Determine default values for said thresholds

**Comment by barbeau** [comment]
Not sure how route_sort_order could be suspicious? It's just a integer for ordering records.

**Comment by lionel-nj** [comment]
We could imagine that for an agency managing 300 routes, having a route with field `route_sort_order` equal to 6000 would be suspicious.

**Comment by barbeau** [comment]
Yes, I guess so. I guess I'm just used to seeing people use somewhat arbitrary integers for ordering. I also haven't seen this field much myself in practice - I'd be interested in seeing actual values used in practice.
