### ISSUE TITLE
[REQUEST] Implement semantic verification of field shape_dist_traveled in stop_times.txt

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#242]
**Is your feature request related to a problem? Please describe.**
This numeric field should be user configurable so that suspicious values can be reported.

**Describe the solution you'd like**

- [ ] Add new Warning notices:
  - `SuspiciousShapeDistTraveledNotice`

- [ ] Add support to provide thresholds for this field via configuration file and/or command line

- [ ] Determine default values for said thresholds

**Comment by barbeau** [comment]
Same here - I don't think stop_sequence can be suspicious. It's either a unique integer for a given trip_id or it's not (which would be an error).

**Comment by lionel-nj** [comment]
True, editing this issue accordingly

**Comment by lionel-nj** [comment]
Duplicated in https://github.com/MobilityData/gtfs-validator/issues/164
