### ISSUE TITLE
[REQUEST] Implement semantic verification of fields shape_pt_lat, shape_pt_lon and shape_dist_traveled in shapes.txt

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#244]
**Is your feature request related to a problem? Please describe.**
These numeric fields should be user configurable so that suspicious values can be reported.

**Describe the solution you'd like**

- [ ] Add new Warning notice:
  - `SuspiciousShapePtLatNotice`
  - `SuspiciousShapePtLonNotice`
  - `SuspiciousShapePtSequenceNotice`
  - `SuspiciousShapeDistTraveledNotice`

- [ ] Add support to provide thresholds for these fields values via configuration file and/or command line

- [ ] Determine default values for said thresholds

**Comment by barbeau** [comment]
I don't think `shape_pt_sequence` can really be suspicious - it's either a valid unique ID for a given shape_id or it's not (which would be an error).

**Comment by lionel-nj** [comment]
Good point. Plus, this one can be touchy depending on the resolution of shapes. Editing this issue accordingly.

**Comment by lionel-nj** [comment]
No semantic validation of fiels yet, per discussion.
