### ISSUE TITLE
[REQUEST] Implement semantic verification of field min_transfer_time in transfers.txt

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#246]
**Is your feature request related to a problem? Please describe.**
This numeric field should be user configurable so that suspicious values can be reported.

**Describe the solution you'd like**

- [ ] Add new Warning notice:
  - `SuspiciousMinTransferTime`

- [ ] Add support to provide thresholds for this field via configuration file and/or command line

- [ ] Determine default values for said thresholds

**Comment by barbeau** [comment]
@maximearmstrong IIRC the Python validator had a threshold for min_transfer_time?

**Comment by lionel-nj** [comment]
Closing this. Duplicated in https://github.com/MobilityData/gtfs-validator/issues/159
