### ISSUE TITLE
Implement semantic verification of fields length, traversal_time, stair_count, max_slope, min_width, 

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#247]
**Is your feature request related to a problem? Please describe.**
These numeric fields should be user configurable so that suspicious values can be reported.

**Describe the solution you'd like**

- [ ] Add new Warning notice:
  - `SuspiciousPathwayLengthNotice`
  - `SuspiciousPathwayTraversalTimeNotice`
  - `SuspiciousPathwayStairCountNotice`
  - `SuspiciousPathwayMaxSlopeNotice`
  - `SuspiciousPathwayMinWidthNotice`

- [ ] Add support to provide thresholds for these fields values via configuration file and/or command line

- [ ] Determine default values for said thresholds

**Comment by barbeau** [comment]
Closing, we're not implementing thresholds at this time
