### ISSUE TITLE
NPE is thrown when executing use case ValidateRouteLongNameDoesNotContainOrEqualShortName

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#249]
**Describe the bug**
When running the validator on the dataset from MBTA, a NPE is thrown 

**To Reproduce**
Steps to reproduce the behavior, including input data sample if applicable:

Run validator with the following configuration : 
`-u https://transitfeeds.com/p/mbta/64/latest/download -z input.zip -e input -o output`

**Expected behavior**
Dataset should be validated, without throwing NPE

**Witnessed behavior**
Method .contains is applied on `null` parameter. The filter on route should be extended to routes with non-null route_short_name.

**Screenshots**
<img width="1284" alt="Capture d’écran, le 2020-06-05 à 11 25 18" src="https://user-images.githubusercontent.com/35747326/83894625-86771f80-a71f-11ea-8426-68be80947b41.png">

**Environment used**
- OS: macOS Catalina
- Java version: javac 11.0.5

**Comment by barbeau** [comment]
Closing, outdated with v2 architecture
