### ISSUE TITLE
Fine tune threshold value for GTFS time type validation warning

### ISSUE THREAD

**Issue by ghost** [MobilityData/gtfs-validator#25]
**Is your feature request related to a problem? Please describe.**
GTFS time type validation emits a warning for any value >= '27:00:00'

**Describe the solution you'd like**
Find out the 95th percentile of real data and use that instead

**Describe alternatives you've considered**
Asking around on the official GTFS GitHub with the risk of picking a value that doesn't satisfy everyone involved in the conversation

**Additional context**
This request stem from https://github.com/MobilityData/gtfs-validator/pull/21#issuecomment-561252588

**Comment by barbeau** [comment]
Closing, as we're not supporting thresholds for now.
