### ISSUE TITLE
[REQUEST] Rename command line option zipinput as input

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#255]
**Is your feature request related to a problem? Please describe.**
The command `zipinput` should be renamed as `input` to prevent confusion since it refers to 
the path of the zip input. Hence the short name should be `-i` instead of `z`

**Comment by barbeau** [comment]
Wasn't `input` renamed to `zipinput` in the past?

**Comment by lionel-nj** [comment]
`input` has been renamed to `extract`

**Comment by barbeau** [comment]
@lionel-nj Ah, right, thanks.
