### ISSUE TITLE
Smarter check for if route_long_name contains route_short_name

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#267]
**Is your feature request related to a problem? Please describe.**
File `routes.txt` requires to check if `route_long_name` contains `route_short_name`. 

However, depending on the number of characters of `route_short_name`, `route_short_name` could be contained in `route_long_name`. 
For example: `route_short_name` is `C`, and `route_long_name` is `Cxxxxxxxxxxx`.
Here, `route_short_name` is just a character of the string defining `route_long_name`. Yet, with our current implementation, a notice would be generated although it should not.
 
**Describe the solution you'd like**
Implement a  regex or an algorithm using a threshold to define whether `route_long_name` contains `route_short_name`.

**Comment by barbeau** [comment]
A simple solution may be to only check for this rule if `route_short_name` is >= 2 or 3 characters.

**Comment by isabelle-dr** [comment]
Is this check implemented in RouteShortAndLongNameEqualNotice or DuplicateRouteNameNotice?

Also just a note: this is mentioned in the Best Practices, not in the routes.txt specification.
> route_long_name should not contain the route_short_name.

**Comment by briandonahue** [comment]
@barbeau @isabelle-dr I am looking at this issue.  Is the preferred solution what @aababilov mentioned [here](https://github.com/MobilityData/gtfs-validator/pull/501#discussion_r535506016):

> check that long name does not start from the short name followed by ' ', '-' or '('.

**Comment by barbeau** [comment]
Seems reasonable to me

**Comment by isabelle-dr** [comment]
Sounds good. Hello @barbeau 👋😊
This issue was initially opened to replace [route_short_and_long_name_equal](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#route_short_and_long_name_equal), and the reference is in the GTFS Best Practices, not the spec.

**Comment by briandonahue** [comment]
Linking to @julianharty's [question on the associated PR ](https://github.com/MobilityData/gtfs-validator/pull/1325#discussion_r1105766132), should we add any more explanation to the documentation about how this rule works?

Also are the characters ' ', '-' and '(' as mentioned [here](https://github.com/MobilityData/gtfs-validator/pull/501#discussion_r535506016) sufficient, or are there other characters - like ':' or ')' - that we should consider in this PR?
