### ISSUE TITLE
ValidateRouteShortNameLengthTest.nullRouteColorShouldNotGenerateNotice() is misnamed

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-validator#274]
**Describe the bug**
The method `ValidateRouteShortNameLengthTest.nullRouteColorShouldNotGenerateNotice()` is misnamed - it should be `ValidateRouteShortNameLengthTest.nullRouteShortNameNotGenerateNotice()`.

**To Reproduce**
Look at code

**Expected behavior**
Method should be named `ValidateRouteShortNameLengthTest.nullRouteShortNameNotGenerateNotice()`

**Witnessed behavior**
Method is named `ValidateRouteShortNameLengthTest.nullRouteColorShouldNotGenerateNotice()`

**Comment by lionel-nj** [comment]
Closing as the change have been provided in c4581e9572511f3b7a53c65f8a4ff43de2eb5f07
