### ISSUE TITLE
Improve protobuf export

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#296]
**Is your feature request related to a problem? Please describe.**

Some records have a lot of fields to be exported (e.g `FieldIntegerOutOfRangeNotice`). Once the list of methods of a builder is exhausted (such as `.setEntityId()`) , it is not possible to export these fields to proto without loosing previous recored information.

It should be possible to export all fields of a notice (even when `null`) to proto.

Also, these same methods throw an `NPE` when called with a `null` parameter. It should be possible to export fields of notice even if they are `null`.

**Describe the solution you'd like**
- add support in exporter to handle null values when exporting notices.
- determine a solution to export all fields of notices.

**Additional context**
See https://github.com/MobilityData/gtfs-validator/blob/05c2abde7e9ac15767fa064fd1e3d11e60d2b2f6/adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporterTest.java#L338

**Comment by barbeau** [comment]
Closing as outdated with annotation-based architecture
