### ISSUE TITLE
Standardize regex implementations

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#305]
**Is your feature request related to a problem? Please describe.**
At present multiple implementations of regex are used, an unique implementatiom should be used.

**Describe the solution you'd like**
Use an unique implementation for regex, for example `Apache commons`

**Additional context**
https://github.com/MobilityData/gtfs-validator/pull/294/files#r444545656

**Comment by barbeau** [comment]
Closing, resolved with v2 architecture
