### ISSUE TITLE
[REQUEST] Extend Google type error listing

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#310]
**Is your feature request related to a problem? Please describe.**
At present, it is not possible to represent as a `Google Type Error` all the problems encountered while validating a GTFS feed.

File of reference for `GtfsProblem`:
 `adapter/repository/in-memory simple/out/production/resources/gtfs_validation.proto`

**Describe the solution you'd like**
This `.proto` file should be extended to account all problems. The following enums should be added:

- `TYPE_INTEGER_VALUE_OUT_OF_RANGE`
-  `TYPE_FLOAT_VALUE_OUT_OF_RANGE` 
- `TYPE_INVALID_DATE`
- `TYPE_INVALID_CURRENCY_CODE`
- `TYPE_UNEXPECTED_ENUM_VALUE`
- `TYPE_MISSING_AGENCY`
- `TYPE_NOT_FOUND_AGENCY_ID`
- `TYPE_NOT_FOUND_ROUTE_ID`

Moreover, this same file should be extended to handle additional proto builder methods such as : 
- `composite_key_first_value`
- `composite_key_second_value` etc..
- `composite_key_first_part`
- `composite_key_second_part` etc...

After modification of `gtfs_validation.proto` and compilation via `protoc`, file `GtfsSpecificationProto` will be automatically modified.

**Comment by barbeau** [comment]
Closing as outdated with annotation-based architecture
