### ISSUE TITLE
[REQUEST] Rework gtfs schema to remove numeric field ranges

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#314]
**Is your feature request related to a problem? Please describe.**
Inclusion of ranges in GTFS scheme defined in `gtfs_spec.asciipb` can lead to confusion when it comes to range validation.

**Describe the solution you'd like**
- Remove numeric fields ranges
- Define new types: NON_NEGATIVE_INTEGER, NON_NULL_INTEGER, NON_NEGATIVE_FLOAT, for consistency with the GTFS specification.

**Additional context**
See https://github.com/MobilityData/gtfs-validator/pull/297

**Comment by barbeau** [comment]
Closing as outdated with annotation-based architecture
