### ISSUE TITLE
Insure consistency among error codes

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#345]
**Describe the bug**
`EmptyFileErrorNotice` uses error code E039 instead of E047.

**To Reproduce**
See `EmptyFileErrorNotice.java`: https://github.com/MobilityData/gtfs-validator/blob/80cbc3c003b8b4f9b92da848151142adf7268f9b/domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/EmptyFileErrorNotice.java#L26

**Expected behavior**
`EmptyFileErrorNotice` should use E047 error code.

**Witnessed behavior**
E039 error code is used

**Environment used**
- OS: macOS Catalina
- Java version: 11.0.5
- gtfs-validator version: 1.2.1

**Additional context**
https://github.com/MobilityData/gtfs-validator/pull/344#discussion_r472291297

**Comment by barbeau** [comment]
Closing, resolved with v2 architecture
