### ISSUE TITLE
Verify stops is no more than 10m away from shape (WARNING)

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#357]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by isabelle-dr** [comment]
Where in the documentation is this mentioned? 

I can only find this from the Best Practices in `shapes.txt`, mentioning 100 meters and not 10.
> Route alignments (in shapes.txt) should be within 100 meters of stop locations which a trip serves.

**Comment by barbeau** [comment]
This issue is old and I believe can be closed. It's currently implemented as https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#StopTooFarFromTripShapeNotice with the 100m threshold.

**Comment by isabelle-dr** [comment]
Thanks, closing this issue
