### ISSUE TITLE
[REQUEST] Improve memory footprint of GTFS entity containers

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#360]
**Is your feature request related to a problem? Please describe.**
This issue is related to https://github.com/MobilityData/gtfs-validator/pull/346#discussion_r481388556 and deals with improvement of memory footprint of GTFS entities 

**Describe the solution you'd like**
Implement methods `.equal()` and `.hashCode()`in GTFS entities (such as `CalendarDate`) to identify GTFS entities with same keys used for in nested maps.
This implementation could prevent from storing memory consuming Strings, and save lots of memory usage.

**Describe alternatives you've considered**
Do nothing.

**Additional context**
@lionel-nj:

> Question! If we do this: https://github.com/MobilityData/gtfs-validator/pull/346#discussion_r481388556 - wouldn’t we loose the check for duplicate when adding CalendarDate entities to the repository?
Or, do you mean that the key used to map CalendarDate  would be a composite key made of service_id and start_date (as string), which would ensure unicity of CalendarDate based on their service_id and start date.

@barbeau:

> Right now in `addCalendarDate()` in the GTFS data repo, we're keying the inner HashMap on the dateAsString:
> `calendarDatePerServiceIdAndDate.get(serviceId).put(dateAsString, newCalendarDate);`
> and `final String dateAsString = newCalendarDate.getDate().toString();`
> 
> So I think the above would technically work, but semantically we can't do it because it violates the definition of the calendar_dates.txt spec in that more than one record in that file can have the same date. So we shouldn't based our `CalendarDates.equals()` just on `CalendarDates.getDate()`.
> So then the question is if we can use the composite key like you suggested instead of just `CalendarDates.getDate()`  for `.equals()` and `.hashCode()`...

@lionel-nj:

> For consistency with the other implementations I would go with the first suggestion. However, the second solution seems interesting since it avoids storing useless String, and we could in the future implement it, not only for `CalendarDate` entities, but also for all entities stored in an nested map I think.

**Comment by barbeau** [comment]
To summarize the above, the goal would be to see if we could switch from using nested `Map`s, which have a separate key, to nested `Sets`, which don't require their own key. 

For example from:

```java
Map<String, Map<String, CalendarDate>> calendarDatePerServiceIdAndDate = new HashMap<>();
```


```java
Map<String, Set<CalendarDate>> calendarDatePerServiceIdAndDate = new HashMap<>();
```java

If it works this could potentially save a `String` per calendar_dates (or stop_times, etc.) entry, which, for those files, would be significant savings. The question is if we can manage this type of change while still having the data we need to execute rules as well as maintaining semantic validity with the GTFS spec (i.e., saying that `CalendarDate` is equal with another `CalendarDate` when that violates the rules of records in GTFS calendar_dates.txt).

**Comment by barbeau** [comment]
My comment in https://github.com/MobilityData/gtfs-validator/pull/346#discussion_r483160648 for `CalendarDate` and making `.equals()` return true if serviceId and date match:

>While this might technically work for our current purposes of enforcing uniqueness of serviceId and date combinations, after looking at this I think it's a dangerous change that could result in strange bugs later. It would be easy for a future developer to call CalendarDate.equals() and assume that two instances of CalendarDate that have the same serviceId and date but different exception type would return false. But with this implementation it would return true.
>
>Let's stick with the existing HashMap impl in the GTFS repo instead of the new Set that relies on this for now, and we can revisit later in #360.

**Comment by barbeau** [comment]
Closing as outdated with annotation-based architecture
