### ISSUE TITLE
Normalize use cases to always take the result repo as a constructor parameter

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#366]
**Is your feature request related to a problem? Please describe.**
Use cases should always take the result repository as a constructor parameter instead of considering said repository as a parameter of their `execute` method.

**Describe the solution you'd like**

Modify use case constructors to take the result repository as a constructor parameter:
`ValidateShapeIdReferenceInStopTime`
`ValidateStopTimeTripId`
 `ValidateBackwardsTimeTravelForStops`
`ValidateStopTimeIncreasingDistance`
`ValidateShapeUsage`
`ValidateShapeIncreasingDistance`
**Additional context**
https://github.com/MobilityData/gtfs-validator/pull/363#discussion_r489716717

**Comment by barbeau** [comment]
Closing, outdated with v2 architecture
