### ISSUE TITLE
[REQUEST] Improve validator documentation

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#368]
**Is your feature request related to a problem? Please describe.**
For now, we are missing description for the 20 first error rules, and 3 warning rule description. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fabrice-v** [comment]
I aslo have ti update all links pointing towards gtfs.org to the new resource center https://gtfs.mobilitydata.org/
