### ISSUE TITLE
Modify GitHub workflow

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#374]
**Is your feature request related to a problem? Please describe.**
GitHub workflow does not include the build of the web related nodules and code

**Describe the solution you'd like**
- [x] Build web related modules and code
- [ ] Run web related tests: no tests implemented yet in this PR
- [x] Packaging as `.jar`

**Additional context**
https://github.com/MobilityData/gtfs-validator/pull/365#issuecomment-694998509

**Comment by barbeau** [comment]
Closing as outdated - future work on web UI won't use the existing implementation. More info on future web UI at #495.
