### ISSUE TITLE
[BUG] How to handle contrast ratio when they are close to the limit set? 

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#376]
**Describe the bug**
This deals with error `E025`. A member of Cal-ITP was wondering how to handle such a situation where route color `BD202E` with white is rejected by the validator.  For the benefit of the community we open an issue on this, so that everyone can be part of the conversation.

**Comment by lionel-nj** [comment]
Color contrast ratio is subjective, yet, the formula that is applied to compute it has been established by professionals of accessibility. (https://www.w3.org/TR/WCAG20-TECHS/G17.html#G17-procedure)

One of the suggestion was to apply some kind of buffer to avoid situations where the validator flags an error when the computed color contrast ratio is close to the limit. Our thought on this it that doing so would potentially lead to an exclusion of a part of the population with limited eyesight.

**Comment by fabrice-v** [comment]
As discussed, I'm of the opinion that said formula was designed by accessibility expert. As such, the validator should reject values even if they are close to the limit as they constitute an error that exclude some part of the population from accessing the data.

**Comment by barbeau** [comment]
>As discussed, I'm of the opinion that said formula was designed by accessibility experts. As such, the validator should reject values even if they are close to the limit as they constitute an error that exclude some part of the population from accessing the data.

I agree

**Comment by lionel-nj** [comment]
FYI @mcplanner
