### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#382]
**Is your feature request related to a problem? Please describe.**
UI is not definitive. 

**Describe the solution you'd like**
- Add a dropzone for configuration file
- Add a button to launch the validator
- Add a visualisation of the configuration file
- Add a visualisation of the validation report

**Describe alternatives you've considered**

**Additional context**

**Comment by barbeau** [comment]
Closing as outdated - future work on web UI won't use the existing implementation. More info on future web UI at #495.
