### ISSUE TITLE
[BUG] Incorrectly prohibits "transfers" field to be blank in Fare_Attributes

### ISSUE THREAD

**Issue by mcplanner** [MobilityData/gtfs-validator#400]
**Describe the bug**
The validator incorrectly creates an error when the transfers field of Fare_Attributes is blank. This is a required field, but allowed to be blank.

**To Reproduce**
http://transitfeeds.com/p/siskiyou-transit-and-general-express/492/latest

**Expected behavior**
According to the [GTFS Reference](https://developers.google.com/transit/gtfs/reference#fare_attributestxt): "The fact that this field can be left empty is an exception to the requirement that a Required field must not be empty."

**Witnessed behavior**
`Notice{filename='fare_attributes.txt', level='ERROR', code='15', title='Missing required value', description='Missing value for field:`transfers` marked as required in entity with id:`4191`', extra='{fieldName=transfers}'}, `

**Environment used**
- OS: macOS Catalina 10.15.6
- Java version: 11.0.5
- gtfs-validator version: gtfs-validator-v1.3.0-SNAPSHOT.jar

**Comment by fabrice-v** [comment]
Note: we lifted the dataset and added it to our future end to end testing of the validator as can be seen here
https://github.com/MobilityData/gtfs-validator/blob/31863ad983f1ae75589edb909f062b95664ce46b/.github/workflows/end_to_end.yml#L56
Thank you for reporting
