### ISSUE TITLE
Add build info to README

### ISSUE THREAD

**Issue by e-lo** [MobilityData/gtfs-validator#403]
In order to quickly understand how to correctly build the Validator from source rather than downloading a release or reading GitHub Actions, please add a quick reference to the build instructions. Suggested text is as follows:

# Build

### Prerequisites
1. Download and install [Gradle](https://gradle.org/)

Build from source using Gradle:

```sh
./gradlew shadowJar 
```

This build will put the packaged jar here to run: `application/cli-app/build/libs/gtfs-validator-v<version number>-SNAPSHOT.jar`

Test the build using the MBTA dataset by running:

```sh
java -jar application/cli-app/build/libs/gtfs-validator-v1.3.0-SNAPSHOT.jar -u https://transitfeeds.com/p/mbta/64/20200531/download -i input.zip -e input -o output -abort_on_error false
```

**Comment by fabrice-v** [comment]
Super, thks for the ready made content. When we'll have merged it, we will also add instructions to build the web ui spring boot server and react client app) from source and how to run them.

**Comment by fabrice-v** [comment]
For future contributions such as those we would suggest using GitHub PR flow.

**Comment by carlfredl** [comment]
We want to encourage everyone to run the validator on GitHub so that we can automatically collect all the relevant info about any issue.
