### ISSUE TITLE
[REQUEST] Add additional feeds for end-to-end, functional tests

### ISSUE THREAD

**Issue by e-lo** [MobilityData/gtfs-validator#406]
**Is your feature request related to a problem? Please describe.**
I've been frustrated when the validator fails and is brittle to different feeds other than MBTA. 

**Describe the solution you'd like**
~5sh additional feeds of varying complexity/quality added to the validator's testing suite  (see issue #405) and continuous integration process. 

**Describe alternatives you've considered**
Running them myself and submitting bugs for each, which isn't ideal b/c developers would ideally catch these bugs before users.

**Comment by fabrice-v** [comment]
We made progress towards simplifying the process, as can be seen in the `End to end` GitHub Action workflow executions
https://github.com/MobilityData/gtfs-validator/actions?query=workflow%3A%22End+to+end%22

We will encourage would be contributors to open PRs in forked repositories in which they update the workflow with datasets of their interest so we could quickly identify critical NPEs issues from data in the wild. The running part would happen in the contained/replicable GitHub environment, easing out the reproducing step. We would be able to diagnose, contribute and pull up code from the PRs.

We intent to demo the procedure during our October 28th deep dive presentation if everything is ready by then. It will consist in a few steps directly through the GitHub web interface to create a fork and directly edit and commit on the workflow file, opening a PR.
The workflow execution result will be visible in the fork GitHub interface as a check on the newly opened PR.
Nothing more required than a GitHub account and a web browser.

It is our hope that will reduce frustration around testing of the validator on a variety of datasets in the short/middle term.

**Comment by fabrice-v** [comment]
Note that starting from today we provide an artifact containing the json reports for all gtfs datasets ran in the end to end GitHub Action workflow. 
![image](https://user-images.githubusercontent.com/55884852/96645891-45139500-12f9-11eb-96c7-aa31b4eaeb0d.png)

It's automatically created for each run. The first run providing it is visible here
https://github.com/MobilityData/gtfs-validator/actions/runs/318541798

**Comment by fabrice-v** [comment]
FYI, find the relevant updated section of the readme [run on GitHub](https://github.com/MobilityData/gtfs-validator/blob/master/README.md#via-github-actions---run-the-validator-on-any-gtfs-archive-available-on-a-public-url)
and [Contribute](https://github.com/MobilityData/gtfs-validator/blob/master/README.md#contribute).

The end to end workflow runs will collect the dataset as well as the report validation if any and provide logs of the validator execution. See an example run [here](https://github.com/MobilityData/gtfs-validator/actions/runs/325537233) and [there](https://github.com/MobilityData/gtfs-validator/runs/1301412316?check_suite_focus=true).
That should provide any member of the public a streamlined and integrated way to raise, investigate, diagnose, propose, collaborate and fix issues.

Thank you so much for bringing that up, it helped coming up with this solution and of course we're open to suggestions and improvements.
