### ISSUE TITLE
[REQUEST] Implement second CI solution as backup

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#416]
**Is your feature request related to a problem? Please describe.**
At present we totally rely on gitHub actions to build artifacts.

**Describe the solution you'd like**
- Have a CI as back up and consider using Circle CI
- Study possibility to run locally github actions
https://github.com/nektos/act

**Describe alternatives you've considered**

**Additional context**

**Comment by fabrice-v** [comment]
> Study possibility to run locally github actions
> https://github.com/nektos/act

That should be split into its own issue and PR. I will create and assign to myself
