### ISSUE TITLE
Errors vs warnings - Incorrect rule about shapes.txt

### ISSUE THREAD

**Issue by mcplanner** [MobilityData/gtfs-validator#417]
**Describe the bug**
I'm given an error that I believe incorrectly interprets the GTFS reference document on shapes.txt. The error claims that all shapes defined must be used, which I don't believe is true.

**To Reproduce**
I'm running this on Tuolumne's October GTFS file, which is not available online, but attached here:
[tuolumne.zip](https://github.com/MobilityData/gtfs-validator/files/5372929/tuolumne.zip)

**Expected behavior**
I did not expect to see this error message because I don't see this requirement in Google's reference document.

**Witnessed behavior**
`Notice{filename='shapes.txt', level='ERROR', code='38', title='Unused shape', description='All records defined by GTFS `shapes.txt` should be used in `trips.txt`. File `shapes.txt`defines entity with id: `23`that is not used.', extra='{fieldName=shape_id}'}]`

**Environment used**
- OS: macOS Catalina 10.15.6
- Java version: 11.0.5
- gtfs-validator version: v1.3.0-SNAPSHOT

**Comment by e-lo** [comment]
To add further to this issue, there is currently a hard line distinguishing a warning from an error in the code, but this should be defined in a config such that you can run the validator based on:

1.  strict treatment of all warnings as errors
2. all GTFS spec and codifyiable best practices treated as errors
3. a user-defined configuration of what is an error vs warning

I believe this will require:
- treatment of the *definitions of* errors vs warning as the same type of entity
- either each error/warning having a boolean property associated with "spec definition" and "best practice" OR a canonical list of warnings/errors which represent each.

**Comment by barbeau** [comment]
Similar issue with extra records in trips.txt, as mentioned in https://github.com/MobilityData/gtfs-validator/issues/519

**Comment by barbeau** [comment]
Related issue for v2 architecture in terms of re-introducing the concept of errors vs warnings - https://github.com/MobilityData/gtfs-validator/issues/549.

**Comment by barbeau** [comment]
Similar issue (unused records in fare_rules.txt) for future rule planned with https://github.com/MobilityData/gtfs-validator/issues/237

**Comment by lionel-nj** [comment]
Will be closed by https://github.com/MobilityData/gtfs-validator/pull/726. This has been set to be a `WARNING` instead of an `ERROR`.
