### ISSUE TITLE
[BUG] Incorrect error on H:MM:SS time format

### ISSUE THREAD

**Issue by mcplanner** [MobilityData/gtfs-validator#428]
**Describe the bug**
Error code 16 seems to be a false positive, as it is citing a rule that conflicts with the GTFS reference.

**To Reproduce**
I ran the validator on the attached GTFS file: [Feed_Trapeze.zip](https://github.com/MobilityData/gtfs-validator/files/5381523/Feed_Trapeze.zip)

**Expected behavior**
I do not expect to see an error for this behavior because the [GTFS reference](https://developers.google.com/transit/gtfs/reference#field_types) document explicitly allows it. ("Time in the HH:MM:SS format (H:MM:SS is also accepted)."

**Witnessed behavior**
`Notice{filename='stop_times.txt', level='ERROR', code='16', title='Invalid time', description='Invalid time:` 9:38:00` in field:`departure_time` for entity with id:`null`', extra='{fieldName=departure_time, timeValue= 9:38:00}'}, `

**Environment used**
- OS: macOS Catalina 10.15.6
- Java version: 11.0.5
- gtfs-validator version: v1.2.2

**Comment by fabrice-v** [comment]
After analysis, it appears a space character is in front of the incriminated Strings. 
![image](https://user-images.githubusercontent.com/55884852/96296328-1fb31e00-0fbd-11eb-9e3d-1d50c436ec58.png)


**Space ` ` is not a valid character** for a time in the `HH:MM:SS` format

Note that a `0` (zero) would be valid in that context
See: https://docs.oracle.com/cd/E41183_01/DR/Time_Formats.html

> Example: 02:18:23
