### ISSUE TITLE
[REQUEST] Study possibility to run GitHub actions locally

### ISSUE THREAD

**Issue by fabrice-v** [MobilityData/gtfs-validator#431]
**Is your feature request related to a problem? Please describe.**
This a split of #416 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Study possibility to run locally github actions
https://github.com/nektos/act

**Comment by fabrice-v** [comment]
It's actually super simple to use `act`. We have a bug though so I'll see after refactoring the GitHub workflows in the Docker image PR. #384

**Comment by e-lo** [comment]
This seems like a good solution to some of my other requests.

I was able to download and install [`act`](https://github.com/nektos/act) very easily but got this error when running it (not sure it is same one you all got)

```sh
(base) elizabeth@Elizabeths-MacBook-Pro-2 gtfs-validator % act
[Java CI/build   ] 🚀  Start image=node:12.6-buster-slim
[End to end/build] 🚀  Start image=node:12.6-buster-slim
[Java CI/build   ]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[End to end/build]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Java CI/build   ]   🐳  docker cp src=/Users/elizabeth/Documents/urbanlabs/CA Interoperable/gtfs-validator/. dst=/github/workspace
[End to end/build]   🐳  docker cp src=/Users/elizabeth/Documents/urbanlabs/CA Interoperable/gtfs-validator/. dst=/github/workspace
Error: error during connect: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/exec/0065c54f6c29faca7249ab278e81e5e395f6b86dee472800ab0746297de34754/start": net/http: HTTP/1.x transport connection broken: unsupported transfer encoding: "identity"
```

**Comment by fabrice-v** [comment]
So, syncing the latest version of master and passing the command `act -j end-to-end`
Now works fine with the validator running on all datasets until the persist artifact steps...
![image](https://user-images.githubusercontent.com/55884852/97044454-23f1b500-1542-11eb-9c20-d25930fec0d4.png)

... which is a known issue of act
https://github.com/nektos/act/issues/329

The files in question can be manually collected inside the container. 
Datasets `.zip` files are present as well as validation reports `.json`
![image](https://user-images.githubusercontent.com/55884852/97044721-8054d480-1542-11eb-8f82-a31471f7f204.png)



I think that's as far as we can go presently. Do you think @e-lo that would be enough to close this issue?

**Comment by fabrice-v** [comment]
@e-lo the documentation has been updated. Let us know as we will merge it for release `v1.3.0` that should happen today no earlier than 14:00 EST
