### ISSUE TITLE
[Question] UI to view validation results?

### ISSUE THREAD

**Issue by NomeQ** [MobilityData/gtfs-validator#442]
I'm testing out the validator for @Trillium-Solutions, and am wondering if there is a tool or UI for consuming and displaying the results.json.

I see a few tags for a "local web UI" here in the Issues - does that tool already exist and just lack documentation, or is that something different altogether?

**Comment by fabrice-v** [comment]
Hi, thks for your question and welcome around!

Quick answer: there is no tool or UI for consuming the validation report.

Longer answer: The local web UI is a web application packaging the validator functionality in a Spring based server and a React based client. It has just been merged, packaged and published as a [Docker image](https://github.com/orgs/MobilityData/packages/container/package/gtfs-validator) for the first time today. 
`docker pull ghcr.io/mobilitydata/gtfs-validator:master`
It's a first version that opens a local text editor to consume and display the validation report but could be a good candidate for more advanced visually displaying the results.
You can see more details in #421 

Hope that answer your question,

**Comment by e-lo** [comment]
@NomeQ -  perhaps open a feature request issue so that it is tracked?

**Comment by fabrice-v** [comment]
FYI @NomeQ , we figured the validation report display is broken when the web app is run inside Docker. We should have a fix shortly to display it right into the UI. See #451

**Comment by fabrice-v** [comment]
It has now been merged to master and is available in the Docker image
![image](https://user-images.githubusercontent.com/55884852/97194956-22620000-1781-11eb-935e-31392d8a0900.png)

Hope that helps,
