### ISSUE TITLE
Improve package declarations

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#444]
**Is your feature request related to a problem? Please describe.**
At present some packaged declarations are mixed-up.:
- https://github.com/MobilityData/gtfs-validator/blob/e639357a10d4995789c95031718198fa60645b72/adapter/protos/src/main/java/org/mobilitydata/gtfsvalidator/protos/GtfsSpecificationProto.java#L4
- https://github.com/MobilityData/gtfs-validator/blob/e639357a10d4995789c95031718198fa60645b72/adapter/protos/src/main/java/org/mobilitydata/gtfsvalidator/protos/GtfsValidationOutputProto.java#L20

**Describe the solution you'd like**
The original `proto` should be modified. Then  the bindings should be re-generated.

**Comment by barbeau** [comment]
Closing, fixed by v2 architecture
