### ISSUE TITLE
Implement solution to gracefully shutdown web-app and enable switch to cli-app in Docker image

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#445]
**Is your feature request related to a problem? Please describe.**
We have not implemented yet a solution to gracefully shutdown web-app and enable switch to cli-app in Docker image.

**Describe the solution you'd like**
- add code in spring-server to shutdown web-app gracefully. 
- implement a button in the `react-client` to shut down the process
- produce an only Docker image that will contain the `cli-app`  and the `web-app`.

**Describe alternatives you've considered**

**Additional context**

**Comment by barbeau** [comment]
Closing as outdated - future work on web UI won't use the existing implementation. More info on future web UI at #495.
