### ISSUE TITLE
[REQUEST] Ensure consistency of Route entities with new extensions

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#448]
**Is your feature request related to a problem? Please describe.**
At present the`gtfs-validator` does not account for the new development of the GTFS specification.
Particularly `Route` entities should be updated to include the following fields:
- `continousDropOff` 
- `continuousPickUp`

**Describe the solution you'd like**
- Update Route `GtfsEntity`
- additional unit tests

**Comment by barbeau** [comment]
Closed by https://github.com/MobilityData/gtfs-validator/pull/486
