### ISSUE TITLE
[REQUEST] Handle #397 gracefully

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#458]
**Is your feature request related to a problem? Please describe.**
#397 is two folded:
1. we should provide a graceful way to handle the NPE thrown by #397
1. we should provide a bug fix for #397

This issue deals with the first step:  provide a graceful way to handle the NPE thrown by #397

**Describe the solution you'd like**
Generate a notice describing the fact that the structure of `calendar.txt` and `calendar_dates.txt` is not supported yet. 

**Additional context**
See #397

**Comment by fabrice-v** [comment]
The notice should be an info notice as to not stop the validation process
