### ISSUE TITLE
[REQUEST] Adding some details for bug reports

### ISSUE THREAD

**Issue by unreasonableman** [MobilityData/gtfs-validator#468]
I would like to see a couple of things regarding bug reports:

- distinguish crash bugs from "just" incorrect behavior. Crash bugs are serious because a) they provide a poor user experience, and b) they may hide other bugs that the system just never got to because it crashed. I would like to see an issue template specifically for bugs, and I would suggest for it to have a section that specifically asks if this is a crash bug. In addition, I would like to see a "Crash" label that is applied to such bugs

- also in the bug report template, I would like to see a section called "Inputs" or something that specifically asks the user to provide the GTFS URL or zip file that caused the issue

From a comment elsewhere by @f8full it seems like .github/ISSUE_TEMPLATES/bug_report.md used to exist, but was deleted. That file seems well suited to contain the sections mentioned above. Fabrice, can you talk about why the file was deleted?

I am happy to make these changes. Wondering if there is a preference between just branching the main repo and doing a PR, or if doing a full fork is necessary.

**Comment by carlfredl** [comment]
Thanks for the feedback.

Our idea with creating new templates yesterday was to streamline the reporting and triage processes. 

Basically what we are asking folks to contribute is just enough for us to be able to reproduce the issue so we can run test and get a standardized report out of CircleCI.

**Comment by unreasonableman** [comment]
I'm sorry, I don't understand how this answers my questions:
- should I just submit a PR for the main repo for this, or do I need to do a full fork?
- why was the bug_report.md file deleted from the repo?
