### ISSUE TITLE
Validator behaviour when encountering unexpected enum values

### ISSUE THREAD

**Issue by ghost** [MobilityData/gtfs-validator#47]
**Is your feature request related to a problem? Please describe.**
It is presently unclear how the validator should behave when it encounters an unexpected enum value in an expected field.

**Describe the solution you'd like**
TODO: the result of the discussion will be resumed here

**Additional context**
Stem from https://github.com/MobilityData/gtfs-validator/pull/44#discussion_r387732469

**Comment by barbeau** [comment]
Closing, addressed in the new v2 architecture
