### ISSUE TITLE
Document the Development Roadmap

### ISSUE THREAD

**Issue by e-lo** [MobilityData/gtfs-validator#476]
**Is your feature request related to a problem? Please describe.**
As a potential contributor, it is frustrating to not understand the development roadmap and what MobilityData is expecting to take on as core developers and what features are in-scope and available for other contributors to take on.

**Describe the solution you'd like**
- Tagging of issues/features that MobilityData expect to take on themselves
- Tagging of issues/features that MobilityData supports but doesn't expect to take on themselves unless somebody else submits a PR
- General development roadmap with key milestones

**Describe alternatives you've considered**
- Sending MobilityData lots of emails :-)

**Comment by Cristhian-HA** [comment]
Hello @e-lo 
Thank you for your feedback. We will discuss this internally and we will get back to you as soon as possible.
Have a great day!

**Comment by lionel-nj** [comment]
Hi @e-lo! We have been working on exposing the roadmap. We recently shared our big picture roadmap for the Canonical GTFS Validator, it can be found [here](https://github.com/MobilityData/gtfs-validator/wiki/Roadmap). 
All contributors are welcome to edit this wiki and add major items you would like to work on or solve! 

Also, we have put in place different labels which can be uses to tag issues and/or PRs. 
The label:
- [`community`](https://github.com/MobilityData/gtfs-validator/labels/community): is dedicated to contributions that community members could help with
- [`wontfix`](https://github.com/MobilityData/gtfs-validator/labels/wontfix): is dedicated to suggestions that do not align with the roadmap of the validator

Thank you, feel free to close this issue if this answers your questions 😀

**Comment by e-lo** [comment]
LGTM - thank you!
