### ISSUE TITLE
[REQUEST] Benchmark/improve performance of GTFS entity enums

### ISSUE THREAD

**Issue by fabrice-v** [MobilityData/gtfs-validator#48]
**Is your feature request related to a problem? Please describe.**
Yhis feature is linked to the general idea of optimizing the validator for performance.

**Describe the solution you'd like**
This code https://github.com/MobilityData/gtfs-validator/blob/cd453761ef60a7d6c7bdc6ed5dd07d65ca31c1f6/domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/stops/WheelchairBoarding.java#L36 
could be replaced by a switch statement.

**Additional context**
https://github.com/MobilityData/gtfs-validator/pull/44#discussion_r388938144

**Comment by barbeau** [comment]
This issue applies to all enums for GTFS entities - see `org.mobilitydata.gtfsvalidator.domain.entity` package.
