### ISSUE TITLE
[REQUEST] differentiate tests on GitHub actions and CircleCI

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#482]
**Is your feature request related to a problem? Please describe.**
At present, the validator's tests randomly fail on CircleCI: [`NoticeMemoryConsumptionTest`](https://github.com/MobilityData/gtfs-validator/blob/bcc6d8178f8b0fdf2108c5e83998f80c8c29ba6e/adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/NoticeMemoryConsumptionTest.java#L82).
It is possible that this happens because by the amount of memory available on CircleCI is different from the one available on GitHub actions.

- sample of job successfully ran on CircleCI: https://app.circleci.com/pipelines/github/MobilityData/gtfs-validator/433/workflows/2e7166a4-4bf5-4817-a551-6e294795bb15

- sample of the same job failing on CircleCI (nothing changed, we just relaunched the machine): https://app.circleci.com/pipelines/github/MobilityData/gtfs-validator/433/workflows/2700426f-db30-411f-b0e0-02b22045e995

- sample of the same job successfully ran on GitHub Actions: https://github.com/MobilityData/gtfs-validator/actions/runs/358118727

**Describe the solution you'd like**
Adapt the test to be ran on CircleCi using an environmental variable to distinguish GitHub actions from CircleCI.

**Comment by fabrice-v** [comment]
I think we should just relax those tests or remove them altogether to fix circleCI because v2.0 is coming.

**Comment by barbeau** [comment]
Closing as outdated - we're not using Circle CI.
