### ISSUE TITLE
False positives for translations "Duplicate entity"

### ISSUE THREAD

**Issue by gabrbuiv** [MobilityData/gtfs-validator#492]
A lot of "Duplicate entity" error false positives occur because only `table_name`, `field_value` and `language` are being used to check for uniqueness in `InMemoryGtfsDataRepository` method `addTranslation`. 

Example feed: https://openmobilitydata.org/p/city-of-turku/730/latest/download

The sample of incorrect validation errors:

table_name | field_name | language | translation              | record_id
stops           | stop_name | sv             | Hintza Knaps gata | 1460
stops           | stop_name | sv             | Hintza Knaps gata | 1461
stops           | stop_name | sv             | Hintza Knaps gata | 835

**Comment by fabrice-v** [comment]
Thks @gabrbuiv for having prepared a public fork, this is just perfect for us to be able to provide the best assistance in the coming days.
https://github.com/gabrbuiv/gtfs-validator (@lionel-nj )

**Comment by fabrice-v** [comment]
And, [it's already up to date](https://github.com/gabrbuiv/gtfs-validator/compare/master...MobilityData:master) with latest release, [v1.4.0](https://github.com/MobilityData/gtfs-validator/releases/tag/v1.4.0)

**Comment by barbeau** [comment]
Closing, fixed in master branch with the v2 architecture
