### ISSUE TITLE
Validate trip frequencies do not overlap

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#522]
**Describe the solution you'd like**
Validate trip frequencies do not overlap

**Additional context**
`v1.4.0` implementation:
- https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateTripFrequenciesOverlap.java
- https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateTripFrequenciesOverlapTest.java

**Comment by barbeau** [comment]
Reopening this - rule was implemented in https://github.com/MobilityData/gtfs-validator/pull/581, but it still needs to be added to RULES.md.
