### ISSUE TITLE
Verify `shape_dist_traveled` increase along a shape in `shapes.txt`

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#527]
**Describe the solution you'd like**
Verify `shape_dist_traveled` increase along a shape in `shapes.txt` 

**Additional context**
`v1.4.0` implementation: 
https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ValidateShapeIncreasingDistance.java
- tests: https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ValidateShapeIncreasingDistanceTest.java

**Comment by lionel-nj** [comment]
Closing as already implemented in #486

**Comment by timMillet** [comment]
@lionel-nj 
In order to make the spec definitions and/or the Best Practices more accurate, could you tell me what is the validation behavior that has been implemented regarding this use case?

**Comment by lionel-nj** [comment]
@lionel-nj
In order to make the spec definitions and/or the Best Practices more accurate, could you tell me what is the validation behavior that has been implemented regarding this use case?
Thank you :)

This has been treated as an `ERROR`, see https://github.com/MobilityData/gtfs-validator/blob/d355fbd15f2f971f990edaba189944f3fb7c7fb1/main/src/main/java/org/mobilitydata/gtfsvalidator/notice/DecreasingShapeDistanceNotice.java#L28

**Comment by lionel-nj** [comment]
@timMillet as discussed, decreasing values for `shapes.shape_dist_traveled` are considered an `ERROR`, equal values are not considered an  `ERROR`.

**Comment by lionel-nj** [comment]
@timMillet, After discussion, decreasing  AND equal values for shapes.shape_dist_traveled should be considered an error. 

decreasing values for shapes.shape_dist_traveled #757 has been opened to better reflect the specification.
