### ISSUE TITLE
GTFS archive should not contain folder

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#528]
**Describe the solution you'd like**
Validate GTFS archive does not contain folder

**Additional context**
`v1.4.0` implementation: 
- https://github.com/MobilityData/gtfs-validator/blob/76970f6ab56c885ef3fad951a6bff2531ae18a3e/usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/UnzipInputArchive.java#L83
- https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/UnzipInputArchiveTest.java

**Comment by barbeau** [comment]
Closed with new v2.0 architecture
