### ISSUE TITLE
GTFS dataset too big

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#536]
**Describe the solution you'd like**
Implement a solution to crash gracefully in case dataset is too big

**Additional context**
`v1.4.0` implementation: 
- https://github.com/MobilityData/gtfs-validator/blob/76970f6ab56c885ef3fad951a6bff2531ae18a3e/usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/DownloadArchiveFromNetwork.java#L110
- tests: https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/DownloadArchiveFromNetworkTest.java

**Comment by barbeau** [comment]
Closed by https://github.com/MobilityData/gtfs-validator/pull/596
