### ISSUE TITLE
Fatal internal error -- please report

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#537]
**Describe the solution you'd like**
Implement a solution to crash gracefully in case of unknown exception/error

**Additional context**
`v1.4.0` implementation:
- https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/HandleUnsupportedException.java
- tests: https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/HandleUnsupportedExceptionTest.java

**Comment by barbeau** [comment]
Closed by https://github.com/MobilityData/gtfs-validator/pull/596
