### ISSUE TITLE
Handle Out of memory errors

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#538]
**Describe the solution you'd like**
Handle gracefully Out of memory errors

**Additional context**
`v1.4.0` implementation: 
- https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/HandleOutOfMemoryError.java
- tests: https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/HandleOutOfMemoryErrorTest.java

**Comment by barbeau** [comment]
Closed by https://github.com/MobilityData/gtfs-validator/pull/596
