### ISSUE TITLE
Make -f an optional command-line parameter

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-validator#539]
**Is your feature request related to a problem? Please describe.**
IMHO it's a bit awkward to have `-f` or `--feed_name` be a required command-line parameter, as it forces you to have a priori knowledge about the dataset you're validating. If given a directory of GTFS zip files with no metadata, it's not a trivial task to find the country code for each.

**Describe the solution you'd like**
Make `-f` an optional command-line parameter, where rules that require `-f` are skipped if `-f` isn't provided.

IIRC right now the feed name is only used for the country code to validate phone numbers.

@aababilov Thoughts on this? Is this something you could work on?

**Describe alternatives you've considered**
Clarify how `-f` parameter should be used in documentation and what happens if you provide a wrong country code, and what the valid values for the name is.

**Comment by maximearmstrong** [comment]
@barbeau I agree with you on this. @annaelleduff and me noticed this while implementing the Validator 2.0 in the MobilityDatabase pipeline. Most of the time, we won't have access to the country code prior to validation.

At the moment, for the harvesting of OpenMobilityData, we managed to obtain the country code using [Nominatim](nominatim.openstreetmap.org). This is possible thanks to the latitude and longitude of a dataset given by the API of OpenMobilityData. However, this information might not always be accessible prior to validation of a dataset.

Could the Validator use the latitude and longitude pairs found inside the dataset to get the country code?
Also, it would remove potential human errors from modifying the validation report.
cc: @lionel-nj @aababilov

**Comment by barbeau** [comment]
There are also embedded libraries that we could leverage to do lookup of country code from lat/long without having to hit an external API, like https://github.com/bencampion/reverse-country-code.

**Comment by lionel-nj** [comment]
It appears that `GtfsFeedName` is used to check the phone number formatting. A possible implementation could consist in an additional multiple file `validator` that would check phone numbers formatting (in agency.txt, and attributions.txt). This use case would be executed if `-f` is not provided. 

@barbeau @aababilov  However I am afraid that this approach might not scale efficiently: if the validator was to be extended (addition of another table which contains a `phone number` field) the implementor would have to modify said use case to validate the extension.

**Comment by aababilov** [comment]
I can propose the following option.

Add a flag for country code. It may be used to validate phone numbers and it may have other use cases in the future. The full feed name is not needed, so that flag may be removed.

Reverse country code is a good option for some use cases but we cannot use it for phone validation :(

1. Validation of phone numbers depends on the content of agency.txt only. Latlngs are not available since they are in stops.txt.
2. Agencies may naturally cover multiple countries.
3. Agencies may have no stops assigned.

**Comment by barbeau** [comment]
@aababilov What are you thoughts on making the phone number validation optional, and only execute it if the `-f` or alternate country code parameter is provided?
