### ISSUE TITLE
Class file version of CLI jar exceeds minimum Java version (8) referenced in usage docs

### ISSUE THREAD

**Issue by botanize** [MobilityData/gtfs-validator#542]
**Issue encountered**
I attempted to run [gtfs-validator](https://github.com/MobilityData/gtfs-validator/releases/download/v1.4.0/gtfs-validator-v1.4.0_cli.jar) with Java 8 but encountered the following error:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/mobilitydata/gtfsvalidator/cli/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

The [usage documentation](https://github.com/MobilityData/gtfs-validator/blob/master/docs/USAGE.md) says "install Java 8 or higher", but it looks like the minimum supported version is Java 11 (class file version 55.0).

Seems like either the something needs to change with the builds to support earlier versions of Java (preferable) or the documentation needs to be updated.

**Comment by barbeau** [comment]
@botanize If you're running v1.x release JAR you'll need Java 11, and can follow these instructions:
https://github.com/MobilityData/gtfs-validator/tree/v1.4.0#via-java-on-your-local-computer

The current master branch (which will eventually be v2.0) is a refactor of the project for efficiency and currently only requires Java 8. I agree that this isn't currently clear - you caught us in the middle of switching over.

@lionel-nj Would you be able to add a note at the top of the main README usage section and usage docs that point to the above link for anyone using the v1.x releases?

**Comment by lionel-nj** [comment]
> @lionel-nj Would you be able to add a note at the top of the main README usage section and usage docs that point to the above link for anyone using the v1.x releases?

See https://github.com/MobilityData/gtfs-validator/pull/543/commits/50a70436faec397eb0fed8b3b4aae452ff13e090
