### ISSUE TITLE
Distinguish between errors and warnings in notices

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-validator#549]
**Is your feature request related to a problem? Please describe.**
v1.x of the validator distinguishes between errors and warnings.

The current master branch after the annotation refactor does not.

For example, see this comment for `PlatformWithoutParentStationNotice` which should be distinguished as a warning and not an error:
https://github.com/MobilityData/gtfs-validator/pull/500#discussion_r538869906

**Describe the solution you'd like**
We should update the annotation-based validator with the concept of errors vs. warnings.

**Describe alternatives you've considered**
N/A

**Comment by carlfredl** [comment]
I'm going to review with MobilityData spec team:
- Define methodology for deciding error vs. warning. (In-spec = error / Open to interpretation = warning.) What does in-spec mean?
- Example: [Shape distance travelled must always increase](https://github.com/MobilityData/gtfs-validator/issues/527)

**Comment by aababilov** [comment]
This issue was not fully resolved. We still do not export info about severity and we do not make decisions based on that.

I volunteer to take this issue.

**Comment by aababilov** [comment]
Actually, that was my issue from the beginning :)

**Comment by barbeau** [comment]
The MobilityData spec team has decided to define ERRORS vs. WARNINGs as the following:
* If the [GTFS reference spec](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md) says something is required ("must" or "must not" be done), then violation of this is an ERROR
* Otherwise, violations of any other language ("should", "should not") in the GTFS reference, or violation of anything in the [GTFS Best Practices](https://gtfs.org/best-practices/) is a WARNING

(The above choices for "must" vs. "should" follow [RFC 2119](https://tools.ietf.org/html/rfc2119) - with the realization that the GTFS spec will need to be modified to come into full compliance with RFC 2119 based on current GTFS industry practice)

Note that this doesn't necessarily align with the current definitions of `SeverityLevel` in the validator, which is:
* `INFO` - is used for things that do not affect the feed's quality, such as unknown files or unknown fields
* `WARNING` - is used for things that affects the feed's quality (e.g., insufficient color contrast) but the feed remains functional
* `ERROR` - is used when the feed cannot function (e.g., broken foreign key reference)

Should we reconsider the enumerations for `SeverityLevel` to be something like `HIGH`, `MEDIUM`, and `LOW`, which is possibly orthogonal to whether something is declared an ERROR or WARNING based on the spec?

In theory the spec should always be changed so that high severity items are called out as "must" or "must not", but given that will take time to align I think it's worth discussing the above.

@aababilov @lionel-nj Thoughts on this?

**Comment by aababilov** [comment]
This makes sense to me but please let's postpone that modification until we revise the GTFS reference.

The existing GTFS reference does not define explicitly certain things, e.g, that foreign key **must** reference a valid primary key.

Some should vs must phrasing is incorrect, e.g.:

> The value in record_id should be a main ID of the table
The value in record_id **must** be a main ID of the table

So, we cannot use GTFS reference as the source of truth for telling between ERRORS and WARNINGS right now. I wish to see that happen in the future.

Could you provide your rationale for using `HIGH`, `MEDIUM` and `LOW` instead of `ERROR`, `WARNING` and `INFO`?

**Comment by barbeau** [comment]
>Could you provide your rationale for using HIGH, MEDIUM and LOW instead of ERROR, WARNING and INFO?

Assuming the validator is a canonical implementation of the spec and that's how we define ERROR vs WARNING, it gives us a way to mark some issues as more important than others until we can bring the spec into the alignment with practice.

Also, in USF's work with the open-source GTFS-realtime validator, producers requested prioritization among the detected issues, especially in the area of warnings. Some are more egregious than others, so this would enable us to classify them accordingly. 

Alternately, if we don't think a separate severity scale is useful, we can just keep ERROR vs WARNING vs INFO, although as stated above the definition needs to change if it's a canonical validator.

**Comment by carlfredl** [comment]
I think we should ship the v2.0 with our best understanding of the GTFS reference as it is today.

In the vision for what's after we should:
1.) FIx the language in the GTFS reference to be able to make the Error directly reflect in spec 
2.) Add functionality to the Validator to allow for
- MobilityData's best practices (WARNINGS)
- Google's acceptance rules (ERRORS) and best practices (WARNINGS)
- Apple's acceptance rules (ERRORS) and best practices (WARNINGS)
- ...'s acceptance rules (ERRORS) and best practices (WARNINGS)

**Comment by timMillet** [comment]
Related document: [[Internal] Discrepancies Specification vs Validator](https://docs.google.com/document/d/1bp8wReHYbXgyyJQY17i2QIOAgn8sLPLT2s7-FHb7M6c/edit#)
