### ISSUE TITLE
Additional unit tests for processor module

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#569]
**Is your feature request related to a problem? Please describe.**
At present, the new architecture is not fully tested. 

**Describe the solution you'd like**
Additional unit tests should be written.

**Additional context**
See:
- additional unit tests for [core module](https://github.com/MobilityData/gtfs-validator/issues/567)
- additional unit test for [main module](https://github.com/MobilityData/gtfs-validator/issues/570)

**Comment by barbeau** [comment]
@lionel-nj I think this issue can be closed in favor of https://github.com/MobilityData/gtfs-validator/issues/734?

**Comment by lionel-nj** [comment]
> @lionel-nj I think this issue can be closed in favor of #734?

Yes! Closing now.
