### ISSUE TITLE
Could not export results as file

### ISSUE THREAD

**Issue by mpaine-act** [MobilityData/gtfs-validator#579]
**Issue encountered**
When trying to run against my agency's GTFS, the output file could not be exported for unknown reasons.

[ERROR] 2020-12-30 09:31:04.720 [main] Main - Could not export results as file: C-\Temp\output\AC_TRANSIT__AC_TRANSIT__2020-12-30_12-31-04.6792359.json

**Steps to Reproduce**
1. Downloaded gtfs-validator-v1.4.0_cli.jar
2. using java 11: cd c:\temp ^^ java -jar .\gtfs-validator-v1.4.0_cli.jar -i .\GTFS.zip -o .\report.json -f us-ACT

**Comment by lionel-nj** [comment]
Thanks for opening an issue @mpaine-act. 
**The documentation available on the master branch is applicable for the next version of the `gtfs-validator`.** 

To run the `v1.4.0` version of the `gtfs-validator`, please refer to this [`README.md`](https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/README.md). 
In your case, to run the validator, a sample usage could be: 
`java -jar gtfs-validator-v1.4.0_cli.jar -i GTFS.zip`

which will: 
1. validate the gifts archive named `GTFS.zip` located at the root of the project,
2. extract the content of said archive in a folder named `input` at the root of the project,
3. generate a `.json` validation report named `report.json` in a folder named `output` at the root of the project.

Please note that the validator will abort on the first error; to override this default behavior set `--abort_on_error` to `false`: 
`java -jar gtfs-validator-v1.4.0_cli.jar -i GTFS.zip **-a false**`.

**Comment by mpaine-act** [comment]
Thank you for the tips.  I retried and it still failed to write the export results to a file.   Is this because I'm running on Windows 10?  Perhaps that OS is untested.


Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
[WARN ] 2021-01-04 08:57:41.842 [main] Main - Configuration file execution-parameters.json not found in working directory
[INFO ] 2021-01-04 08:57:41.846 [main] Main - Retrieving execution parameters from command-line
[INFO ] 2021-01-04 08:57:42.124 [main] Main - --input not provided. Will extract zip content in: P:\github\gtfs-validator\input
[INFO ] 2021-01-04 08:57:42.124 [main] Main - --output not provided. Will place execution results in: P:\github\gtfs-validator\output
[INFO ] 2021-01-04 08:57:42.131 [main] Main - Unzipping archive
[INFO ] 2021-01-04 08:57:42.312 [main] Main - No file to exclude -- will execute validation process on all files
[INFO ] 2021-01-04 08:57:42.317 [main] Main - List of filenames to exclude is: []
[INFO ] 2021-01-04 08:57:42.318 [main] Main - Will execute validation on the following subset of files: [feed_info.txt, stops.txt, routes.txt, trips.txt, stop_times.txt, agency.txt, calendar.txt, calendar_dates.txt, shapes.txt]
[INFO ] 2021-01-04 08:57:42.340 [main] Main -

Validate CSV structure and field types for file: feed_info.txt
[INFO ] 2021-01-04 08:57:42.342 [main] Main - Validating rule 'E_039 & W_009 - Empty file'
[INFO ] 2021-01-04 08:57:42.367 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2021-01-04 08:57:42.367 [main] Main -                   'E043 - Duplicated field
[INFO ] 2021-01-04 08:57:42.367 [main] Main -                   'W002 - Non standard field name
[INFO ] 2021-01-04 08:57:42.404 [main] Main -

Validate CSV structure and field types for file: stops.txt
[INFO ] 2021-01-04 08:57:42.404 [main] Main - Validating rule 'E_039 & W_009 - Empty file'
[INFO ] 2021-01-04 08:57:42.405 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2021-01-04 08:57:42.406 [main] Main -                   'E043 - Duplicated field
[INFO ] 2021-01-04 08:57:42.406 [main] Main -                   'W002 - Non standard field name
[INFO ] 2021-01-04 08:57:42.673 [main] Main -

Validate CSV structure and field types for file: routes.txt
[INFO ] 2021-01-04 08:57:42.674 [main] Main - Validating rule 'E_039 & W_009 - Empty file'
[INFO ] 2021-01-04 08:57:42.676 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2021-01-04 08:57:42.677 [main] Main -                   'E043 - Duplicated field
[INFO ] 2021-01-04 08:57:42.678 [main] Main -                   'W002 - Non standard field name
[INFO ] 2021-01-04 08:57:42.693 [main] Main -

Validate CSV structure and field types for file: trips.txt
[INFO ] 2021-01-04 08:57:42.694 [main] Main - Validating rule 'E_039 & W_009 - Empty file'
[INFO ] 2021-01-04 08:57:42.697 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2021-01-04 08:57:42.698 [main] Main -                   'E043 - Duplicated field
[INFO ] 2021-01-04 08:57:42.698 [main] Main -                   'W002 - Non standard field name
[INFO ] 2021-01-04 08:57:43.046 [main] Main -

Validate CSV structure and field types for file: stop_times.txt
[INFO ] 2021-01-04 08:57:43.047 [main] Main - Validating rule 'E_039 & W_009 - Empty file'
[INFO ] 2021-01-04 08:57:43.050 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2021-01-04 08:57:43.051 [main] Main -                   'E043 - Duplicated field
[INFO ] 2021-01-04 08:57:43.051 [main] Main -                   'W002 - Non standard field name
[INFO ] 2021-01-04 08:57:51.165 [main] Main -

Validate CSV structure and field types for file: agency.txt
[INFO ] 2021-01-04 08:57:51.166 [main] Main - Validating rule 'E_039 & W_009 - Empty file'
[INFO ] 2021-01-04 08:57:51.167 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2021-01-04 08:57:51.168 [main] Main -                   'E043 - Duplicated field
[INFO ] 2021-01-04 08:57:51.168 [main] Main -                   'W002 - Non standard field name
[INFO ] 2021-01-04 08:57:51.181 [main] Main -

Validate CSV structure and field types for file: calendar.txt
[INFO ] 2021-01-04 08:57:51.181 [main] Main - Validating rule 'E_039 & W_009 - Empty file'
[INFO ] 2021-01-04 08:57:51.182 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2021-01-04 08:57:51.183 [main] Main -                   'E043 - Duplicated field
[INFO ] 2021-01-04 08:57:51.183 [main] Main -                   'W002 - Non standard field name
[INFO ] 2021-01-04 08:57:51.189 [main] Main -

Validate CSV structure and field types for file: calendar_dates.txt
[INFO ] 2021-01-04 08:57:51.189 [main] Main - Validating rule 'E_039 & W_009 - Empty file'
[INFO ] 2021-01-04 08:57:51.190 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2021-01-04 08:57:51.191 [main] Main -                   'E043 - Duplicated field
[INFO ] 2021-01-04 08:57:51.191 [main] Main -                   'W002 - Non standard field name
[INFO ] 2021-01-04 08:57:51.214 [main] Main -

Validate CSV structure and field types for file: shapes.txt
[INFO ] 2021-01-04 08:57:51.214 [main] Main - Validating rule 'E_039 & W_009 - Empty file'
[INFO ] 2021-01-04 08:57:51.218 [main] Main - Validating rules :'E001 - Missing required field
[INFO ] 2021-01-04 08:57:51.218 [main] Main -                   'E043 - Duplicated field
[INFO ] 2021-01-04 08:57:51.219 [main] Main -                   'W002 - Non standard field name
[INFO ] 2021-01-04 08:57:55.169 [main] Main - Validating rule 'W005 - Route short name too long'
[INFO ] 2021-01-04 08:57:55.171 [main] Main - Validating rule 'E025 - Insufficient route color contrast'
[INFO ] 2021-01-04 08:57:55.175 [main] Main - Validating rule 'E024 - Same name and description for route'
[INFO ] 2021-01-04 08:57:55.179 [main] Main - Validating rule 'E026 - Invalid route type'
[INFO ] 2021-01-04 08:57:55.181 [main] Main - Validating rule 'E027 - Missing route short name and long name'
[INFO ] 2021-01-04 08:57:55.183 [main] Main - Validating rule 'E028 - Route long name equals short name'
[INFO ] 2021-01-04 08:57:55.189 [main] Main - Validating rule 'E032 - calendar.txt end_date is before start_date'
[INFO ] 2021-01-04 08:57:55.191 [main] Main - Validating rule 'E030 - Different 'agency_timezone'
[INFO ] 2021-01-04 08:57:55.193 [main] Main - Validating rule E033 - `route_id` not found
[INFO ] 2021-01-04 08:57:55.203 [main] Main - Validating rule E036 - `service_id` not found
[INFO ] 2021-01-04 08:57:55.212 [main] Main - Validating rule 'E035 - `agency_id` not found
[INFO ] 2021-01-04 08:57:55.218 [main] Main - Validating rules: 'E049 - Bad combination of stoptime arrival and departure times`
[INFO ] 2021-01-04 08:57:55.219 [main] Main -                   'E034 - `shape_id` not found
[INFO ] 2021-01-04 08:57:55.220 [main] Main -                   'E037 - `trip_id` not found
[INFO ] 2021-01-04 08:57:55.221 [main] Main -                   'E054 & W013 - Decreasing travelled distance
[INFO ] 2021-01-04 08:57:55.412 [main] Main - Validating rules :'E038 - All shapes should be used in GTFS `trips.txt`
[INFO ] 2021-01-04 08:57:55.413 [main] Main - Validating rules :'E058 - Decreasing `shape_dist_traveled` in `shapes.txt`
[INFO ] 2021-01-04 08:57:55.463 [main] Main - Validating rule 'E037 - `feed_start_date` and `feed_end_date` out of order
[INFO ] 2021-01-04 08:57:55.465 [main] Main - Validating rule 'E038 - Dataset should be valid for at least the next 7 days'
[INFO ] 2021-01-04 08:57:55.469 [main] Main - Validating rule 'W009 - Dataset should cover at least the next 30 days of service'
[INFO ] 2021-01-04 08:57:55.472 [main] Main - Validating rule W010 - `feed_end_date` should be provided if `feed_start_date` is provided
[INFO ] 2021-01-04 08:57:55.475 [main] Main - Validating rule W011 - `feed_start_date` should be provided if `feed_end_date` is provided
[INFO ] 2021-01-04 08:57:55.476 [main] Main - Validating rule 'E045 - `departure_time` and `arrival_time` out of order
[INFO ] 2021-01-04 08:57:55.515 [main] Main - Validating rule E044 - Missing trip edge arrival_time or departure_time
[INFO ] 2021-01-04 08:57:55.555 [main] Main - Validating rule E046 - Fast travel between stops
[ERROR] 2021-01-04 08:57:55.616 [main] Main - Error detected during data validation -- ABORTING
[INFO ] 2021-01-04 08:57:55.616 [main] Main - Set option -abort_on_error to false for validation process to continue on errors
[INFO ] 2021-01-04 08:57:55.660 [main] Main - Results are exported as JSON by default
[INFO ] 2021-01-04 08:57:55.662 [main] Main - Computed relative path for report file: P-\github\gtfs-validator\output\AC_TRANSIT__AC_TRANSIT__2021-01-04_11-57-55.6391348
[INFO ] 2021-01-04 08:57:55.702 [main] Main - Exporting validation repo content:[
Notice{filename='null', level='INFO', code='1', title='Info notice', description='More information regarding the validation process', extra='{feedPublisherNameOrAgencyName=AC TRANSIT, errorNoticeCount=1, gtfsArchiveSizeBeforeUnzippingByte=8558468, processingTimeSecs=0, validationTimestamp=2021-01-04 11:57:55.6181258, gtfsValidatorVersion=TODO, warningNoticeCount=5, processedFilenameCollection=[stops.txt, trips.txt, feed_info.txt, agency.txt, calendar.txt, stop_times.txt, calendar_dates.txt, routes.txt, shapes.txt], pathOrUrlToGtfsArchive=C:\Users\mpaine\Downloads\old\gtfs\2012WR-v2\Google.zip, gtfsArchiveSizeAfterUnzippingByte=40100834}'},
Notice{filename='routes.txt', level='WARNING', code='8', title='`route_long_name` contains `route_short_name`', description='`route_long_name` contains `route_short_name`:`90` in file:`routes.txt`. `route_long_name` and should not contain the `route_short_name`.', noticeSpecific='{}'},
Notice{filename='routes.txt', level='WARNING', code='8', title='`route_long_name` contains `route_short_name`', description='`route_long_name` contains `route_short_name`:`98` in file:`routes.txt`. `route_long_name` and should not contain the `route_short_name`.', noticeSpecific='{}'},
Notice{filename='routes.txt', level='WARNING', code='8', title='`route_long_name` contains `route_short_name`', description='`route_long_name` contains `route_short_name`:`14` in file:`routes.txt`. `route_long_name` and should not contain the `route_short_name`.', noticeSpecific='{}'},
Notice{filename='routes.txt', level='WARNING', code='8', title='`route_long_name` contains `route_short_name`', description='`route_long_name` contains `route_short_name`:`P` in file:`routes.txt`. `route_long_name` and should not contain the `route_short_name`.', noticeSpecific='{}'},
Notice{filename='routes.txt', level='WARNING', code='8', title='`route_long_name` contains `route_short_name`', description='`route_long_name` contains `route_short_name`:`73` in file:`routes.txt`. `route_long_name` and should not contain the `route_short_name`.', noticeSpecific='{}'},
Notice{filename='stop_times.txt', level='ERROR', code='46', title='Fast travel between stops', description='Fast travel detected in trip:`4145020` over stop sequence:[15, 16]. Calculated speed: 270.0kmh', extra='{compositeKeyFirstPart=trip_id, stopTimeStopSequenceList=[15, 16], compositeKeyFirstValue=4145020, compositeKeySecondPart=stop_sequence_list}'}]
[ERROR] 2021-01-04 08:57:55.710 [main] Main - Could not export results as file: P-\github\gtfs-validator\output\AC_TRANSIT__AC_TRANSIT__2021-01-04_11-57-55.6391348.json
[INFO ] 2021-01-04 08:57:55.712 [main] Main - Took 00h 00m 15s

**Comment by mpaine-act** [comment]
I just got it to work, thanks again.
