### ISSUE TITLE
Confirm that trips sharing a block cannot overlap

### ISSUE THREAD

**Issue by mcplanner** [MobilityData/gtfs-validator#580]
Error 54 states that "block trips must not have overlapping stop times". Where does this requirement come from? I understand the logic, but has a consumer indicated this is a problem for them?

Full content of the error message (as an example):
Notice{filename='trips.txt', level='ERROR', code='54', title='Block trips must not have overlapping stop times', description='Trips with `trip_id`: `15141366-NC2010-NCTD-Weekday-06` (first time: `16:06:00`, last time: `17:00:00`) and `15245013-NC2010-NCTD-Holiday1-11-1111111` (first time: `16:06:00`, last time: `17:00:00`) from block: `30301` overlap. Conflicts happen on: [tuesday, wednesday, thursday, friday, monday].', extra='{blockId=30301, tripFirstTime=16:06:00, previousTripFirstTime=16:06:00, previousTripId=15245013-NC2010-NCTD-Holiday1-11-1111111, conflictingDateList=[tuesday, wednesday, thursday, friday, monday], previousTripLastTime=17:00:00, tripId=15141366-NC2010-NCTD-Weekday-06, tripLastTime=17:00:00}'},

**Comment by barbeau** [comment]
@mcplanner This rule is implemented in the original Google [GTFS Python validator](https://github.com/google/transitfeed/wiki/FeedValidator), so implementation in this tool was part of reaching feature parity with the Python validator. Here's the Python validator rule implementation:
https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/schedule.py#L1205

...and the error text:
https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/problems.py#L754

**Comment by mcplanner** [comment]
Got it, thank you!
