### ISSUE TITLE
CI environment Java runtime doesn't match source code

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-validator#593]
**Summary**
In our `build.gradle` we currently have:

```groovy
sourceCompatibility = JavaVersion.VERSION_1_8
```

...which indicates that the project can be compiled and run on JRE 8 or higher.

However, our CI configuration, for example:
https://github.com/MobilityData/gtfs-validator/blob/master/.github/workflows/test_pack_doc.yml#L35

...runs on JDK 11. As an end result we could have code sneak in that's not compatible with Java 8.

**What I expect**

CI Java runtime should match project code - if we say the project runs on Java 8, we need to test on Java 8. It's ok to test on 8 and 11 both (not sure if that's possible with GitHub Actions).

**What I see**

Code says it runs on Java 8, but we're only testing on JDK 11, which may pass on new variables that were added to Java after Java 8 (e.g., `LocaDate.EPOCH`), but result in errors when running on Java 8.

**Comment by aababilov** [comment]
We have JDK 11 at Google, so I am sending
https://github.com/MobilityData/gtfs-validator/pull/595

Alexej Ababilov | ru, uk, pl, it, es, fr, pt, ro, en, de, sv, nl | Senior
Software Engineer | Maps Transit


Den tors 14 jan. 2021 kl 07:42 skrev Sean Barbeau <notifications@github.com

**Comment by barbeau** [comment]
Re-opening, looks like we still have Java 8 on the end-to-end CI test:
https://github.com/MobilityData/gtfs-validator/runs/1703698539?check_suite_focus=true

```
> Configure project :
System.getenv("CI"): true - System.getenv("versionTag"): v-master-sha-35c46277-SNAPSHOT
> Task :core:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileJava'.
> Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.
```
