### ISSUE TITLE
Improve memory footprint of Notice classes

### ISSUE THREAD

**Issue by ghost** [MobilityData/gtfs-validator#62]
**Is your feature request related to a problem? Please describe.**
The validator runs out of memory pretty quickly when it generates multiple notices.

**Describe the solution you'd like**
Leads:
- static title
- static description pattern. Generate complete description only when required
- ...

**Comment by barbeau** [comment]
In the GTFS RT validator, we made the validation rules their own Java objects, which contained the String title, class, general description, and the part of the error message that was the same for all occurrences that violated that rule:
https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/validation/ValidationRules.java#L32

Like:

~~~
    public static final ValidationRule E001 = new ValidationRule("E001", "ERROR", "Not in POSIX time",
            "All timestamps must be in POSIX time (i.e., number of seconds since January 1st 1970 00:00:00 UTC)",
            "is not POSIX time");
~~~

Then, at runtime for each occurrence of the error would would only need to store a reference to this rule as well as a string to concatenate to the error message. For example, if the POSIX value was `1234567890`, then we would just store "1234567890" as a string for that occurrence, and concatenate it to the rest of the message that was the same for all occurrences whenever we had to output to human-readable form, which would give us "1234567890 is not POSIX time".

**Comment by fabrice-v** [comment]
Thks. Definitely something to get inspiration from. Considering the avenue of using [Sting.format](https://www.javatpoint.com/java-string-format) with the format a static member.

**Comment by barbeau** [comment]
Closing - addressed by v2 architecture
