### ISSUE TITLE
[REQUEST] Extend tests of notice repository to find memory limits

### ISSUE THREAD

**Issue by fabrice-v** [MobilityData/gtfs-validator#63]
**Is your feature request related to a problem? Please describe.**
Right now the validator quickly runs out of memory when generating notices

**Describe the solution you'd like**
We need automated tests to figure out. the memory limits of our notices repository implementation.
Two kinds of tests
- test that pass when memory is not exhausted for a given number of notices
- tests that pass when memory IS exhausted for a given number of notices
Those trests will allow to monitor memory footprint progress as well as prevent regressions.

**Comment by barbeau** [comment]
Here are the three implementations high level implementations / adaptors I can think of for the notice repository:
1. In memory (`InMemoryValidationResultRepository`)
1. File-based
1. Database-based

I'm assuming the tests are intended to measure memory use of 1) at the moment, but could potentially be used for 2) and 3) too.

>tests that pass when memory IS exhausted for a given number of notices

How are you planning on testing this?

**Comment by fabrice-v** [comment]
Yes, tests are intended for case 1

As for testing memory exhaustion, we're not sure yet how the testing framework behaves but we are expecting something along the line of an exception being raised. So a valid test would check such exception is raised.

**Comment by fabrice-v** [comment]
PR #65 can be merged in it's current state
