### ISSUE TITLE
[REQUEST] Support command-line release of JAR file

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-validator#66]
**Is your feature request related to a problem? Please describe.**
Currently, the release process is very manual:
https://github.com/MobilityData/gtfs-validator/blob/master/RELEASE.md

This process is labor intensive and prone to mistakes.

**Describe the solution you'd like**
We should be able to support a command-line release such as `mvn deploy` or `gradlew assembleRelease`. This allows for a simpler release process that is less prone to errors and could eventually be used to build releases automatically via CI and Git tags.

We should also support minification to try and reduce the size of the output JAR file.

Gradle plugins to investigate:
* https://github.com/johnrengelman/shadow

**Describe alternatives you've considered**
Do nothing - leave release process as-is

**Comment by fabrice-v** [comment]
I'd suggest we avoid using Maven as to keep things streamlined around Gradle

**Comment by barbeau** [comment]
@fabrice-v Yes, if possible, I agree - I only intended the mention of `mvn deploy` to be an example of a general command to package an application.
