### ISSUE TITLE
Update RULES.md

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#714]

**Comment by barbeau** [comment]
@lionel-nj In the future, let's add a short description to each of these issues, even if it's planned to be short-lived, so we have a record of why something is done. Ideally this would have had a "The current docs ...., and therefore we need to update them by ...." sentence.

**Comment by lionel-nj** [comment]
Just seeing this comment now @barbeau - yes, will do! Thanks :)
