### ISSUE TITLE
Abort on first error

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#760]
**Is your feature request related to a problem? Please describe.**
At present the validation process stops on parsing errors by printing a big error message.

However, when it comes to semantic rules, the validator does not stop after the first error.
Until v1.4.0, we used to abort the validation process after the first error was encountered because the validator's behavior cannot be predicted and guaranteed after the first `ERROR`. 
For example: a missing required field in `agency.txt` or `feed_info.txt` would:
- first generate a `MissingRequiredFieldNotice` (which is an `ERROR`), 
- but this could also lead to the validator issuing erroneous notices in `AgencyConsistencyValidator`.

Implementing the same process would: 
- ease the task of analyzing validation reports in integration tests
- allow us to provide validation reports of better quality

**Proposed solution**
execute `System.exit` method as soon as a notice of `ERROR` type is added to (one of) the `noticeContainer`. 

**Additional context**
#734

**Comment by lionel-nj** [comment]
If implemented, this  should be implemented before writing integration tests.

@barbeau @aababilov: can I have your feedback on the best way to approach implementation? 

@carlfredl if implemented, this should be considered in the sprint planning :)

**Comment by carlfredl** [comment]
Agreed that this makes sense to include but we should allow users to toggle this feature.

**Comment by lionel-nj** [comment]
Closing as:

> we can work on more targeted solutions within validators (see some thoughts in https://github.com/MobilityData/gtfs-validator/pull/765#issuecomment-785200442) when we know that bad data could influence a validator's output.
