### ISSUE TITLE
Fail gracefully on Out Of Memory exception

### ISSUE THREAD

**Issue by ghost** [MobilityData/gtfs-validator#77]
**Is your feature request related to a problem? Please describe.**
Right now, the validator crashes and stop without outputting anything if it consumes too much memory.

**Describe the solution you'd like**
Have mechanism in place for:
- output notices form notices repo on some defined validating steps
  - add a new `partialExport` or `export`  or something use case and run it as specific gates in the validation process
- detect and catch the out of memory exception to fail gracefully

**Additional context**
https://github.com/MobilityData/gtfs-validator/pull/65#discussion_r393691253

**Comment by barbeau** [comment]
Instead of putting effort into a solution to fail gracefully on the `InMemoryValidationResultRepository` running out of memory, I think it would make more sense to put effort into implement a results repo that isn't as likely to encounter memory issues. 

One such example is to stream write the output (instead of keeping it in memory) using something like Jackson's JSON streaming API:
https://github.com/FasterXML/jackson-docs/wiki/JacksonStreamingApi

Or appending to a CSV, if the results are a relatively flat file.

Or, a database-backed solution.

**Comment by fabrice-v** [comment]
Good point. Our solution must also support protobuf export. Work started in branch https://github.com/MobilityData/gtfs-validator/tree/notice-repo-export to come up with a generic export solution and a first protobuf implementation. Not sure if it qualifies as a streaming solution. 
Maybe we could also have only a JSON streaming export and a generic way to implement different conversion from there?

**Comment by barbeau** [comment]
>Maybe we could also have only a JSON streaming export and a generic way to implement different conversion from there?

That seems reasonable to me - you'd need to support streaming JSON import as well to be able to handle the data conversion step.

Writing to a single huge PB will be challenging - see:
https://developers.google.com/protocol-buffers/docs/techniques

>Protocol Buffers are not designed to handle large messages. As a general rule of thumb, if you are dealing in messages larger than a megabyte each, it may be time to consider an alternate strategy.

One possible way to handle this is to output all notices to JSON via a streaming API, and then write only a summary subset to a single PB, which would be a repeated list of notices.

For example, if you have 1,000 occurrences of the same warning or error, writing only the first 10 may be sufficient to indicate to the producer that there is something systemic that they need to resolve.

Or, you could write each Notice to it's own PB file, but that's going to generate hundreds if not thousands of files.

**Comment by fabrice-v** [comment]
Ok, I'll pause work on the notice-repo-export and open a new branch from master to implement JSON streaming output. Additioned to the fact we can now do basic validation on all files will be our first stable release.

**Comment by fabrice-v** [comment]
Ok, from the current situation, work in the branch will be altered to support a single file per notice, non streaming model for notice export in both JSON and protobuf. Then I'll open an issue for the streaming version of the repo. That way we will be able to merge and release this week our first stable version.

**Comment by barbeau** [comment]
Closed by https://github.com/MobilityData/gtfs-validator/pull/596
