### ISSUE TITLE
Review notice/feature migration before v2 release

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#785]
## **Feature request**
It appears from https://github.com/MobilityData/gtfs-validator/pull/781 that some notices from v1 do not have a v2  mapping. 
Some rules might be missing for v1 parity or they could be implemented as part of other v2 rules we haven't tracked in #781. 
These notices should be reviewed.

**Additional context**
https://github.com/MobilityData/gtfs-validator/pull/781#discussion_r585904679

**Comment by lionel-nj** [comment]
Notices from v1 that do not have a v2 mapping:
- [E008](https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/RULES.md#E008)
- [E019](https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/RULES.md#E019)
- [E031](https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/RULES.md#E031)
- [E059](https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/RULES.md#E059)
- [E060](https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/RULES.md#E060)
- [E061](https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/RULES.md#E061)
- [W001](https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/RULES.md#W001)
- [W006](https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/RULES.md#W006)
- [W007](https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/RULES.md#W007)
- [W008](https://github.com/MobilityData/gtfs-validator/blob/v1.4.0/RULES.md#W008)

**Comment by barbeau** [comment]
@lionel-nj For OOM and other runtime exceptions (E60, E61), these will get caught and logged in GtfsFeedLoader line 120 as a `RuntimeExceptionInLoaderError`.

**Comment by lionel-nj** [comment]
Thanks @barbeau! Will update the documentation.
