### ISSUE TITLE
[REQUEST] Optimize memory usage for GTFS Shape entity

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-validator#79]
**Is your feature request related to a problem? Please describe.**
Currently, in https://github.com/MobilityData/gtfs-validator/pull/70 we are storing each `shapes.txt` record as a `Shape` object. `Shape` and stop_times.txt are the two GTFS files that will likely consume the vast majority of memory for GTFS entities, as they are typically the two largest files in the feed.

**Describe the solution you'd like**

We can reduce the amount of memory for `Shape` considerably, from two perspectives:
1. The String `shapeId` is the same for each point in the trip - we only need to store it once per trip
1. The lat/lon points for the trip can be losslessly compressed from `float`s to an encoded polyline, which is a variable-length String depending on the number of points (see https://developers.google.com/maps/documentation/utilities/polylinealgorithm - there are libraries as well, such as [this code](https://github.com/googlemaps/android-maps-utils/blob/master/library/src/main/java/com/google/maps/android/PolyUtil.java#L490))

A new object to hold the shape info for each trip (e.g., `Shape`) could have these fields:
* `String shapeId`
* `String encodedPolyline // The points of the shape`
* `float[] shape_dist_traveled // (if this optional field exists)`

(Not that a shape_id can be re-used in more than one trip, so we don't want to have this data inside a trip object)

The new optimized process to read `shapes.txt` into memory could be:
1. Read all records for a given `shape_id` into `Shape` entity `List`
1. Sort list by increasing `shape_pt_sequence`
1. Encode lat/longs for list of `Shape` entities into `encodedPolyline`
1. (If optional field `shape_dist_traveled` exists) Store all `shape_dist_traveled` values of `Shape` entities into the `shape_dist_traveled` array

We could also optionally simplify the shape before encoding it to something like decimeter level precision to reduce the number of points, although this is a lossy operation.

**Describe alternatives you've considered**
Do nothing

**Additional context**
https://github.com/MobilityData/gtfs-validator/pull/70

**Comment by lionel-nj** [comment]
Implemented in #70

**Comment by lionel-nj** [comment]
Working on this.
