### ISSUE TITLE
Improve DuplicateRouteNameValidator

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#805]
## **Feature request**

**Is your feature request related to a problem? Please describe.**
At present, `DuplicateRouteNameValidator` performs a non -efficient operation that leads to memory fragmentation. 

**Proposed solution**
Replace String concatenation by the use of an hashcode. 

**Additional context**
https://github.com/MobilityData/gtfs-validator/pull/779#discussion_r593996579

**Comment by barbeau** [comment]
@lionel-nj I believe this applies to a few of the other validators as well, including `DuplicateFareRuleZoneIdFieldsValidator`. Let's change them all to be consistent.

**Comment by lionel-nj** [comment]
Opened #812 to this extent.
