### ISSUE TITLE
Warn if route_short_name and the route_long_name are not both provided

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#807]
## **Feature request**

**Is your feature request related to a problem? Please describe.**
In an attempt to implement rule from v1.4.0, https://github.com/MobilityData/gtfs-validator/pull/797 was created. It appears that this rule might not be relevant because of the use of `routes.route_short_name` and  `routes.route_long_name` as suggested by @aababilov in https://github.com/MobilityData/gtfs-validator/pull/797#discussion_r593981927: 

> I am unsure if we need this check. Here is some statistics from all prod feeds at Google.
> - 45% give both names
> - 35% give ONLY long name
> - 20% give ONLY short name
> Less than a half routes give both names and I think that makes sense. Real-world transit routes may indeed have just one name. If we issue warnings, that may push some GTFS providers to invent short or long names that never existed in the real world just to satisfy the validator.
> 
> Ceterum censeo Python validator should be taken with a grain of salt. It was never used on a wide range of feeds and before porting a validation rules from Python, we should have evidence that it's a meaningful rule

**Proposed solution**
Study the use of this rule with @MobilityData/transit-specs and get feedback from other data consumers before implementation.

**Additional context**
https://github.com/MobilityData/gtfs-validator/pull/797

**Comment by timMillet** [comment]
I think we can remove the warning in case the route_short_name and the route_long_name are not both provided together. Spec and Best Practices say:
> potentially both if appropriate

If it’s not appropriate to provide both, we don't want to push producers to invent names.

Same comment in https://github.com/MobilityData/gtfs-validator/pull/797#issuecomment-800289097

**Comment by aababilov** [comment]
I propose to close that issue as "intended behaviour".

**Comment by lionel-nj** [comment]
> I propose to close that issue as "intended behaviour".

Closing.
