### ISSUE TITLE
Frequencies.txt exact_times=0 trips must not have stop_times.timepoint=1 records

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-validator#823]
**Is your feature request related to a problem? Please describe.**
There is an optional field in stop_times.txt `timepoint` that is used to specify a timepoint that a transit vehicle should strictly adhere to (e.g., hold if they are running early). If a trip is defined in frequencies.txt with the exact_times=0 value, then it is a frequency-based trip, which means that a schedule doesn't exist. 

Therefore, frequency-based trips with exact_times=0 should NOT have any timepoint=1 values in stop_times.txt - the field should either be 0 or blank.

**Proposed solution**
New rule - if a GTFS dataset has stop_times.timepoint=1 for any trips in frequencies.txt with exact_times=0, that is an error.

**Comment by lionel-nj** [comment]
Closing for now as we will not implement this invariant - we might revisit this in the future following spec clarification.
