### ISSUE TITLE
Add command-line parameter to output "pretty" JSON

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-validator#838]
**Is your feature request related to a problem? Please describe.**
My workflow when running the validator is typically:
1. Run the validator
2. Copy/paste the `report.json` file into a JSON formatter like https://jsonformatter.curiousconcept.com/ so it's readable (by default the JSON file is only one line without any whitespace). If the report file is big I'll open it in an application like NotePad++ and use the JSON formatter plugin.

**Proposed solution**

I'd like to add a command-line parameter (e.g., `-p` or `--pretty`) that would allow users to specify that they want readable JSON that can directly be viewed in any text editor without having to be formatted. Note that we want to keep the default to the more efficient single-line output for efficiency when using it primarily as a machine readable format between applications.

We're using GSON to output the JSON data, so looks like pretty print can be enabled with a single line of code when instantiating the `Gson` object:

```java
Gson gson = new GsonBuilder().setPrettyPrinting().create();
```

So this change would mainly entail implementing the command-line parameter and piping it through to the notice container.

**Describe alternatives you've considered**
Do nothing - keep copy/pasting the output to read it

**Comment by lionel-nj** [comment]
Thanks for the suggestion! Implementing this could be a first first towards improving the output visualisation before actually developing a UI for the results (see roadmap on the [wiki](https://github.com/MobilityData/gtfs-validator/wiki/Roadmap#results-ui)). We will consider it when planning future sprints.

**Comment by thbar** [comment]
In the mean time, one can also pipe the output into tools like [jq](https://github.com/stedolan/jq), which pretty prints & color stuff by default.
