### ISSUE TITLE
Create a git repository or a folder to store documentation

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#85]
**Is your feature request related to a problem? Please describe.**

We should have a place (inside the project on github?) to store documentation including javadoc and .proto files.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fabrice-v** [comment]
After reflexion, the image should live either in an other repository or the MobilityData Google Drive, and links can be generated through GitHub issues.

**Comment by fabrice-v** [comment]
We need documentation regarding two aspects
- the GTFS issues/rules the validator is checking the dataset against. See for reference: https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fgithub.com%2FCUTR-at-USF%2Fgtfs-realtime-validator%2Fblob%2Fmaster%2FRULES.md
Use a Google drive drawing type document to have an architecture diagram of our modules, maybe down to some specific important classes as well. @maximearmstrong

**Comment by barbeau** [comment]
Closing - documentation exists in https://github.com/MobilityData/gtfs-validator/tree/master/docs
