### ISSUE TITLE
Invalid phone number seems to be producing false positives

### ISSUE THREAD

**Issue by mcplanner** [MobilityData/gtfs-validator#856]
## **Bug report** 

**Describe the bug**
AC Transit and BART both produced `invalid_phone_number` errors, though their numbers are correct.

AC Transit: [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '5108914777'}]
BART: [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '510-464-6000'}]

**Expected behaviour**
An error should not have been given.

**Observed behaviour**
An error code was given.

**Environment versions**
- validator version: 2.0.0
- docker file: https://github.com/cal-itp/gtfs-validator-api/blob/main/Dockerfile

**Comment by mcplanner** [comment]
This is the most common error we've been able to produce. More examples:


AC Transit | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '5108914777'}]
-- | --
Bay Area Rapid Transit | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '510-464-6000'}]
Bear Transit | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '(510) 643-5708'}]
Caltrain | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '800-660-4287'}]
Capitol Corridor | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '877-974-3322'}]
Cloverdale Transit | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '(707) 576-7433'}]
County Connection | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '925-676-7500'}]
Golden Gate Bridge Highway and Transportation District | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '(415) 455-2000)'}]
Marguerite Shuttle | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '650-723-9362'}]
Marin Transit | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '415-455-2000'}]
MVGO | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '(650) 933-2518'}]
Petaluma Transit | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '(707)778-4303'}]
Rio Vista Delta Breeze | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '(707) 374-2878'}]
Sage Stage | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '(530) 233-6410'}]
Santa Clara Valley Transportation Authority | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '408-321-2300'}]
SolanoExpress | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '(707) 648-4666'}]
Sonoma County Transit | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '(707) 576-7433'}]
Sonoma-Marin Area Rail Transit | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '(707)794-3330'}]
South County Transit Link | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '(209) 745-3052'}]
Tideline | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '415-339-0196'}]
Vacaville City Coach | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '707-449-6000'}]
Vine Transit | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '707-251-2800'}]
WestCAT | [{'filename': 'agency.txt', 'csvRowNumber': 2, 'fieldName': 'agency_phone', 'fieldValue': '510-724-7993'}]

**Comment by lionel-nj** [comment]
Thanks @mcplanner for opening an issue regarding this. @MobilityData/tools-and-services will analyze.

**Comment by lionel-nj** [comment]
Could you provide urls to download the GTFS datasets used please? So that we are able to reproduce the errors.

**Comment by mcplanner** [comment]
I knew I forgot something!

https://api.actransit.org/transit/gtfs/download?token=2512B81107A09D2DC44895CDDC650D47
https://www.bart.gov/dev/schedules/google_transit.zip

**Comment by lionel-nj** [comment]
Thanks!

**Comment by lionel-nj** [comment]
@mcplanner Could you provide the command line input used to validate these GTFS datasets please?

**Comment by machow** [comment]
Hey, I think this may be related to #858--since I did not specify the correct country code, maybe the validation rule for phone numbers was expecting a different format? I'm fixing now, and can double check the corrected validator output for phone numbers.

**Comment by lionel-nj** [comment]
Looks like it has been solved. You are welcome to re-open it if anything.
