### ISSUE TITLE
Best Practice:  feed_info.txt should be provided (WARNING)

### ISSUE THREAD

**Issue by e-lo** [MobilityData/gtfs-validator#877]
Lack of  `feed_info.txt` should all trigger a WARNING because the file is required in the GTFS Best Practices. 

Should probably mirror or extend [MissingRequiredFileNotice](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#MissingRequiredFileNotice) to allow for a parameter to indicate `SeverityLevel.WARNING` 

https://github.com/MobilityData/gtfs-validator/blob/52434454b747bb4085038f27563e98fee6018ca5/core/src/main/java/org/mobilitydata/gtfsvalidator/notice/MissingRequiredFileNotice.java#L27-L29

**Comment by scmcca** [comment]
Indeed it is recommended for [`feed_info.txt`](https://github.com/MobilityData/GTFS_Schedule_Best-Practices/blob/master/en/feed_info.md).

Maybe I'm missing something, but I don't see recommendations for providing the [`agency.txt`](https://github.com/MobilityData/GTFS_Schedule_Best-Practices/blob/master/en/agency.md) or [`shapes.txt`](https://github.com/MobilityData/GTFS_Schedule_Best-Practices/blob/master/en/shapes.md) file in the GTFS Best Practices.

**Comment by e-lo** [comment]
Good call - `agency.txt` is actually a required file so that should be checked against the spec and `shapes.txt` inclusion is not a best practice....but should be! (otherwise you are leaving interpretation up to each consuming app).

Updated issue name to be consistent.

**Comment by lionel-nj** [comment]
>  `agency.txt` is actually a required file so that should be checked against the spec 

This is the case, @e-lo have you witnessed dataset where `agency.txt` is missing but the validation report did not flag it?

**Comment by e-lo** [comment]
> This is the case, @e-lo have you witnessed dataset where agency.txt is missing but the validation report did not flag it?

Nope nope!  Sorry for false alarm on that one.

**Comment by aababilov** [comment]
I would introduce a `MissingRecommendedFileNotice` and also `MissingRecommendedFieldNotice` with SeverityLevel.WARNING. I generally think that each notice type should have a fixed priority - this is easier to handle in human-readable validation reports and this is easier to setup exceptions for certain feeds that demonstrate errors that we want to skip.

We may add a `@Recommended` annotation that would work in a similar way to `@Required`.
