### ISSUE TITLE
Best Practice: stop names should be in mixed case (WARNING)

### ISSUE THREAD

**Issue by e-lo** [MobilityData/gtfs-validator#881]
Provide stop names in mixed case, following local conventions, as per recommendation for all customer-facing text fields.

**Comment by lionel-nj** [comment]
Thanks for flagging that. We will determine a list of customer-facing text fields to check.

**Comment by lionel-nj** [comment]
@aababilov here I think that we could definitely use annotations to avoid boiler plate code.

**Comment by lionel-nj** [comment]
@aababilov Would this be a good use case of annotations?

**Comment by lionel-nj** [comment]
> Thanks for flagging that. We will determine a list of customer-facing text fields to check.

Here it is, thanks @scmcca
> 
> agency.agency_name
> stops.stop_name
> stops.stop_desc
> routes.route_short_name
> routes.route_long_name
> routes.route_desc
> trips.trip_headsign
> trips.trip_short_name
> pathways.signposted_as
> pathways.reversed_signposted_as
> levels.level_name

**Comment by KClough** [comment]
> @aababilov Would this be a good use case of annotations?

@maximearmstrong @bdferris 

Wanted to bump this question up, I think it makes sense to me to use annotations for this functionality. What do you think?
