### ISSUE TITLE
Best Practice: feed_info should include start_date, end_date, version, email, url (WARNING)

### ISSUE THREAD

**Issue by e-lo** [MobilityData/gtfs-validator#885]
`feed_info.txt` should Includes valid fields for:

- feed_start_date, feed_end_date 
- Feed_version.
- Feed_email
- feed_url
-

**Comment by lionel-nj** [comment]
Agreed, as suggested per best practice:

> `feed_info.txt` should be included, with all fields below.
> 
> | Field Name | Recommendation |
> | --- | --- |
> | feed_start_date & feed_end_date | Should be included |
> | feed_version | Should be included |
> | feed_contact_email & feed_contact_url | Provide at least one |

https://github.com/MobilityData/GTFS_Schedule_Best-Practices/blob/master/en/feed_info.md

**Comment by KClough** [comment]
@isabelle-dr can we mark this issue as closed? 

This has been implemented in #1157 , I probably should have put "resolves" instead of "related" in the PR description.

**Comment by isabelle-dr** [comment]
I think what closes automatically an issue is writing "closes #issue number" in a PR :)

Closing this issue, thanks for adding this to this project!
