### ISSUE TITLE
Best Practice: Date Validity (WARNING)

### ISSUE THREAD

**Issue by e-lo** [MobilityData/gtfs-validator#886]
Per the best practices:
- Dataset should be valid for at least the next seven days [ from publication date? ]
- Dataset shouldn't include date ranges that have already ended [ No expired calendars ]

**Comment by aababilov** [comment]
Thanks for filing that issue.

What do you want to use as the start and end date for a dataset? Google uses a so called majority service date. Does that sound OK to you?

**Comment by lionel-nj** [comment]
@aababilov  Very interesting! How is this majority service date defined?

**Comment by lionel-nj** [comment]
> Dataset should be valid for at least the next seven days [ from publication date? ]

From anytime. The best practices say:
> **At any time**, the published GTFS dataset should be valid for at least the next 7 days [...]
http://gtfs.org/best-practices/#dataset-publishing--general-practices

This rule is checked by `FeedExpirationDateValidator` here:

https://github.com/MobilityData/gtfs-validator/blob/4824a4c839d8f4c84c866c492e9c925f70dd6f51/main/src/main/java/org/mobilitydata/gtfsvalidator/validator/FeedExpirationDateValidator.java#L42

**Comment by aababilov** [comment]
> @aababilov Very interesting! How is this majority service date defined?

We find the max amount of trips per day (`MAX_TPD`), then find the first and last days that demonstrate more than `0.75 * MAX_TPD` trips per day. That is the majority service window.

This captures the date range when a significant number of trips are running, relative to the max number of trips on a single day in the feed. This helps detect when a single trip has caused a feed to appear "active" even though the bulk of service is no longer running.

**Comment by aababilov** [comment]
> At any time, the published GTFS dataset should be valid for at least the next 7 days [...]
> http://gtfs.org/best-practices/#dataset-publishing--general-practices

This rule is quite ambiguous when it comes to implementation. There are at least 3 ways to find when the dataset is valid.

* `feed_info.feed_start_date` and `feed_end_date` - the file is optional and the fields are also optional
* trip coverage
* majority trip coverage described above and used by Google

**Comment by lionel-nj** [comment]
> We find the max amount of trips per day (MAX_TPD), then find the first and last days that demonstrate more than 0.75 * MAX_TPD trips per day. That is the majority service window.
> 
> This captures the date range when a significant number of trips are running, relative to the max number of trips on a single day in the feed. This helps detect when a single trip has caused a feed to appear "active" even though the bulk of service is no longer running.

Thanks for clarifying this. 

> This rule is quite ambiguous when it comes to implementation. 

Indeed, @barbeau given that `feed_info.txt` is optional do you think that we should improve the implementation of `FeedExpirationDateValidator` to no longer rely on said file and use the majority trip coverage approach used at Google?

**Comment by barbeau** [comment]
>given that feed_info.txt is optional do you think that we should improve the implementation of FeedExpirationDateValidator to no longer rely on said file and use the majority trip coverage approach used at Google?

I think for validation you could check both `feed_info` and calculate majority trip coverage and flag if either of these looks wrong. I could see some consumers just relying on `feed_info` alone so we should still validate that.

**Comment by KClough** [comment]
@maximearmstrong / @isabelle-dr 

Before I dig deeply on this issue, I wanted to confirm my approach is sane and verify there isn't any existing logic that can be used to help calculate max amount of trips per day (`MAX_TPD`) /  majority service window.

**Here is my proposed way to calculate `MAXP_TPD`: **

Find min date between `calendar.txt` start dates and `feed_info.txt` start date.
Find max date between `calendar.txt` start dates and `feed_info.txt` start date.

For each day, find the relevant `serviceId`(s) from `calendar.txt`.

Calculate total number of trips for that day via `routes.txt` + `trips.txt`.

Find max of that total = `MAX_TPD`. 

Throw a new notice if any day in the next 7 days from `feed_info.txt` start date OR `calendar.txt` min date has a total number of trips <= 80% of `MAX_TPD`.
