### ISSUE TITLE
Bug: Unable to execute the download jar on command line

### ISSUE THREAD

**Issue by dancesWithCycles** [MobilityData/gtfs-validator#900]
Hi folks,
Thank you very much for creating and providing this repository. Please accept my appreciation!

I followed the [README](https://github.com/MobilityData/gtfs-validator/blob/master/README.md) to download and run the JAR file on the command line. However, I did not manage to execute the validator without failure yet.

Steps to reproduce the behaviour:
1. Go to [README](https://github.com/MobilityData/gtfs-validator/blob/master/README.md)
2. Download the offered JAR file (```gtfs-validator-v2.0.0_cli.jar```).
3. Call one of the following instructions.

```
java -jar gtfs-validator-v2.0.0_cli.jar -i ~/otp/vbn/vbn.gtfs.zip -o vbn.gtfs.vd.report
java -jar gtfs-validator-v2.0.0_cli.jar -i ~/otp/vbn/vbn.gtfs.zip -o vbn.gtfs.vd.report -c de
```

I expected the validator to validate the file ```vbn.gtfs.zip```.

Call:
```
java -jar gtfs-validator-v2.0.0_cli.jar -i ~/otp/vbn/vbn.gtfs.zip -o vbn.gtfs.vd.report
```
Answer:
```
Exception in thread "main" java.lang.NullPointerException
	at org.mobilitydata.gtfsvalidator.input.GtfsFeedName.parseString(GtfsFeedName.java:88)
	at org.mobilitydata.gtfsvalidator.cli.Main.main(Main.java:57)
```
Call:
```
java -jar gtfs-validator-v2.0.0_cli.jar -i ~/otp/vbn/vbn.gtfs.zip -o vbn.gtfs.vd.report -c de
```
Answer:
```
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -c
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at org.mobilitydata.gtfsvalidator.cli.Main.main(Main.java:49)

```

This is my test environment.
- validator version: ```gtfs-validator-v2.0.0_cli.jar```
- Java version: ```java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)```
- Java version: ```java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)```
- OS versions: ```Linux tpx200 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux```

As you can see, I tested the validator for the two Java version 8 and 11.

I appreciate any hint. Cheers!

**Comment by kannes** [comment]
I ran into the same issue :)

Maybe you could add a note in the readme? It links to the 2.0.0 jar file and then has the wrong usage instructions which is super confusing.

**Comment by isabelle-dr** [comment]
Hi @kannes!
We're working on this issue in PR #905 
Feel free to have a look and participate in the discussion :)
