### ISSUE TITLE
Validate conditionally required fields from translations.txt

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#906]
## **Feature request**

**Is your feature request related to a problem? Please describe.**
At present this extension is not fully implemented: verification of conditionally required fields is missing. 

**Proposed solution**
Implement a custom validator to check the conditionally required fields of said file.

**Comment by isabelle-dr** [comment]
Closing this because it's a dupplicate. 
Original issue 
https://github.com/MobilityData/gtfs-validator/issues/820
