### ISSUE TITLE
Add routes.route_url != agency.agency_url

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#907]
**The specification says**
field `routes.route_url`
> Should be different from the agency.agency_url value

**Error vs warning**
warning

**Comment by lionel-nj** [comment]
@isabelle-dr here I believe that the specification could be clarified. From my understanding: 
`routes.route_url != agency.agency_url` for the agency whose id matches the `id` provided in `routes.agency_id`. This last point could be added to the spec to ease comprehension. @MobilityData/transit-specs thoughts?
