### ISSUE TITLE
Add warning notice for suspicious time

### ISSUE THREAD

**Issue by ghost** [MobilityData/gtfs-validator#91]
**Is your feature request related to a problem? Please describe.**
There is no clear threashold value to consider a filed of gtfs type time to contain incorrect value.

**Describe the solution you'd like**
This issue is about implementing a suspicious threshold that could be user controlled through a command line option, defaulting to hour 29 as the latest possible value for time in a service day.

**Additional context**
https://github.com/MobilityData/gtfs-validator/pull/76#discussion_r396717291

**Comment by fabrice-v** [comment]
hold for now, we will revisit matter of default and user configurable thresholds after we get openmobilitydata.org set of datasets.

**Comment by barbeau** [comment]
Closing, not implementing thresholds at this time
