### ISSUE TITLE
Validation on continuous_pickup and continuous_drop_off

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#911]
Referencing [issue #311](https://github.com/MobilityData/gtfs-validator/issues/311), making this issue to add the new validation rule, keeping 311 for the discussion about ways to keep the validator up to date with the specs

Route entities should be updated with the following fields:
- continuous_drop_off
- continuous_pickup

Describe the solution you'd like
- Add new fields to GTFS entity
- Verify enum values
- update tests

**Comment by lionel-nj** [comment]
Closing as this rule is implemented in https://github.com/MobilityData/gtfs-validator/pull/486
