### ISSUE TITLE
[REQUEST] Command line option to specify range for numeric fields

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#92]
**Is your feature request related to a problem? Please describe.**

Numeric fields such as `min_transfer_time` require ranges for the validation process. These are by default set in the schema file. However, these default value are not always applicable for every agency which often leads to the generation of notices such as IntegerFieldValueOutOfRangeNotice that do not represent inconsistencies from the GTFS dataset to be validated.

![Capture d’écran, le 2020-03-27 à 18 31 55](https://user-images.githubusercontent.com/35747326/77806016-d8356680-7059-11ea-9303-543d93d29959.png)

To reproduce phenomemon, run this configuration:
` -u https://openmobilitydata.org/p/sbb-cff-ffs/793/latest/download -z input.zip -i input -o output
`

**Describe the solution you'd like**

It should be possible to manually specify ranges for numeric fields such as `min_transfer_time` from the line command since this particular kind of information depends on the agency providing the GTFS.

**Describe alternatives you've considered**

**Additional context**

**Comment by fabrice-v** [comment]
After discussion, we shall update the schema for now if the data is not obviously.
