### ISSUE TITLE
Add validation on levels.txt presence

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#921]
The specification in Dataset Files says:
> Conditionally Required:
> - Required when describing pathways with elevators (pathway_mode=5).
> - Optional otherwise.

**Error vs warning**
error

**Comment by aababilov** [comment]
I would extend this requirement. If there is an elevator, then it must connect two locations that have `level_id` field assigned.

**Comment by lionel-nj** [comment]
> I would extend this requirement. If there is an elevator, then it must connect two locations that have level_id field assigned.

Makes sense to me! @isabelle-dr one more thing that we could add to the discrepancy list, thoughts?

**Comment by isabelle-dr** [comment]
Agreed with @aababilov.
I would even add a third verification that I think is missing.
If an elevator is described in `pathways.txt`:
1- The file levels.txt has to be present
2- The level_id has to be present in the two stops referenced in `from_stop_id` and `to_stop_id fields`
3- The `location_type` of the two stops referenced can't have the value 1 (station)

Spec in `pathways.from_stop_id` and `pathways.to_stop_id`:
> Values for stop_id that identify stations (location_type=1) are forbidden.

This makes me realise that maybe the field `level_id` should be described as conditionally required, not optional? @MobilityData/transit-specs

**Comment by scmcca** [comment]
Are there cases where stairs, escalators, and elevators are short enough that they are considered to be on the same level?

**Comment by lionel-nj** [comment]
> Agreed with @aababilov.
> I would even add a third verification that I think is missing.
> If an elevator is described in pathways.txt:
> 1- The file levels.txt has to be present

Done in #966.

> 2- The level_id has to be present in the two stops referenced in from_stop_id and to_stop_id fields
> 3- The location_type of the two stops referenced can't have the value 1 (station)

WIP in https://github.com/MobilityData/gtfs-validator/pull/967

**Comment by lionel-nj** [comment]
> Are there cases where stairs, escalators, and elevators are short enough that they are considered to be on the same level?

@barbeau thoughts?

**Comment by barbeau** [comment]
I haven't spent a lot of time with pathways so I'm probably not the best one to ask, but there could be cases where there are a single or few steps that would be considered on the same level that you'd want to model for accessibility so someone in a wheelchair would know they couldn't use that route. But I haven't seen enough data to know of a real-world case like that.

**Comment by scmcca** [comment]
Just re-reading this thread. I think the two following statements do not have the same meaning:

> If there is an elevator, then it must connect two locations that have level_id field assigned. (@aababilov)

> The level_id has to be present in the two stops referenced in from_stop_id and to_stop_id fields (@isabelle-dr)

The first statement has the loose requirement that an elevator must connect locations with `level_id` defined. Also, it makes no reference to the `level_id` being different between locations connected by an elevator, which might be a favourable description given the possibility that a short elevator could be considered on the same level. 

The second statement is quite different. It states that a given `level_id` (suggested by the language of "the" `level_id`) must be used in a single (`from_stop_id`, `to_stop_id`) pair. Maybe I am being picky, but I prefer the language of the first statement.

**Comment by lionel-nj** [comment]
> Just re-reading this thread. I think the two following statements do not have the same meaning:
> 
> > If there is an elevator, then it must connect two locations that have level_id field assigned. (@aababilov)
> 
> > The level_id has to be present in the two stops referenced in from_stop_id and to_stop_id fields (@isabelle-dr)
> 
> The first statement has the loose requirement that an elevator must connect locations with `level_id` defined. Also, it makes no reference to the `level_id` being different (or the same) between locations connected by an elevator, which might be a favourable description given the possibility that a short elevator could be considered on the same level.
> 
> The second statement is quite different. It states that a given `level_id` (suggested by the language of "the" `level_id`) must be used in a single (`from_stop_id`, `to_stop_id`) pair. Maybe I am being picky, but I prefer the language of the first statement.

I agree. Do you think that `stops.level_id` should be described as conditionally required?

**Comment by lionel-nj** [comment]
Per discussion with @isabelle-dr, we will implement points 1 and 3 from https://github.com/MobilityData/gtfs-validator/issues/921#issuecomment-901352444 and will open the floor to discussions towards including the suggestion from Alexei in the specification.
