### ISSUE TITLE
When using -f command-line parameter no warning is given

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-validator#935]
**Describe the bug**
I was accidentally using the old `-f` command-line parameter with the main branch, and when I do I get a mysterious:

```
Execution failed for task ':main:Main.main()'.
> Process 'command 'C:/Program Files/Java/jdk-14/bin/java.exe'' finished with non-zero exit value 1
```

The help should print and say that `-f` is deprecated and use `-c` instead.

**How we reproduce the bug**
Steps to reproduce the behaviour:
1. Run validator with the old `-f` command line parameter from v2

**Expected behaviour**
Validator should tell me not to do that and what parameter to use instead

**Observed behaviour**
Validator just fails to execute without any output

**Environment versions**
- validator version: Tested with https://github.com/MobilityData/gtfs-validator/pull/925 but should also apply to main branch
- Java version: JDK 14
- OS versions: Windows 10

**Comment by lionel-nj** [comment]
@barbeau  I could not reproduce the behavior you witnessed. Here is the console output in different situations: 

**On the main branch or https://github.com/MobilityData/gtfs-validator/pull/925**

- When running the validator with `--help` or `-h` parameter: 
<img width="1160" alt="Capture d’écran, le 2021-07-26 à 15 29 10" src="https://user-images.githubusercontent.com/35747326/127047411-ada325ac-d830-4042-8a03-953b7619ee7f.png">

- When running the following command line: `java -jar gtfs-validator-null_cli.jar -u http://webapps.thebus.org/transitdata/Production/google_transit.zip -o output -f us`

<img width="1171" alt="Capture d’écran, le 2021-07-26 à 15 39 26" src="https://user-images.githubusercontent.com/35747326/127048553-89baca56-be55-4faa-b4fb-b41ee3556d48.png">

The same behavior is witnessed when running the validation using a configuration in IntelliJ.
