### ISSUE TITLE
Two rules doing the same thing: DuplicateRouteNameNotice and RouteShortAndLongNameEqualNotice

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#971]
## **Bug report** 

Two rules are doing the same thing: 
**1- DuplicateRouteNameNotice:**

Description in RULES.md:
> All routes of the same route_type with the same agency_id should have unique combinations of route_short_name and route_long_name.

Added to the validator on:
Jan 2021 in [PR#689](https://github.com/MobilityData/gtfs-validator/pull/689)

**2- RouteShortAndLongNameEqualNotice**

Description in RULES.md:
> Short and long name are equal for a route.

Added to the validator on:
December 2020 in [PR#501](https://github.com/MobilityData/gtfs-validator/pull/501)

I would recommend:
- keeping `RouteShortAndLongNameEqualNotice` because it's using one validator (`RouteNameValidator.java`) that is generating two other rules (`RouteBothShortAndLongNameMissing` and `RouteShortNameTooLongNotice`)
- removing `DuplicateRouteNameNotice` that has it's own validator (`DuplicateRouteNameValidator`).

**Comment by aababilov** [comment]
Correct me if I am wrong, but I believe that these notices describe very different things. We should keep both.

* DuplicateRouteNameNotice tells you that route1 and route2 have the same names:
* RouteShortAndLongNameEqualNotice tells you that route1 has `route_short_name == route_long_name`


DuplicateRouteNameNotice

route_id | route_short_name | route_long_name
-----------|-----------------------|-----------------------------
r1   | U1     | Southern
r2   | U1     | Southern


RouteShortAndLongNameEqualNotice
route_id | route_short_name | route_long_name
-----------|-----------------------|-----------------------------
r1   | L1     | L1

**Comment by isabelle-dr** [comment]
You're right @aababilov, they seem to be looking at different things that are both very useful to flag!
Thank you very much! 
The table you made here would be very useful in the documentation :) 

@lionel-nj if this is accurate we can close this issue and I'll make the docs a little more clear.

**Comment by lionel-nj** [comment]
Thanks for flagging that. Indeed the docs are confusing, will clarify.
