### ISSUE TITLE
new rule: No dangling locations in pathways.txt

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#974]
## **Feature request**

The GTFS specification says: 
> No dangling locations: If any location within a station has a pathway, then all locations within that station should have pathways, except for platforms that have boarding areas (location_type=4, see guideline below).

_https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#pathwaystxt_

As of now, this does not seem to be implemented. 

**Proposed solution**
Check all child stops of a station: they all **must** have pathways except for platforms that have boarding areas (i.e. at least one of the platform's children is a boarding area).

**Comment by aababilov** [comment]
I have an implementation of that rule at Google and I will open-source it soon.
