### ISSUE TITLE
new rule: no locked platforms

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#975]
**Describe the new validation rule**
The GTFS specification says: 

> No locked platforms: Each platform (location_type=0 or empty) or boarding area (location_type=4) must be connected to at least one entrance/exit (location_type=2) via some chain of pathways. Stations not allowing a pathway to the outside of the station from a given platform are rare.

_https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#pathwaystxt_

**Proposed solution**
1. Build the chain of pathway from/to  each platform (location_type=0 or empty) or boarding area (location_type=4) then evaluate if an entrance/exit is included in this pathway chain. If not, this is an error. 

**Error vs warning**
This should be an error (violates a requirement of the GTFS spec).

**Comment by aababilov** [comment]
I have an implementation of that rule at Google and I will open-source it soon.
