### ISSUE TITLE
Validator fails to report invalid dates

### ISSUE THREAD

**Issue by asvechnikov2** [MobilityData/gtfs-validator#976]
## **Bug report** 

**Describe the bug**
RowParser doesn't handle cases when date has an incorrect value for instance `20219999`. `GtfsData.fromString()` [calls](https://github.com/MobilityData/gtfs-validator/blob/52434454b747bb4085038f27563e98fee6018ca5/core/src/main/java/org/mobilitydata/gtfsvalidator/type/GtfsDate.java#L49) `LocalDate.of()` method which  may return `DateTimeException`.

**How we reproduce the bug**
Steps to reproduce the behaviour:
1. Add test to [GtfsDateTest](https://github.com/MobilityData/gtfs-validator/blob/52434454b747bb4085038f27563e98fee6018ca5/core/src/test/java/org/mobilitydata/gtfsvalidator/type/GtfsDateTest.java#L36) to parse string `20219999`
2. Run test and observe DateTimeException instead of `IllegalArgumentException`

Alternatively,

1. Modify a date in `calendar.txt` to has incorrect date `20219999`
2. Run validator for the feed
3. Observe no `InvalidDateNotice` issues in a report

**Expected behaviour**
GtfsDate must handle this type of exceptions and report them as `IllegalArgumentException`.

**Observed behaviour**
GtfsDate returns `DateTimeException` which is not known how to handle by RowParser and SystemError reported instead of `InvalidDateNotice`

**Comment by lionel-nj** [comment]
Thanks for flagging @asvechnikov2! It looks like @aababilov fixed this in #977. Thanks 🙏🏾
