### ISSUE TITLE
Two rules are doing the same thing

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#990]
Those two notices seem to be triggered in the same context: when a stop referenced by a row from `pathways.txt` has `location_type=1` (station).

LocationTypeStationForStopOnPathwayNotice implemented in [#967](https://github.com/MobilityData/gtfs-validator/pull/967)

PathwayToWrongLocationTypeNotice implemented in [#961](https://github.com/MobilityData/gtfs-validator/pull/961)

**Comment by aababilov** [comment]
This will be fixed in pull #978

**Comment by isabelle-dr** [comment]
Indeed, just saw this. Thanks!
